### ISSUE TITLE
[BUG] - CPU doesn't enters Deep Sleep when autotunneling on

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#102]
**Describe the bug**
CPU doesn't enters Deep Sleep when autotunneling on

**Smartphone (please complete the following information):**

- Device: Google Pixel 7 Pro
- Android Version: Android 14
- App Version 3.3.5

**To Reproduce**

Enter the app then enable tunneling when in mobile data then start service

**Expected behavior**
Foreground service doesn't affect the CPU ability to enter Deep Sleep

**Comment by kslcsdalsadg** [comment]
Not noticed this issue at previous versions.
The issue occurs even if "battery saver (beta)" is checked

**Comment by zaneschepke** [comment]
Hello! There is a 15 minutes wakelock on the CPU with battery saver and then a 30 minute wakelock on the CPU without battery saver. Are you seeing deep sleep prevented after these thresholds?

**Comment by kslcsdalsadg** [comment]
You're right. After a few minutes the CPU goes into Deep Sleep.
My apologies! ;)
