### ISSUE TITLE
[FEATURE] - Block connections outside VPN

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#104]
Is there a way to enable automation then disallow connections outside the VPN but then allow it when automation disconnects the VPN? 
It I set manually the toggle on Android settings -> Internet -> VPN the internet isn't working when automation disables VPN due to the app settings.

**Comment by zaneschepke** [comment]
Hello! Unfortunately, Android does not provide an API for controlling that setting. The only way around this is to not use the OS level kill-switch and create a kill-switch within the app that can be managed by the app to have the behavior you described. This was discussed previously in #52 and it is definitely something that is on the roadmap to be implemented.

**Comment by zaneschepke** [comment]
If I understand this feature correctly, this should be resolved with the latest VPN kill switch feature added for #52. If I'm mistaken, let me know and we can reopen.
