### ISSUE TITLE
[BUG] - VPN loses connectivity

### ISSUE THREAD

**Issue by Idowza** [zaneschepke/wgtunnel#107]
**Describe the bug**
VPN loses connectivity periodically 

**Smartphone (please complete the following information):**

- Device: Pixel 8 Pro
- Android Version: 14
- App Version: 3.3.5

**To Reproduce**

VPN will lose connectivity every now and then.  I'm not sure what triggers the loss in connectivity.  Stopping and stating the VPN will immediately restore connectivity.

**Expected behavior**

The VPN used to always keep connectivity.  All other devices stay connected.  (iOS, desktop)

**Screenshots (Only if necessary)**

**Additional context**

**Comment by Idowza** [comment]
I tested the official wireguard app, and it has the same issue.  

It still only seems to affect Android devices.

**Comment by zaneschepke** [comment]
> I tested the official wireguard app, and it has the same issue.
> 
> It still only seems to affect Android devices.

Thank you for this additional information. I am guessing this is the same DNS issue as has been commonly reported with both WireGuard's official app and this app (both apps use the same wireguard official core library). I'm currently brainstorming a few ways around this issue.

**Comment by Idowza** [comment]
It does seem to be quite a common issue.  When I first started using wireguard (and your app) it was flawless.  I unfortunately cannot think of what changed.

I did add "25" to the persistent keep alive which seems to fix the issue.  However it does say it's "not recommended.". Does using persistent keepalive leak your IP somehow?

**Comment by zaneschepke** [comment]
It do not think it leaks IP. It seems it just goes against WireGuard's silent protocol methodology. It is necessary for peers behind NAT and firewalls though. For more information, read [here](https://www.wireguard.com/quickstart/).

**Comment by zaneschepke** [comment]
There is a somewhat lengthy but useful dialog [here](https://github.com/WireGuard/wireguard-android/pull/26) about connectivity issues around DNS. To help mitigate connectivity issues, I've added a ping feature to auto tunneling that will attempt to restart the tunnel if pinging the server fails. It is a pretty rudimentary implementation/solution for now, but I hope to make it more robust in the future. I'll mark this one as closed for now with the release of [3.3.9](https://github.com/zaneschepke/wgtunnel/releases/tag/3.3.9) that has this ping feature.

**Comment by zaneschepke** [comment]
> > There is a somewhat lengthy but useful dialog [here](https://github.com/WireGuard/wireguard-android/pull/26) about connectivity issues around DNS. To help mitigate connectivity issues, I've added a ping feature to auto tunneling that will attempt to restart the tunnel if pinging the server fails. It is a pretty rudimentary implementation/solution for now, but I hope to make it more robust in the future. I'll mark this one as closed for now with the release of [3.3.9](https://github.com/zaneschepke/wgtunnel/releases/tag/3.3.9) that has this ping feature.
> 
> Does that need auto-tunneling turned on to work? In my use case, I want the tunnel always active and its unclear if autotunelling would allow that (and I'd like that autorestart feature)

Ah! I did not realize the auto-tunneling restrictions would not allow this feature to be used with AOVPN. Right now, it is purely an auto-tunneling feature, but it would be a very small change to make this work with AOVPN as well. I'll reopen this issue to get this added.

**Comment by TheDarkula** [comment]
@zaneschepke Thank you so much for your work!
Having this implemented for always-on would be amazing :)

**Comment by zaneschepke** [comment]
> @zaneschepke Thank you so much for your work! Having this implemented for always-on would be amazing :)

The ping feature is now allowed to work with AOVPN in the latest nightly version. You just have to only enable the ping feature and then start auto tunneling and it will monitoring the ping results and restart the tunnel if needed. 

If you enable block connections with this, your phone will likely not be able to re-resolve the dns when the tunnel is restarted so I would advice against this as that would defeat the purpose of the ping feature. 

I think updates to the ping feature and the ability to customize the interval/ip per tunnel should close this one out. If there are any issues we can reopen. Thanks!
