### ISSUE TITLE
Auto tunnel not switching over correctly

### ISSUE THREAD

**Issue by mgriner** [zaneschepke/wgtunnel#11]
First, thanks for making this, been wanting this from the official Wireguard app for years now.  On to the issue.

**Expected behavior:** 

1. Tunnel start: When away from home (not connected to trusted SSID) tunnel should be started.
2. Tunnel stop: When connected to home SSID(s) tunnel should automatically be disconnected.

**Issue:** 

1. Tunnel start: This behavior is working so far as expected.
2. Tunnel stop: This in general has worked but it failed at some point tonight.

**Steps that lead to issue:**

- I left the house, tunnel started as expected when I lost connection with home network.
- When I returned home and reconnected to the home network the tunnel stopped as expected.
- Sometime later, I checked my phone and saw the key icon, the tunnel had been restarted at some point (without leaving the house).

Unfortunately, I did not witness this happening at the moment, so I am not sure exactly what happened or know exact steps to reproduce.

**Special note:** I have seen this same behavior with the official Wireguard app + Tasker (actually it is the primary reason I was trying your app out!) and I am wondering if it has to do with my Wi-Fi extender in my house, it creates two new SSIDs (one on 2.4GHz one on 5GHz).  As I move through the house my phone will automatically switch between one of the three SSIDs (primary router, extender 2.4g, extender 5g) depending on signal strength.  All three SSIDs are entered in the app as trusted SSIDs.  I am wondering if there is some gap between switching from one SSID to another where the tunnel starts (because network is very briefly lost) but the new SSID connects so quickly it does not trigger the tunnel to stop again.

**Additional note:** After this happened, I was not able to disable the tunnel again by switching networks, turning off Wi-Fi on my phone, or by manually disabling auto tunnel and trying to manually turn off the tunnel in the app.  I had to force quit the app.  I will make another issue for this second problem though.

**Comment by zaneschepke** [comment]
Thank you for the extensive details! Could you also share your phone model/android version? 

I think I have seen this issue once before but I was never able to reproduce. I also have a similar wifi setup at my house. I'll investigate more to see if I can reproduce. If it is caused from rapid wifi network changes it may be worth adding a short delay and rechecking the network state before toggling VPN. 

Thinking about the logic now I definitely can see where this could be causing an issue. Can you confirm you had tunnel on mobile data enabled when this issue occurred?

**Comment by mgriner** [comment]
Phone Model: Pixel 3
Android Version: 12

Yes, I can confirm tunnel on mobile data was enabled.

**Comment by zaneschepke** [comment]
I believe this issue should be fixed now with the 2.3.2 release. Please let me know if it is not fixed and we can reopen. I've added a slight delay in auto tunneling to prevent the rapid toggling of the tunnel which I think was causing this issue.
