### ISSUE TITLE
[BUG] - No list of connections when connected and auto-tunneling active

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#116]
**Describe the bug**
No list of connections at the connections tab when auto-tunneling is active and connected

**Smartphone (please complete the following information):**

- Device: Pixel 7 Pro
- Android Version: Android 14
- App Version 3.3.6

**To Reproduce**
Enable auto-tunneling
Wait until your preferred tunnel is Connected
Go tunnels tab
See no tunnels are listed

**Expected behavior**
Tunnels are listed in any case, like in previous versions

**Screenshots (Only if necessary)**

![image](https://github.com/zaneschepke/wgtunnel/assets/31618496/264165f6-d75b-46b0-9e6d-7e24ced47173)

**Comment by zaneschepke** [comment]
Thank you so much for reporting this. I'm working on a fix now.
