### ISSUE TITLE
Cannot disable tunnel without force quit

### ISSUE THREAD

**Issue by mgriner** [zaneschepke/wgtunnel#12]
Possibly related to #11 

**Issue:** Tunnel was active with auto tunnel enabled.  Switching networks was not turning off the tunnel, so I disabled auto tunnel and tried to manually turn off the tunnel.  Pressing the toggle button on the tunnels page did not turn the tunnel off (the toggle button had no visual response when tapping it, and the VPN key icon was still present in notifications area).

I was able to eventually disable the tunnel by force quitting the app.

I have not since been able to reproduce the issue.

**Comment by zaneschepke** [comment]
I think this bug was also caused by the same issues as #11 which should now be resolved.
