### ISSUE TITLE
[BUG] - Save Button doesn't appears when editing a tunnel

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#120]
**Describe the bug**
Save Button doesn't appears when editing a tunnel

**Smartphone (please complete the following information):**

- Device: Google Pixel 7 Pro
- Android Version: Android 14
- App Version 3.3.7

**To Reproduce**

1.Go To Tunnels Tab
2. Edit a tunnel
3. Save button doesn't appears

**Expected behavior**
Save button appears or changes automatically stored when exiting edit page

**Comment by zaneschepke** [comment]
Hello! Ah, I see the bug. Making a fix now.

**Comment by kslcsdalsadg** [comment]
Thanks!
