### ISSUE TITLE
[BUG] - VPN Doesn't connect

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#121]
**Describe the bug**
App says VPN is connected but not really

**Smartphone (please complete the following information):**

- Device: Google Pixel 7 Pro
- Android Version: Android 14
- App Version 3.3.7

**To Reproduce**

1. Enable auto tunneling when on mobile data
2. Disable WiFi

App says tunnel is connected but not really, see screenshot
I have tried to remove app data then configure and also reboot the device some times

![image](https://github.com/zaneschepke/wgtunnel/assets/31618496/5904c55a-b204-4c15-8f46-911cfea09223)

**Comment by zaneschepke** [comment]
Hello! Are you using GrapheneOS? When Graphene first instals the app is auto enabled always-on VPN for some reason. Can you disable this and see if that fixes the issue?

**Comment by kslcsdalsadg** [comment]
That's no first install, but issue seems fixed after goto android settings->vpn->wg->forget vpn
