### ISSUE TITLE
Invalid SSL certificate (read the docs)

### ISSUE THREAD

**Issue by felixhummel** [zaneschepke/wgtunnel#130]
https://zaneschepke.com/wgtunnel-docs/overview.html

Cloudflare says "Invalid SSL certificate".

The same for your homepage: https://zaneschepke.com/

PS: Thank you for your work on wgtunnel! :)

**Comment by zaneschepke** [comment]
Thank you for notifying me of this. I'll work on getting this fixed!

**Comment by genomez** [comment]
This app is great!!! I just recently started using it in the last few days and it's intuitive enough that I have it running (Auto-tunneling, exceptions etc.), but am wanting to look over the docs for stuff I've missed. However, each day I check I keep getting the website error. Any update on the SSL certificate for the docs? 

Thank you for all your hard work!

**Comment by kjkent** [comment]
Came here to say the same thing; thanks for your work @zaneschepke ! Looking forward to testing this out.

**Comment by zaneschepke** [comment]
Site back up! Sorry this took me so long.

**Comment by genomez** [comment]
Great! Thanks again for all your hard work!
