### ISSUE TITLE
[Minor bug] Strange toast message with config that causes a parse error.

### ISSUE THREAD

**Issue by jhillest** [zaneschepke/wgtunnel#131]
**Background 📖**

I was setting up IPv6 for my Android device while sleep deprived, and I got confused by a strange toast message that does not make any sense when attempting to save the config.
After a bit of head-scratching, It turned out I had one extra colon before the IPv6 prefix in one of the address fields. Once I removed that, I could update the config as normal.

**Device info 📱**
- Pixel 6a
- Android Version: GrapheneOS, build number 2024030300 (Android 14)
- App Version: 3.3.8, obtained from F-Droid.

**Steps to reproduce 📜**
1. Set up a working IPv4-only config and verify it works.
2. (Optional) Follow the guide @ [https://www.digitalocean.com/community/tutorials/how-to-set-up-wireguard-on-ubuntu-20-04](url) while being sleep deprived and excited about your recent success. 🙃
3. Add the newly generated IPv6 addresses where they belong in the relevant fields, seperated by a comma, a space, but _add one comma too many before the IPv6 prefix_ [Example; for the Addresses field `10.10.10.2/32, fd0d:cfa6:2f72::2:/64`]
4. Hit the button to update the config with new values.
5. A non-sensical toast message appears, it just says `s2.l`

**Expected behavior 🧐**

A toast message warning about a parse error, like the original Wireguard app does. Or, some other, more human-friendly message.

**Need a logcat? 🤓**

GrapheneOS gives me easy access to the logcat for apps. I'll happily provide that if useful.

**Thank you! ♥️**

WG Tunnel's auto tunneling feature is pure gold.
Thank you for creating this!

Cordial regards
/Joachim

**Comment by zaneschepke** [comment]
Hello! Thanks for the detailed explanation! I'll look into this.

**Comment by zaneschepke** [comment]
Closed with [3.3.9](https://github.com/zaneschepke/wgtunnel/releases/tag/3.3.9)
