### ISSUE TITLE
[BUG] - Tile switches VPN to another tunnel falsely 

### ISSUE THREAD

**Issue by pikatchu2k3** [zaneschepke/wgtunnel#132]
**Describe the bug**

**Smartphone (please complete the following information):**

- Device: pixel 7 pro with graphene OS
- Android Version: 14 
- App Version []3.3.8

**To Reproduce**

1. Set two VPN tunnels in WG app
2. Put the quick tile into the status bar
3. Activate the selected tunnel through the tile
4. Disable the tunnel through the tile
5. Wait 
6. Enable the tunnel through the tile again

**Expected behavior**

The tile which is shown should be enabled like on the first try.
But instead the tile switches to the second tunnel.

**Screenshots (Only if necessary)**

Video of screen recording 
https://streamable.com/12jhhi

**Additional context**

If I make one tunnel as preferred tunnel (star it) then the tile won't switch but I need to tab the tile twice to enable the tunnel. 
That feels buggy and unresponsive.

**Comment by zaneschepke** [comment]
Hello! Thank you for reporting this. I'm looking into it.
