### ISSUE TITLE
[BUG] - Very slow speeds

### ISSUE THREAD

**Issue by ian-weir** [zaneschepke/wgtunnel#137]
**Describe the bug**
When using the app I am able to connect to my VPN but I'm getting very slow speeds ~50kbps. When using the official wireguard app I get ~100mbps. Using the same config for both apps.

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S10
- Android Version: Android 12
- App Version: 3.3.8

**To Reproduce**

1. Connect to vpn
2. Once connection is established run a speed test
3. Be sad at slow speeds 

**Expected behavior**
Similar speeds to wireguard official app

**Screenshots (Only if necessary)**

**Additional context**
Only potentially unique thing I can think of is I'm running the wireguard server via my Asus Router

**Comment by zaneschepke** [comment]
Hello! Thanks for reporting this. Are you using kernel mode or just regular userspace mode? I have heard one other report of slow speeds since I switched the app to using a compiled version of the wireguard lib instead of a precompiled one.

One thing you could try is install version 3.3.5 and see if there is still an issue. That would be the version before I made this lib change which could help determine if that is the cause of the slow speeds.

**Comment by AncientVamp** [comment]
I can confirm I also get very slow speeds (less than a megabit) on my Samsung Galaxy s20 Ultra using v3.3.6 and up. Switching back to v3.3.5 fixes the speeds (over 200Mbps now) and other issues. My other issues on v3.3.6+ was I had to hit the toggle 2 times before it would turn on and the app is not showing all my apps in the list of tunneling.

**Comment by zaneschepke** [comment]
> I can confirm I also get very slow speeds (less than a megabit) on my Samsung Galaxy s20 Ultra using v3.3.6 and up. Switching back to v3.3.5 fixes the speeds (over 200Mbps now) and other issues. My other issues on v3.3.6+ was I had to hit the toggle 2 times before it would turn on and the app is not showing all my apps in the list of tunneling.

Okay, I'm planning on releasing a new version today that rolls back the lib change. Thanks for the additional info.

**Comment by AncientVamp** [comment]
Just wanted to let you know that I installed v3.3.9 and all my issues I mentioned are fixed. Thank you :)

**Comment by zaneschepke** [comment]
> Just wanted to let you know that I installed v3.3.9 and all my issues I mentioned are fixed. Thank you :)

You're welcome! 😄

**Comment by ian-weir** [comment]
@zaneschepke thanks for the speedy resolution! Seems fdroid still has latest version at 3.3.8, any idea when .9 will be available there?

**Comment by zaneschepke** [comment]
> @zaneschepke thanks for the speedy resolution! Seems fdroid still has latest version at 3.3.8, any idea when .9 will be available there?

Np! Unfortunately, it can take up to one week before new app version is available in Fdroid. I do have a custom fdroid repo that you can add to the app to get updates as soon as they come out [here](https://github.com/zaneschepke/fdroid).
