### ISSUE TITLE
[BUG] - Cannot delete tunnel entry

### ISSUE THREAD

**Issue by tonyhardcode** [zaneschepke/wgtunnel#138]
**Describe the bug**
Cannot delete tunnel inside the app. The tunnel entry is still listed after confirming the deletion.

**Smartphone (please complete the following information):**

- Device: Chromecast with GoogleTV
- Android Version: Android 12
- App Version 3.3.5

**To Reproduce**

1. Go to tunnel
2. Click on the delete icon
3. Confirm deletion

I also just noticed Github has a 3.3.8 release but the Google Play Store is still on the 3.3.5 release a month later. Maybe this bug was picked up already? I can not confirm.

**Comment by zaneschepke** [comment]
Hello! I'll look into this and see if it is resolved on a later version. If not, I'll fix it for the next release. Google has been making me jump through hoops and is not allowing me to release a new version. I am hoping this next release resolves the remaining items for the play store.

**Comment by TadMSTR** [comment]
You can sideload the latest release from here or use F-Droid app store to get the latest. I've been using F-Droid to keep WG Tunnel updated. If you switch to F-Droid you may have to re-install. Just export your config and then import afterwards.

https://github.com/zaneschepke/wgtunnel/releases/tag/3.3.8

**Comment by zaneschepke** [comment]
This was an issue 3.3.8 as well. I found the issue and it will be fixed in 3.3.9.

**Comment by zaneschepke** [comment]
Closed with [3.3.9](https://github.com/zaneschepke/wgtunnel/releases/tag/3.3.9)
