### ISSUE TITLE
Android Auto plz check [BUG] - Problem with app

### ISSUE THREAD

**Issue by Ph8700** [zaneschepke/wgtunnel#150]
**Describe the bug**

Android Auto connect disconnect ever with wg Tunnel. Android Auto is include in the list.
Mobile Data on.

**Smartphone (please complete the following information):**

- Device: [Samsung S24 Ultra]
- Android Version: [Android 14]
- App Version [3.3.9]

Could you please check rhis in the Software and Version?
Thank you.

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by genomez** [comment]
Hello,

I'm not associated with the developer, but I started using the app a few weeks ago and really like it. 

I have the same phone as you and also had to figure out the Wireless Android Auto issue, so I thought I'd comment. 

You mentioned you have added Android Auto to the "include" list. I actually had to add Android Auto to the "exclude" list. 

I can run everything through WG Tunnel and exclude Android Auto and it works. I have also tested it by including only certain apps that I need to run back to my VPN server and as long as I don't include Android Auto, it works. 

I hope this helps.

**Comment by zaneschepke** [comment]
> Hello,
> 
> I'm not associated with the developer, but I started using the app a few weeks ago and really like it.
> 
> I have the same phone as you and also had to figure out the Wireless Android Auto issue, so I thought I'd comment.
> 
> You mentioned you have added Android Auto to the "include" list. I actually had to add Android Auto to the "exclude" list.
> 
> I can run everything through WG Tunnel and exclude Android Auto and it works. I have also tested it by including only certain apps that I need to run back to my VPN server and as long as I don't include Android Auto, it works.
> 
> I hope this helps.

Correct! Thank you for these details. Include is which apps are included in the tunnel, excluded is apps are able to operate outside of the tunnel. I will update the docs with these details to prevent confusion in the future.

**Comment by Ph8700** [comment]
Thank you so much. My failure. Yes thats correct exclude is the correct button.
