### ISSUE TITLE
[BUG] - Auto tunneling VPN fails after switching to a roamed LTE

### ISSUE THREAD

**Issue by vsatmydynipnet** [zaneschepke/wgtunnel#157]
While riding yesterday  found out that wgtunnel 3.4.0 on LOS20/Fairphone FP3+  fails if one crosses a broder and mobile connection switches to roaming.

- Setting: Auto Tunneling on mobile data ON
- Riding in home country VPN is turned on when leaving home SSID WIFI
- after crossing the border i lost connectivity (also no key which shows VPN on shown)
- paused Autotunneling and manually switched on the connection worked immediately

unsure how to further debug this one.

**Comment by zaneschepke** [comment]
I think this one might be fixed with the new auto tunneling changes. I'm going to mark as closed for now. If you encounter the error again, please let me know and we'll reopen this ticket.
