### ISSUE TITLE
AndroidTV small issues

### ISSUE THREAD

**Issue by marcelmah** [zaneschepke/wgtunnel#16]
Hi,

On my NVIDIA Shield Pro connected to a 4K TV I noticed two issues:
 - when I have a SSID set I am unable to remove it when with the controller, I can with the (air)mouse.
 - when I have an SSID set I am unable to see the last option about the always on VPN, see screenshot
![20230802_222039](https://github.com/zaneschepke/wgtunnel/assets/19894281/89b28f2c-8ef2-4a45-86c6-4e67e6cc3548)

**Comment by marcelmah** [comment]
Hi, I can confirm that I can now view all settings even when an SSID is set.

But removing the SSID is not possible with the road / ok button. I need to enable the air mouse function of my remote.

**Comment by zaneschepke** [comment]
> Hi, I can confirm that I can now view all settings even when an SSID is set.
> 
> But removing the SSID is not possible with the road / ok button. I need to enable the air mouse function of my remote.

I know it is a bit quirky, but are you able to delete the SSID by holding down on the ok button? I'm able to delete it on my Chromecast by doing this.

**Comment by marcelmah** [comment]
> > Hi, I can confirm that I can now view all settings even when an SSID is set.
> > But removing the SSID is not possible with the road / ok button. I need to enable the air mouse function of my remote.
> 
> I know it is a bit quirky, but are you able to delete the SSID by holding down on the ok button? I'm able to delete it on my Chromecast by doing this.

Correct, long pressing the ok button removes the SSID on releasing the button. 👍
