### ISSUE TITLE
[BUG] - Previous solved problem from version 3.3.3 resurrected "Tunnel disable frozen Bug"

### ISSUE THREAD

**Issue by elversoee** [zaneschepke/wgtunnel#163]
**Describe the bug**

After upgrading to version 3.4.1 from 3.3.9 because 3.4.0 was never available on the google play store for me
the Auto tunnel feature have started to "lock up" again.

after x amount auto tunnel operations (Activate/Deactivate) the wireguard tunnel on my phone is getting stuck in active tunnel, 
and will not disconnect, the WG tunnel App is working when opened i can enable/disable auto tunnel with pause/resume button but the tunnel will not disconnect, the only way to recover the intended function is to force stop WG tunnel from Android Apps menu and open it again, the have happened 2 times now after upgrading to version 3.4.1 of WG Tunnel app. from 3.3.9

it seems that the Bug that according to release notes of version 3.3.3 "Tunnel disable frozen Bug" was reintroduced       

- Device: Asus Zenfone 9
- Android Version: Android 14 with security updates for 4 April 2024
- App Version 3.4.1

**To Reproduce**

Use the App Normaly with it running in the background doing it`s thing

Expected that it disconnects when the phone connects to a trusted SSID

I have the WG Tunnel logs if necessary 

Thanks from Denmark

**Comment by zaneschepke** [comment]
Thank you for reporting this. Yes, any logs you have would be helpful. Please email them if you encounter the issue again. Thank you!
