### ISSUE TITLE
[Question] Autotunneling without "Tunnel on mobile data" purpose?

### ISSUE THREAD

**Issue by zilexa** [zaneschepke/wgtunnel#17]
I am wondering what "auto tunneling" is supposed to do, when none of the other 2 checkboxes have been enabled, like "tunnel on mobile data"?

For example, when I'm at home and turn off my WiFi (SSID added to trusted SSID list), and turn on the tunnel manually, it gets automatically disabled. 

Does the top option have any purpose, without "tunnel on mobile data" ? 

I'm just curious. I would expect only 1 toggle.

**Comment by zaneschepke** [comment]
> I am wondering what "auto tunneling" is supposed to do, when none of the other 2 checkboxes have been enabled, like "tunnel on mobile data"?
> 
> For example, when I'm at home and turn off my WiFi (SSID added to trusted SSID list), and turn on the tunnel manually, it gets automatically disabled. 
> 
> Does the top option have any purpose, without "tunnel on mobile data" ? 
> 
> I'm just curious. I would expect only 1 toggle. 

Hi! So I added tunnel on mobile data for people that always want to be connected to VPN when they are not on their home network. At the same time, it is also there for people who only want to tunnel when they are connected to public Wi-Fi networks and not when they are on mobile data. For example, people that want to conserve mobile data usage as VPN does add some extra mobile data usage. Or when people are very far away from their VPN server geographically where it will significantly slow their speeds. Perhaps it should be turned on by default though as I think that is the more common use case.

**Comment by zilexa** [comment]
Ah yes makes sense!
I only use it to automatically turn on/off the tunnel when I leave/join a trusted WiFi. Hence I would always need that second toggle as well. Thanks!

**Comment by zaneschepke** [comment]
No problem!
