### ISSUE TITLE
[FEATURE] - auto tunneling only specific apps

### ISSUE THREAD

**Issue by JohannCR** [zaneschepke/wgtunnel#171]
**Is your feature request related to a problem? Please describe.**
Using local wireguard vpn server (to access my LAN when out of home) + remote express vpn (to secure home connection).
When I'm back home, I use auto tunneling (awesome feature, thx a lot !) to deactivate wireguard, and navigate behind my express vpn. But some websites (Google for example) don't like express vpn, and throw a ton of Captchas... So annoying !

**Describe the solution you'd like**
This could be solved if, instead of pausing the wireguard vpn we could pause it only for specific apps but keep it running for others.

Kind of a mix between split tunneling and auto tunneling. (Split tunneling lets us exclude or include apps from wireguard tunnel, but is not affected by auto tunneling)

**Describe alternatives you've considered**
Only alternative is for me to deactivate express vpn for my device, but I would like to keep it for some apps, so it's not ideal...

Does that make sense or did I miss something ? Is that feasible?

**Comment by zaneschepke** [comment]
Hello! I hope I am understanding the exact ask, but I think this is already possible. I am not familiar with expressVPN, but this should be possible. 

I know other VPN providers (like Surfshark) allow you to export WireGuard configs from their service to use in third party apps.

I think the solution to your problem would be something like this:

- Configure home hosted server as primary tunnel (star it) (auto tunneling)
- Add expressVPN config to WG Tunnel and configure it for "tunnel on wifi name" with your home wifi name (auto tunneling) and w/split tunneling for the various apps you would like to be used in and outside of the tunnel

Let me know if that answers your question or if there is something I missed! Thanks!

**Comment by JohannCR** [comment]
That would work if expressvpn used wireguard, but they do not...
I may try to switch to nordvpn but not sure how nordlynx works and if it's compatible...

In case I wasn't clear, another way of describing the requested feature is to exclude some apps from the auto tunneling, effectively never disconnecting the tunnel for those apps.
Would it be complex to add ?

**Comment by zaneschepke** [comment]
> That would work if expressvpn used wireguard, but they do not... I may try to switch to nordvpn but not sure how nordlynx works and if it's compatible...
> 
> In case I wasn't clear, another way of describing the requested feature is to exclude some apps from the auto tunneling, effectively never disconnecting the tunnel for those apps. Would it be complex to add ?

That's crazy to me that they do not use WireGuard. 

Android has a limitation where only one VPN can be connected at a time so what you are asking for would not be possible unless you have a rooted phone.

**Comment by JohannCR** [comment]
I have not mentioned it but I use expressvpn on my router, not via mobile app 😉

**Comment by zaneschepke** [comment]
Ah, I see. Your router is the VPN client. 

Well, I don't think there is an action here for WG Tunnel. I think some of these issues you are having will probably disappear if you switch VPN providers or augment your network configuration. 

We can continue discussing different strategies on this issue, but I'll mark it as closed for now.
