### ISSUE TITLE
[BUG] - Weblate is locked because push to repository failed

### ISSUE THREAD

**Issue by Thalhammer** [zaneschepke/wgtunnel#172]
**Describe the bug**
Weblate locked translations because it was unable to push the changes to this repo.

**To Reproduce**

1. Go to weblate
2. Try to translate anything

**Expected behavior**
You can teanslate stuff.

**Comment by zaneschepke** [comment]
Hello! Sorry, this is my first time using Weblate. I'll work on fixing this.

**Comment by zaneschepke** [comment]
I missed a few steps when configuring Weblate. This should be good to go now!

**Comment by Thalhammer** [comment]
> Hello! Sorry, this is my first time using Weblate.

No problem, I just wanted to give you a headsup that it didn't work :)

**Comment by Thalhammer** [comment]
Seems like this is not quite done. Now it complains about a merge conflict for the spanish translation. I haven't used weblate before, but my guess would be that the strings file for spanish got changed both in the repo and on weblate which caused the conflict.

**Comment by zaneschepke** [comment]
I'll reopen this one until I resolve the merge conflict

**Comment by zaneschepke** [comment]
Okay, fixed the merge conflict. It should be good now.
