### ISSUE TITLE
[FEATURE] - mainline clients tunnel info page

### ISSUE THREAD

**Issue by weedy** [zaneschepke/wgtunnel#174]
I saw a commit for adding tunnel information. Is the one line under the tunnel name all we get? 

Could I ask for something closer to mainlines full page? I'd like to see traffic stats and the last handshake time more easily.

Maybe long pressing the tunnel while it's active. 

Thanks for your app and your time.

**Comment by zaneschepke** [comment]
Hello! The one line under tunnel is just the tunnel statistics for when the tunnel is active. 

To view the tunnel configuration information, long press on the tunnel and click the gear icon. Then, click "Edit tunnel" button in the "general" section. This will take you to the tunnel config screen that has all of the tunnel information.

**Comment by weedy** [comment]
Yes, but the "drop shadow" stats are tiny. 

The full page the mainline client gives me is easier to read. And most importantly tells me more. 
Beyond bytes, does the backend give you packet number sent?

**Comment by zaneschepke** [comment]
> Yes, but the "drop shadow" stats are tiny.
> 
> The full page the mainline client gives me is easier to read. And most importantly tells me more. Beyond bytes, does the backend give you packet number sent?

I can look into making this bigger/easier to read and making the drop shadow larger to accommodate. Unfortunately, everything currently being displayed is all of the tunnel statistics offered by the wireguard library.

**Comment by zaneschepke** [comment]
Marking this as closed as this has been improved and made larger in the latest version 3.5.3.
