### ISSUE TITLE
Need help with the starting configuration 

### ISSUE THREAD

**Issue by Chndnngr** [zaneschepke/wgtunnel#176]
I need help with how to setup this app, also i don't know from where i can generate the .cinfig file, bcus i am a newbie in this

**Comment by zaneschepke** [comment]
Hello! No worries. There are a few options. 

1. You can host your own WireGuard VPN server which will generate configs for your to use (a lot of modern home routers have a WireGuard VPN server built in).
2. You can use an online VPN provider that supports WireGuard and allows you to export WireGuard configs to third party apps (like Surfshark). 

Either one of these methods will be able to provide you with a .conf file or a QR code to import a config into the app.

**Comment by Chndnngr** [comment]
I don't know how to do any of these process! That's the main problem

**Comment by zaneschepke** [comment]
No worries! I would recommend joining one of our communities on Telegram or Discord. It will be easier in a chat format for myself and others in the community to help guide you on where to start.
