### ISSUE TITLE
[BUG] - Problem with app

### ISSUE THREAD

**Issue by Tom5051** [zaneschepke/wgtunnel#178]
Connects but no traffic across the vpn. waste of my time

**Comment by kafisc1** [comment]
> Connects but no traffic across the vpn. waste of my time

Please fill out the template so we can help you. Thank you!

**Comment by zaneschepke** [comment]
Please create a new issue with more detailed information if you would like help or considering joining one of our chats. 

It sounds like there is an issue with your server, network, or tunnel configuration. 

There are many people that would be glad to help.

**Comment by Tom5051** [comment]
user error. sorry. working
