### ISSUE TITLE
Add a quick toggle to the Android notification tiles

### ISSUE THREAD

**Issue by zilexa** [zaneschepke/wgtunnel#18]
The official Wireguard app allows you to easily turn on/off a tunnel via a tile in the same area where you toggle WiFi, flashlight etc. 
Please consider adding a tile there. It's the only thing I'm missing at the moment. 

For example, while connected to wireguard, which is actually connecting to my Homeserver, and only let's DNS requests go through the tunnel, AdGuard Home is filtering ads through DNS blocking. 

But sometimes a website doesn't work because an ad or some advertising related tracking is not loading. Especially when purchasing something or booking a service on a small/less known website or when abroad, when a public WiFi network requires registering. In those cases it's handy to temporarily toggle the tile to turn off the tunnel, finish the task and turn it on again.

**Comment by zaneschepke** [comment]
> The official Wireguard app allows you to easily turn on/off a tunnel via a tile in the same area where you toggle WiFi, flashlight etc. Please consider adding a tile there. It's the only thing I'm missing at the moment.
> 
> For example, while connected to wireguard, which is actually connecting to my Homeserver, and only let's DNS requests go through the tunnel, AdGuard Home is filtering ads through DNS blocking.
> 
> But sometimes a website doesn't work because an ad or some advertising related tracking is not loading. Especially when purchasing something or booking a service on a small/less known website or when abroad, when a public WiFi network requires registering. In those cases it's handy to temporarily toggle the tile to turn off the tunnel, finish the task and turn it on again.

A quick tile would be a nice additional feature for sure. The only question I have is how should this behave with auto tunneling? If auto tunneling is enabled, it would just toggle the tunnel back on.

**Comment by zilexa** [comment]
Aha, I would think the autotunnel feature triggers on network changes. Since there is no network change, it's not interfering?
Otherwise, if it is not depending on that, I would say it needs to "pause"?

**Comment by zaneschepke** [comment]
> Aha, I would think the autotunnel feature triggers on network changes. Since there is no network change, it's not interfering?
> Otherwise, if it is not depending on that, I would say it needs to "pause"? 

> Yeah, I can adjust the implementation to account for this but as it stands right now it would try to reconnect you unless you disable auto tunnel. My original implementation worked how you described but there were some additional issues with that approach that I would need to find an alternative solution for. This is definitely doable though. The android API for network connectivity is unfortunately super convoluted :D

**Comment by zilexa** [comment]
Actually, even if I open the app and disable the tunnel on the main screen, it reconnects! 
I would expect any manual action to overule the automatic setting. 

It's really unfortunate Google made it so complicated. Google. A necessary evil. The day iOS becomes a less walled garden, I will switch haha.

**Comment by zaneschepke** [comment]
> Actually, even if I open the app and disable the tunnel on the main screen, it reconnects! I would expect any manual action to overule the automatic setting.
> 
> It's really unfortunate Google made it so complicated. Google. A necessary evil. The day iOS becomes a less walled garden, I will switch haha.

Yeah, this is also expected behavior for now. You have to disable auto tunneling for now if you don't want it to force reconnect to tunnel. And agreed on the Google/Apple bit! 👍

**Comment by zaneschepke** [comment]
@zilexa I've been playing around with implementing this feature and I noticed that the tile for the official Android app doesn't work unless the WireGuard app itself is open. Doing research, it seems Google has heavily restricted what you are able to do from a tile while the app is closed. With that in mind, I'm trying to understand the benefit of using a tile if the app is already open.

**Comment by zilexa** [comment]
@zaneschepke strange. I switched back to the old solution because I can't do without easy "pausing" of the tunnel and it works just fine here. I don't open the app first. 
Tested on Asus ZenFone 9, Pixel 4a and Samsung S20.

**Comment by zaneschepke** [comment]
> @zaneschepke strange. I switched back to the old solution because I can't do without easy "pausing" of the tunnel and it works just fine here. I don't open the app first. 
> Tested on Asus ZenFone 9, Pixel 4a and Samsung S20. 
> 
> Edit: same applies for similar tiles of the PIA VPN app, but also the Aegis Authenticator app. I've never had to open those apps first.

Ah, I see. So the main purpose is to be able to pause the tunnel from the quick tiles. I have this working in dev. Starting tunnels is what doesn't work from quick tiles if the app isn't open. I'll work on that overrule feature so the quick tiles will work with auto tunneling as well. Thank you for the additional context.

**Comment by zilexa** [comment]
I have created a screen recording, after reinstalling the official app. You can see it works just fine without the app in the foreground or background:
https://streamable.com/wb0u0d

This way I can easily stop/start the tunnel, for example when a website doesn't work properly due to Adguard Home filters (poorly designed webshop or ticket website that requires ad trackers to load before the site functionality).

**Comment by mich2k** [comment]
> I have created a screen recording, after reinstalling the official app. You can see it works just fine without the app in the foreground or background:
> https://streamable.com/wb0u0d
> 
> This way I can easily stop/start the tunnel, for example when a website doesn't work properly due to Adguard Home filters (poorly designed webshop or ticket website that requires ad trackers to load before the site functionality).
> 

Asking sorry for the little ot but how do you manage to see the apps running in background from the notification panel? I have a Samsung s23, is something available only on your brand fw? Since I was trying to evaluate battery consumption too
I was also curious about your automate flow!

**Comment by zilexa** [comment]
@mich2k this is standard Google Android 13 functionality. It's on Pixel devices, Asus ZenFone and from the top of my head also Sony. Those are the brands that stay closest to "vanilla" clean Android. 

The Automate flow I believe I already linked to in an earlier ticket.

**Comment by zaneschepke** [comment]
> I have created a screen recording, after reinstalling the official app. You can see it works just fine without the app in the foreground or background: https://streamable.com/wb0u0d
> 
> This way I can easily stop/start the tunnel, for example when a website doesn't work properly due to Adguard Home filters (poorly designed webshop or ticket website that requires ad trackers to load before the site functionality).

Following your steps I am able to replicate the same behavior on both the wireguard official app and my implementation. However, the only reason this worked is because you closed the app with the VPN already running. This mean a service associated with your app was still running when the app was closed (VPN service). If you were to turn off VPN, then kill the app, and then try to toggle on VPN it will not work most of the time. Even toggling will fail with your previous steps if you wait long enough after toggling VPN off because Android will kill the service after the VPN is toggled off for a short period of time. 

I just want to make sure we are all aware of this behavior and that this is expected behavior.

**Comment by zaneschepke** [comment]
@zilexa This is now available in the latest version of the app on Google Play. Additionally, I made it so the quick setting tile toggle off now temporarily stops auto tunneling and toggles the tunnel off if auto tunneling is running (override you requested). From that point you can freely control tunneling from the tile without auto tunneling interfering. Auto tunneling is stopped until the app is relaunched/opened(it does not change your settings, it just stops the auto tunneling service). Upon the app opening, the app will see the setting is still enabled and relaunch the auto tunneling service. The tile enables, by default, whichever tunnel you have selected as your default tunnel in the setting screen. If there is none set, it will grab the first tunnel in your list of tunnels.  Thank you for the consistent feedback on this and please let me know if anything is not working as desired!

**Comment by zilexa** [comment]
Thanks so much for your super quick implementation!! Really great! Indeed it works as expected! 
Only thing I would ask is to re-enable auto tunneling when the tile is used to "unpause" (and if auto-tunnel is enabled in Settings). This way we don't have to think about opening the app.
Otherwise the tunnel will probably stay on when I'm back on home WiFi and never turn off (because I would forget. And my wife and parents sure won't think about reopening the app).

You then have a "configure once and forget" app, that always works autonomously :) just allows you to pause momentarily. 

But I'm already suprised with this super fast upgrade!

**Comment by zaneschepke** [comment]
> Thanks so much for your super quick implementation!! Really great! Indeed it works as expected! 
> Only thing I would ask is to re-enable auto tunneling when the tile is used to "unpause" (and if auto-tunnel is enabled in Settings). This way we don't have to think about opening the app.
> Otherwise the tunnel will probably stay on when I'm back on home WiFi and never turn off (because I would forget. And my wife and parents sure won't think about reopening the app).
> 
> You then have a "configure once and forget" app, that always works autonomously :) just allows you to pause momentarily. 
> 
> But I'm already suprised with this super fast upgrade! 

You're welcome! That idea makes a lot of sense. That will be a really quick fix I can add into the next release.

**Comment by zilexa** [comment]
Perhaps also cool feature (just an aestetic thing): show the name of the tunnel instead of "WG-tunnel". This would probably only make sense if people had multiple tunnels and tiles for each tunnel. I do not have that usecase btw, just thinking out loud, and don't even know if that is possible, to have tiles per tunnel. 

What might make sense is removing "on" or "off" in the tile name, you don't need that because the tile itself changes colour already. Just like other default Android tiles like Bluetooth that also do not show "on" and "off" in its title. 

Just minor visual things.

**Comment by zaneschepke** [comment]
> Perhaps also cool feature (just an aestetic thing): show the name of the tunnel instead of "WG-tunnel". This would probably only make sense if people had multiple tunnels and tiles for each tunnel. I do not have that usecase btw, just thinking out loud, and don't even know if that is possible, to have tiles per tunnel. 
> 
> What might make sense is removing "on" or "off" in the tile name, you don't need that because the tile itself changes colour already. Just like other default Android tiles like Bluetooth that also do not show "on" and "off" in its title. 
> 
> Just minor visual things. 

Good ideas! All sound like valuable improvements. Thank you!

**Comment by zilexa** [comment]
Just FYI, I noticed the tunnel turned on automatically, but the tile says its off. 

The tile does work though, if I click on it now, the tunnel will turn off (and the text of the tile still shows off). 
Not sure if its something you can do about. It's not a big thing because the function does work.

**Comment by zaneschepke** [comment]
> Just FYI, I noticed the tunnel turned on automatically, but the tile says its off.
> 
> The tile does work though, if I click on it now, the tunnel will turn off (and the text of the tile still shows off). Not sure if its something you can do about. It's not a big thing because the tile does work, turning off or on when I click on it.

Yeah. I've also noticed a little issue with the state not always been updated. Looking into it. Thanks again!

**Comment by zaneschepke** [comment]
@zilexa Added your suggestion on including the tunnel name to the tile as well as the auto tunnel toggling back on from the tile. I tried to improve the tile state issues but I think this may still be present in some situations. This is live in 2.3.7 which should drop soon as soon as Google approves!

**Comment by zilexa** [comment]
Thanks!
