### ISSUE TITLE
Obfuscate the tunnel

### ISSUE THREAD

**Issue by GrumpyGiuseppe** [zaneschepke/wgtunnel#181]
**Is your feature request related to a problem? Please describe.**
Some public wifis block the wireguard UDP connection and/or use deep packet inspection.

**Describe the solution you'd like**
Probably easier and less resource intense than masking the tunnel over https/socks5 would be to obfuscate the tunnel.
A fast and easy way would be this project:
https://github.com/dndx/phantun

**Describe alternatives you've considered**
https/socks5 masking

**Additional context**
Nothing

**Comment by zaneschepke** [comment]
Hello! I think this one is a duplicate as there is already a plan to add Amnezia WireGuard to prevent the deep packet inspection as requested in #149. I think this approach makes sense as it is already an android library that is a fork of wireguard-android. This approach should be somewhat plug-and-play for WG Tunnel.

**Comment by GrumpyGiuseppe** [comment]
Yeah, you're right.
I didn't know about Amnezia because before you developed this awesome app these thing were not possible on a non rooted android phone.
Cheers
