### ISSUE TITLE
[BUG] - Time of handshake resets to 0 and start over

### ISSUE THREAD

**Issue by hrshtein** [zaneschepke/wgtunnel#187]
**Description of the bug**
When connected to a server, it is shown that the handshake happened and showing handshake happened 20secs ago and the time was increasing second by second, then i switched to another app and when i again switched to wgtunnel, it was showing handshake happened 12secs ago, 13secs ago but the few mins has already been passed!

**Smartphone:**

- Device: Realme 9pro 5g
- Android Version: Android 14
- App Version: 3.4.2

**Steps to reproduce the behavior:**

1. Connect to a server and notice the handshake happened how many secs ago and let it to increase to 80-100sec ago.
2. Switch the app
3. Again switch to wgtunnel
4. Notice the handshake happened how many secs ago

**Expected behavior**
It should not to resets to 0 and start over.

**Comment by zaneschepke** [comment]
Handshake happens on an interval with wireguard where the client reaches out to the server to confirm there is still a connection. The app displays the last time in seconds since the last successful handshake. If I remember correctly, handshakes happen on a 2 minute interval.
