### ISSUE TITLE
[BUG] - Only 1 device is working with 1 config same time

### ISSUE THREAD

**Issue by CodeWithTamim** [zaneschepke/wgtunnel#195]
Hey bro.  I used the library. But I want to develop a vpn client like the other apps. So I made a app like that using this and I created wireguard config using 3xui panel. But the issue is with 1 config only 1 user can connect. So if I try to connect 10 users with the same config at the same time it dont work for the other 9. How to solve this issue?

**Comment by zaneschepke** [comment]
Hello! It does not sound like this issue relates to this app.  It sounds like you need some server management mechanisms to be able to create new configs on demand. 

See here: https://www.reddit.com/r/WireGuard/comments/kr8fx3/multiple_devices_with_one_client/
