### ISSUE TITLE
Add support for AndroidTV

### ISSUE THREAD

**Issue by zaneschepke** [zaneschepke/wgtunnel#2]

**Comment by mrbluecoat** [comment]
Possible approach: https://forum.tailscale.com/t/route-non-connected-device-through-exit-node/5800

**Comment by marcelmah** [comment]
Hi, 

I can't find it in the app store on my NVIDIA Shield Pro, are you sure It's now ready for AndroidTV?

**Comment by zaneschepke** [comment]
Hey! Sorry for the delay on this one. The app itself is ready for AndroidTV and I tested it on my TV but I keep running into issues with Google Play when I go to publish it to the AndroidTV store. I think I'm pretty close to meeting all of their store listing requirements. I'll let you know once I have successfully published it to the store.

**Comment by zaneschepke** [comment]
> Hi,
> 
> I can't find it in the app store on my NVIDIA Shield Pro, are you sure It's now ready for AndroidTV?


Hey! Sorry for the delay on this one. The app itself is ready for AndroidTV and I tested it on my TV but I keep running into issues with Google Play when I go to publish it to the AndroidTV store. I think I'm pretty close to meeting all of their store listing requirements. I'll let you know once I have successfully published it to the store.

**Comment by zaneschepke** [comment]
I am going to reopen this issue. Google is not like that not all of the UI elements are accessible using the D-pad so this is going to require some more testing and code changes.

**Comment by r2sd** [comment]
I have an Android TV box running Android 9 (armeabi-v7a). I updated the minSdk config to 28 (Android 9) and built the apk (using `./gradlew assembleRelease`). I am unable to install the resulting api though, I simply get a message after a few moments on the Android TV box saying App was not installed.

**Comment by zaneschepke** [comment]
I intentionally set minSdk to only be Android 10 and greater. There will potentially be other issues that will arise if you are adjusting the minSdk and putting the app on Android 9 (deprecated APIs that would need to be implemented to support that version).

**Comment by zaneschepke** [comment]
> I have an Android TV box running Android 9 (armeabi-v7a). I updated the minSdk config to 28 (Android 9) and built the apk (using `./gradlew assembleRelease`). I am unable to install the resulting api though, I simply get a message after a few moments on the Android TV box saying App was not installed. Please let me know if I'm missing something here (I've never worked on Android development before). And thanks for this amazing project. I'm using it on my phone and simply love it!

I intentionally set minSdk to only be Android 10 and greater. There will potentially be other issues that will arise if you are adjusting the minSdk and putting the app on Android 9 (deprecated APIs that would need to be implemented to support that version).

**Comment by zaneschepke** [comment]
I've made all of the required changes to support AndroidTV with D-pad navigation (it is a bit quirky but it works). I am closing this one out as I believe everything is done from a coding standpoint. I will post an update on this issue to notify you all once the app has been successfully approved and deployed to the AndroidTV Google Play Store.

**Comment by zaneschepke** [comment]
Happy to report the app is finally available on the AndroidTV Store. Sorry again for the wait!

**Comment by marcelmah** [comment]
Thnx! I just installed it.

The settings screen needs some work as the bottom options are off screen and I couldn't scroll. Now in my case I don't need them but others might.

Keep up the good work!

**Comment by zaneschepke** [comment]
> Thnx! I just installed it.
> 
> The settings screen needs some work as the bottom options are off screen and I couldn't scroll. Now in my case I don't need them but others might.
> 
> Keep up the good work!

Thanks for the feedback! Would you create an issue for that scrolling issue? If not, I can create one. Thanks again!
