### ISSUE TITLE
AndroidTV app tunnel listing forces the selection to the last (bottom) profile

### ISSUE THREAD

**Issue by tonyhardcode** [zaneschepke/wgtunnel#20]
Great app for the AndroidTV! The main functionality with split tunneling works great. The only issue I am having is when pressing the up and down buttons on my Chromecast with GoogleTV remote on the Home (Tunnel listing) screen. No matter how many times I press up the selection jumps to the last tunnel listing. I have about 5 tunnels added in and can only turn on the last one.

**Comment by zaneschepke** [comment]
Thank you for the detailed explanation of the issue! I'll look into this.

**Comment by zaneschepke** [comment]
@tonyhardcode This fix is now available on Google Play. Subtle difference in behavior is you now need to click once when hovering over a tunnel to access the controls/buttons, but you should be able to reach all tunnel controls now. Let me know if anything isn't working as desired! Thank you!

**Comment by tonyhardcode** [comment]
This issue seems to have come back up again. I'm on version 3.4.6
