### ISSUE TITLE
[FEATURE] - Tunnel on certain WiFi only

### ISSUE THREAD

**Issue by FingerlessGlov3s** [zaneschepke/wgtunnel#201]
**Is your feature request related to a problem? Please describe.**
I like the idea of having a tunnel auto turn on for untrusted WiFi, but what I would like is to have a profile only activate if I'm on a certain WiFi. Most of the time I don't need the VPN on as I don't join many WiFi hotspots and ones I do I trust enough to use without a VPN. There are some places where I'd like for the VPN to connect to access resources at home for example, but these places far out weigh the numbers of WiFi hotspots where I don't care to have it on and drain the battery.

**Describe the solution you'd like**
Auto connect when a certain WiFi name is detected otherwise don't connect at all. Effectively the reverse of how it works now 😅 with the whitelisting.

**Describe alternatives you've considered**
Trying to whitelist all the WiFi names I trust for the VPN to not come up, isn't manageable long term. I just want to add work's SSID, a few family members SSIDs and that's it.

**Additional context**
Don't believe any is needed.

**Comment by tomwhoiscontrary** [comment]
I would also find this very useful. In my case, there is one specific wi-fi network which i use regularly where the admins have blocked several useful sites. So, when i am on this network, i activate a tunnel to avoid all that. I don't use tunnels otherwise. It would be really nice to have the tunnel switch on and off automatically as a join and leave that network.

**Comment by zaneschepke** [comment]
This feature has been added in the latest nightly build. If you're confused on how to set this up, see the docs as I added a roughly written feature section on how to configure this with wildcards and exclusion symbols. Marking this one as closed for now.
