### ISSUE TITLE
[BUG] - Auto-Tunneling "restart on ping fail" switches tunnels on reconnect 

### ISSUE THREAD

**Issue by AMstuff** [zaneschepke/wgtunnel#202]
**Describe the bug**
When I have auto-tunneling enabled using the restart on ping feature, it does re-connect quite reliably, but it always switches to the first tunnel in the list. 

**Smartphone (please complete the following information):**

- Device: Pixel 4a
- Android Version: Android 14
- App Version: 3.4.2

**To Reproduce**
Steps to reproduce the behavior: See description

**Expected behavior**
It should re-connect to the tunnel that failed

**Comment by zaneschepke** [comment]
This should be fixed in the latest https://github.com/zaneschepke/wgtunnel/releases/tag/3.4.3

Let me know if you're still having issues and we can reopen. 

I plan to rework this feature to allow users to set the ping target and customize the frequency/cooldown in the near future.
