### ISSUE TITLE
v 3.4.3 exceptions are gone?

### ISSUE THREAD

**Issue by R7010A** [zaneschepke/wgtunnel#208]
Hi Zane,

are the exceptions for apps are gone in the new version 3.4.3?
I can´t find them in settings.
Some apps have to be set as excepitions, otherwise they don´t work anymore, e.g a file manager to conntect and transfer data via smb to the pc.

**Comment by zaneschepke** [comment]
Hello! What are exceptions for apps? Are you talking about split tunneling?

**Comment by R7010A** [comment]
Hi Zane,
in previous versions it was possible to exclude apps from tunneling, I think the correct name is split-tunneling, yes.
I can´t find this option anymore in v3.4.3

**Comment by zaneschepke** [comment]
Ah gotcha! Yeah, it is called split tunneling. You can access this by long pressing on a tunnel, click the gear icon, then on the tunnel settings screen there is a new floating action button with a pencil icon to edit the tunnel config (either WG or amnezia config).

**Comment by R7010A** [comment]
OMG, sorry for that. I am so stupid. Checked all possible buttons etc but not this one.
Thank you very much, especially for this amazing app.

**Comment by zaneschepke** [comment]
No worries! It is easy to miss because it is a new change and that screen never had a FAB before. Enjoy! :)

**Comment by R7010A** [comment]
Last question:
in tunnel settings, there is the option "connect autmatically" - tunnel for mobile data
Is it neccessary to set a wifi-name in the checkbox ("use wifi-name in tunnel"?)
Sorry for all the questions.

**Comment by zaneschepke** [comment]
No worries! This should help explain what that feature is for: https://zaneschepke.com/wgtunnel-docs/features.html#auto-tunneling-to-a-specific-tunnel-by-wifi-name-and-or-mobile-data
