### ISSUE TITLE
Auto-tunneling not working when there is a wifi connection without internet access

### ISSUE THREAD

**Issue by mich2k** [zaneschepke/wgtunnel#22]
Opening a different issue for this mostly to inform other users since this can be sketchy to detect

When you have both wifi and mobile data on (I think the standard configuration as of today) but you live or are in a zone where there is a wifi with captive portal or that does not provide internet access and is a trusted ssid the auto-tunneling breaks

(I wrote captive portal but may be any reason why wifi doesnt provide internet access)

This happens because the android os knows that the wifi doesnt provide internet access hence uses mobile data but the app checks only if you are, in general, connected to a trusted ssid

the logic in order to fix this should be something like:

- if(connected to trusted_ssid AND wifi provides internet) then disable vpn
- if(connected to trusted_ssid AND mobile data is in use) then enable vpn

from the screenshot is possible to see the wifi that states "No internet connection avialable", the mobile data ON in the notification panel and the vpn tunnel wrongly off (since yes i am also connected to a trusted ssid but actually I am on mobile data)

My main goal is to inform since I did not manage to understand why was not working until i went to check into wifi settings

To be fair I do not know if through android api this kind of control would be possible but forgetting the wifi network may be an option such as considering if to add that network as a trusted one with this issue in mind

![photo_2023-08-27_12-06-11](https://github.com/zaneschepke/wgtunnel/assets/13397578/a5bf3e49-ad6d-4987-b8e9-0227a3f6e5dd)
![photo_2023-08-27_12-06-11 (2)](https://github.com/zaneschepke/wgtunnel/assets/13397578/eda2fd89-a660-4757-8d10-851a06975484)

**Comment by zaneschepke** [comment]
Thanks for the detailed issue! This is definitely an edge case I've never tested before. I look into it.

**Comment by zaneschepke** [comment]
@mich2k This should be fixed as soon as google approves version 2.3.7. Let me know if anything doesn't work as expected! Thanks!

**Comment by zaneschepke** [comment]
@mich2k The fix for this is live now. Please let me know if it doesn't work as expected!
