### ISSUE TITLE
[BUG] - Problem with Google TV app

### ISSUE THREAD

**Issue by mpk995** [zaneschepke/wgtunnel#221]
**Describe the bug**
After the recent updates of the app, I am not able to edit the tunnel. When I click edit, it opens Wireguard/Amnezia option but not able to click any of those because none of those options are becoming reachable with remote. Working fine on phone because we can click on touchscreen but TV needs rely on remote going there

**Smartphone (please complete the following information):**

- Device: Google TV(Chromecast)
- Android Version: Android TV v12
- App Version 3.4.4

**To Reproduce**
1. Go to 'Home->Click on wheel->'
2. Click on 'Edit'
3. Not able to select Wireguard/Amnezia because those are not reachable with TV remote

**Expected behavior**
Wireguard and Amnezia should be reachable with remote

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Thanks for the report! Looking into this.

**Comment by mpk995** [comment]
Hi Zane,
On the re-resolve DNS related restart on ping failure is not working issue, can you please have an option in settings to restart the app on a schedule? if I can restart the app daily 4AM, any drops in connection will auto-resolve.
I tried to see if there is any scheduled restart option in Google TV but not there
Regards,Madhu Kalapala. 

    On Sunday 26 May, 2024 at 11:42:06 pm GMT-4, Zane Schepke ***@***.***> wrote:  
 
 


Thanks for the report! Looking into this.

**Comment by zaneschepke** [comment]
This should be fixed in the latest 3.4.5. I'm going to close this one for now, but we can reopen if you're still having issues.

**Comment by mpk995** [comment]
Hi Zane, though it is not yet in play store I installed 3.4.6 from fdroid on Google TV. I'm now able to click edit but it auto selects interface name and after I close keyboard, I am not able to move anywhere else

**Comment by mpk995** [comment]
Hi Zane, though it is not yet in play store I installed 3.4.6 from fdroid on Google TV. I'm now able to click edit but it auto selects interface name and after I close keyboard, I am not able to move anywhere else

Please reopen this.

Thanks  
 
  On Fri, May 31, 2024 at 12:36 AM, Zane ***@***.***> wrote:   


This should be fixed in the latest 3.4.5. I'm going to close this one for now, but we can reopen if you're still having issues.

**Comment by mpk995** [comment]
If I click back button to bring down keyboard, no nothing else is working. 

If I click on enter button of the keyboard, I am able to go to other fields

Maybe something to do with how keyboard is handled

**Comment by mpk995** [comment]
Keyboard is working fine after restart of the device 
Restart on ping failure attempted restart but server side IP address didn't refresh yet so didn't work. My server router restarted and IP refresh took about 2-3 minutes and WG tunnel reattempted connection and stayed with inactive connection. Can you please setup to try reconnect every 2 minutes till it gets successful handshake?

Madhu Kalapala 
 
  On Sat, Jun 1, 2024 at 12:07 PM, Zane ***@***.***> wrote:   


Reopened #221.
