### ISSUE TITLE
[BUG] - App crashes or hangs when Allowed IPs changed to remote LAN

### ISSUE THREAD

**Issue by ctag** [zaneschepke/wgtunnel#222]
**Describe the bug**
Hi,

I have a wireguard tunnel to let me access my home LAN when I am remote, but don't want to send *all* traffic through the tunnel, just 192.168.13.X IPs that correspond to the remote machines. When I have Allowed IPs in WG Tunnel set to `0.0.0.0/0` it works but sends all traffic. Updating Allowed IPs to `192.168.13.1/24` results in the tunnel either hanging at "connecting..." or the app crashing.

Feels like issue is related to https://github.com/zaneschepke/wgtunnel/issues/95

* Edit: If I set Allowed IPs to a single IP (192.168.13.100/32) then the connection works. It appears to only fail when I have the /24 block.

**Smartphone (please complete the following information):**

- Device: OnePlus 7 Pro
- Android Version: Android 14 - LOS 21
- App Version 3.4.4

**To Reproduce**

1. Go to edit a wireguard tunnel
2. Under Peer update "Allowed IPs" to the LAN (192.168.13.1/24)
3. Try to connect again.

**Expected behavior**

**Screenshots (Only if necessary)**

![image](https://github.com/zaneschepke/wgtunnel/assets/6200085/a02c4ec5-19f8-45dd-a30b-c44d18273a1b)

![image](https://github.com/zaneschepke/wgtunnel/assets/6200085/d32b0dfc-1e37-44bb-86aa-c49a35f64b8a)

**Additional context**

**Comment by ctag** [comment]
I forgot that zaneschepke had already helped me fix this issue in the past and I'd forgotten the solution.

When Allowed IPs is set to the remote LAN, the address must end with .0, not .1 or the address of a specific machine. I was trying to use `192.168.13.1/24` which does not work. Using `192.168.13.0/24` **does work**.

Not a bug, closing and apologies for the notification this generated.

**Comment by zaneschepke** [comment]
> I forgot that zaneschepke had already helped me fix this issue in the past and I'd forgotten the solution.
> 
> When Allowed IPs is set to the remote LAN, the address must end with .0, not .1 or the address of a specific machine. I was trying to use `192.168.13.1/24` which does not work. Using `192.168.13.0/24` **does work**.
> 
> Not a bug, closing and apologies for the notification this generated.

Np! Glad you found the fix!
