### ISSUE TITLE
Search app filter and show installed app/all system app in split tunneling 

### ISSUE THREAD

**Issue by vichhika** [zaneschepke/wgtunnel#23]
First of all, thanks you for develop this alternative app. Based on user experience, there are multiple applications that include or exclude tunneling. If we can search filter or show only installed app that a good feature than scrolling. Thanks

**Comment by zaneschepke** [comment]
You're welcome! Thank you for the feedback. This sound like a great additional feature.

**Comment by vichhika** [comment]
Thanks for prompt action but after I updated and connect VPN, I got a message "WG Tunnel isn't responding"
![image](https://github.com/zaneschepke/wgtunnel/assets/51940586/28f5d0a2-a4d6-4bc6-87c9-212c9f4706db)

**Comment by zaneschepke** [comment]
@vichhika Can you tell me your exact steps to reproduce issue and what version of Android you are using?

**Comment by vichhika** [comment]
Firstly, I import a conf file and try to enable a VPN connection. After a moment, the app force stopped, exit and disconnect VPN. I use Android 11.

**Comment by zaneschepke** [comment]
> Firstly, I import a conf file and try to enable a VPN connection. After a moment, the app force stopped, exit and disconnect VPN. I use Android 11.

Gotcha! I found the issue. I just pushed an updated fix version 2.4.2 to Goole Play. Should be live soon! Thanks again for all of the details and notifying me of the issue so quickly!

**Comment by zaneschepke** [comment]
@vichhika New fix is live on Google Play. Please let me know if it doesn't work for you!

**Comment by vichhika** [comment]
Thanks for your afford time, I have updated and test already. Work perfectly!
