### ISSUE TITLE
[BUG] - VPN can't be disabled after long run

### ISSUE THREAD

**Issue by gabriel20xx** [zaneschepke/wgtunnel#230]
**Describe the bug**
When running the vpn for a long time (multiple hours) in kernel mode, I am then not able to disable the vpn. Vpn switch in the app does not respond. 
When force stopping the app and starting it again, the connection is visibly disabled but it is still running in the background. 
I had to then restart the phone to switch or change the vpn again.

**Smartphone (please complete the following information):**

- Device: Poco F3
- Android Version: Android 14
- App Version: 3.4.6

**To Reproduce**

1. Turn on a connection in kernel mode
2. Wait some long time
3. Try to disable the connection

**Expected behavior**
The connection should get disabled.

**Screenshots (Only if necessary)**

**Additional context**
As a workaround an emergency button would be nice, that disconnects all connections if the bug can't be found or fixed

**Comment by havokator** [comment]
I am having the same exact problem. It is very frustrating because literally the only way to fix it is to reboot the phone which is a PITA. I will add that the app appears to allow me to toggle on a different VPN from my list, but I can definitely not disable the VPN completely. This is in kernal mode on a rooted android 14 phone.

**Comment by zaneschepke** [comment]
Hello! Do either of you know if this behavior happens in the official app? 

If it doesn't, there is a potential to fix the core issue. Otherwise, I'll have the create a work around for this issue.

**Comment by gabriel20xx** [comment]
This issue is still not fixed in the newest version

**Comment by zaneschepke** [comment]
> This issue is still not fixed in the newest version

Thanks for letting me know! Do you happen to have any logs?

**Comment by zaneschepke** [comment]
> This issue is still not fixed in the newest version

A few more questions:

- Did you ever experience this issue in the official app?
- I assume this happens when you've closed the app and reopen it after a while of the kernel mode running in the background?

Thanks! I'm currently still having a hard time trying to reproduce.

**Comment by gabriel20xx** [comment]
I haven't used the official app for a long time.
And yes for the second question, thats exactly what happens.
I just factory reset my phone and will take a look if the issue still present.
Will give feedback on that soon :)

**Comment by zaneschepke** [comment]
> I haven't used the official app for a long time. And yes for the second question, thats exactly what happens. I just factory reset my phone and will take a look if the issue still present. Will give feedback on that soon :)

Thanks! I think I found at least part of the problem and a was able to reproduce the behavior of the tunnel still being active in the background after a close and reopen of the app (despite turning it off after reopening). I also think this is related to #184. I'm working on a fix.
