### ISSUE TITLE
[BUG] Search domains disappear from DNS setting of WireGuard tunnel

### ISSUE THREAD

**Issue by Roy-Orbison** [zaneschepke/wgtunnel#233]
**Describe the bug**
Search domains added to the _DNS_ setting are not restored when editing the config, thus are lost on next save unless entered again each time.

**Smartphone:**

- Device: Pixel 8
- Android Version: 14
- App Version 3.4.6

**To reproduce**

1. Go to the tunnel config editor.
2. Add a search domain to the _DNS_ input, e.g. `10.5.5.1` -> `10.5.5.1, mydomain.example`, so that queries for `machine` are first qualified to `machine.mydomain.example.`.
3. Save the config.
4. Open the same tunnel's config.

**Expected behaviour**
The input should contain the search domain but only has the DNS server IP(s).

**Additional context**
[Search domains are supported][0] by the upstream project, and I've tested that they work as expected. I originally thought the separate setting as per #191 would be suitable, but I now believe it would be more consistent if the value in the _DNS_ setting matched [standard config][1] of other WG versions.

[0]: https://github.com/WireGuard/wireguard-android/blob/4ba87947ae3346280da76e13ef6981a631e43c3c/tunnel/src/main/java/com/wireguard/config/Interface.java#L353
[1]: https://rakhesh.com/linux-bsd/wireguard-search-domain/

**Comment by zaneschepke** [comment]
Hello! Thanks for the report. Anything that works in the official app should work in WG tunnel so I'll dig in and see what's going wrong.

**Comment by invisiblek** [comment]
I [rebased jdieter's commit](https://github.com/invisiblek/wgtunnel/commits/add-search-domain/) on the latest `main` branch (linting caused a bunch of merge conflicts). Been using it for months and it's been working great for me.

**Comment by zaneschepke** [comment]
> I [rebased jdieter's commit](https://github.com/invisiblek/wgtunnel/commits/add-search-domain/) on the latest `main` branch (linting caused a bunch of merge conflicts). Been using it for months and it's been working great for me.

This is great! Would you be willing to create a PR for this so we can add this fix to the app? If not, no worries. I can pull in the changes.
