### ISSUE TITLE
Image problem [BUG] - Problem with app

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#239]
**Describe the bug**
After installation, I see a mobile image on the Android TV box Small narrow image, you can hardly install it any furthe
r
**Smartphone (please complete the following information):**
Device Nvidia Shield TV pro
- Device: [e.g. Pixel 4a]
- Android Version: [e.g. Android 13]
- Android 11
- App Version [e.g. 3.3.3] 

Problem: it gives a mobile on the TV and no TV appearance 

- app 3.4.7

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
This is fixed now in latest nightly as described in #252
