### ISSUE TITLE
[BUG] - hung tunnel

### ISSUE THREAD

**Issue by zamansoum** [zaneschepke/wgtunnel#240]
**Describe the bug**
When the VPN turns on automatically after leaving a trusted wifi, often the tunnel does not work at all until I turn it off and on again. It is reproduced daily and on two different pixel phones. P7 and P6. I noticed on the tunnel stats that the RX is the one staying at 0 while TX was going up.  The Pixel 6 often has to turn off and on the tunnel for it to work while the Pixel 7 is fine once that initial restart is done.

The problem is not from the tunnel itself since it works without issues with the laptop and the pixel 7 does not have the p6 issue of restarting the connection in the middle of the day

I did not collect logs when it happened but will do next time and append them to this thread

**Smartphone (please complete the following information):**

- Device: Pixel 7 and Pixel 6
- Android Version: **P7**: Android 14 (Graphene OS) **P6:** Android 14 vanilla
- App Version 3.3.3

**To Reproduce**

Setup the auto-Tunelling
Leave the wifi range
See if the tunnel comes up and works fine

**Expected behavior**
Tunnel should automatically turn on when leaving the wireless network and it should not require any user manipulation.
Tunnel should stay stable and on during the day without the need of restarting it.

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! Thank you for reporting the issue.

This is an old app version. Could you please try the latest 3.4.7?

**Comment by zamansoum** [comment]
Installing now, will report back within a couple of days

**Comment by zamansoum** [comment]
Update seems to have fixed it. Thank you
