### ISSUE TITLE
[BUG] - PIN-lock bypass

### ISSUE THREAD

**Issue by ubinoob1** [zaneschepke/wgtunnel#242]
**Describe the bug**
PIN-lock can be easily bypassed by clicking notification

**Smartphone (please complete the following information):**

- Device: Motorola edge 30
- Android Version: Android 13
- App Version 3.4.7

**To Reproduce**

1. Setup pin-lock in app and make sure that app is asking for pin
2. Go to system settings>VPN>Settings and change "always-on" switch back and forth. VPN should reconnect.
3. Notification about connection should appear. Tap it.
4. Voila. You have access to app without entering PIN :)

**Expected behavior**
App should require PIN code in any case.

**Screenshots (Only if necessary)**

**Additional context**

**Comment by Livid96** [comment]
I came to report about it. But It's already done by a genius✨

**Comment by zaneschepke** [comment]
Hello! Looking into this! Thank you both for the report.
