### ISSUE TITLE
Always-On VPN support

### ISSUE THREAD

**Issue by drtiwarir** [zaneschepke/wgtunnel#244]
How to keep it always on,I am using it on Android tv,managing with a mouse.
But everytime I turn off the tv,the vpn tunnel closes.
I am using ethernet.

Thanks for your help

**Comment by zaneschepke** [comment]
Always on VPN does not exist for android TV, however, when you restart you device it should restart the tunnel after a delay (could be as much as 5 minutes) if the tunnel was running when you rebooted. There may be a setting that you need to enable if you are running 3.4.7 or a greater version.

**Comment by zaneschepke** [comment]
No problem!

Let me know if that does not solve your issue and we can reopen. I'll close the issue for now.

**Comment by drtiwarir** [comment]
Worked, thanks
