### ISSUE TITLE
[BUG] - Crash on Start

### ISSUE THREAD

**Issue by KobeLAL** [zaneschepke/wgtunnel#245]
**Describe the bug**
When I start the app via a shortcut, it crashes. 
[wg_tunnel_logs-1719661049.txt](https://github.com/user-attachments/files/16039850/wg_tunnel_logs-1719661049.txt)

**Smartphone (please complete the following information):**

- Device: [Pixel 6]
- Android Version: [Android 15]
- App Version [e.g. 3.4.6]

**To Reproduce**

1. Go to Start the app via the shortcut (vpn on)

**Expected behavior**
VPN should switch on via the shortcut.

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! This issue is fixed in 3.4.7. 

Marking this issue as closed. If you're still having issues, we will reopen.
