### ISSUE TITLE
[Question] - Auto tunneling if not connected to x network

### ISSUE THREAD

**Issue by aahmozart** [zaneschepke/wgtunnel#246]
Is there a way to always auto-tunnel, with exception if we're connected to x wifi network? Seems like the options in the app are to tunnel on untrusted wifi network, and I have to list all of them manually.

**Comment by zaneschepke** [comment]
Hello! The network names added to the settings page are your trusted networks. That is where you would want to add the WiFi name of the WiFi that yoy do not wish to tunnel on. This should solve your use case. 

Additionally, you can specify WiFi names under each individual tunnel config if you'd like to use a specific config on a particular WiFi network.

Let me know if that helps!

**Comment by zaneschepke** [comment]
Marking this one as closed. For additionally information, the latest nightly version has added support for wildcards in trusted SSIDs which could help further support your use case. 

https://github.com/zaneschepke/wgtunnel/releases/tag/nightly
