### ISSUE TITLE
[BUG] - Problem with app

### ISSUE THREAD

**Issue by Markushanysn** [zaneschepke/wgtunnel#248]
**Describe the bug**

**Smartphone (please complete the following information):**

- Device: [e.g. Pixel 4a]
- Android Version: [e.g. Android 13]
- App Version [e.g. 3.3.3]

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
No context to this bug.
