### ISSUE TITLE
[FEATURE] - Allow edit wireguard while automatic tunnel is active but no one is connected

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#251]
**Is your feature request related to a problem? Please describe.**

When "Automatic tunneling" is enabled, even if no one tunnel is connected, the added tunnels cannot be edited. Why?

**Describe the solution you'd like**
Tunnels will be edited even if automatic tunnel is enabled if the tunnel that I want to edit isn't connected.
There is not a reason to do not allow to edit tunnels if no connection is established in the tunnel.

**Describe alternatives you've considered**
-

**Additional context**
-

Thanks in advance

**Comment by zaneschepke** [comment]
This one should be resolved in the latest version. Marking as closed.
