### ISSUE TITLE
[BUG] - remove forcing portrait mode

### ISSUE THREAD

**Issue by 2011** [zaneschepke/wgtunnel#252]
**Describe the bug**

The latest release (3.4.7) forces the display into portrait mode (I absolutely can't stand this, and it causes horrible problems with my Android TV box).

**Smartphone (please complete the following information):**

- Device: S905X3 embedded system
- Android Version: 9
- App Version: 3.4.7

**To Reproduce**

Just start the app.

The monitor (television) obviously uses landscape mode. Forcing portrait mode kills all remote display connections, and well as makes it hard to even use the app (with the screen rotated 90 degrees with respect to the pointer device from the user's perspective).

**Expected behavior**

App should open without attempting to rotate the screen.

**Additional context**

No reason exists not to allow the user open and interact with the app in either orientation.

**Comment by zaneschepke** [comment]
Hello! This is fixed in the latest nightly release [here](https://github.com/zaneschepke/wgtunnel/releases/tag/nightly).

Once I get some more fixes/features in, I'll cut a new release to fdroid and google play with this fix as well.
