### ISSUE TITLE
[BUG] - Connection attempts on flight mode ✈️

### ISSUE THREAD

**Issue by matecode** [zaneschepke/wgtunnel#253]
**Describe the bug**
On flight mode, WG Tunnel try to establish a connection 

**Smartphone (please complete the following information):**

- Device: Pixel 6
- Android Version: Android 14
- App Version 3.4.6

**To Reproduce**

1. Turn on Auto Tunneling
2. Make your local WiFi the primary tunnel and also an exception of auto tunneling
3. Connect to 5G and local WiFi
4. Turn on flight mode

**Expected behavior**
On flight mode there should no connection attempts

**Comment by zaneschepke** [comment]
Hello! Why should there be no connection attempts on flight mode?

If you still have a WiFi connection on flight mode, it should still be looking to connect to the tunnel if that WiFi network is untrusted. 

I am probably misunderstanding the problem. Can you explain more?

**Comment by matecode** [comment]
Hi! Thank you for your response. If I turn on WiFI on Flight Mode your absolutely right. My experience was that i was turning on FlightMode, and therefore all connections drop (BL, WiFI and Cellular Network), but WG Tunnel tries to establish a connection (even there is no possible  Connection). It is not a big deal, I just wanted to leave a note as this is maybe not the desired behaviour.

**Comment by zaneschepke** [comment]
Right now, I think this is the expected behavior. Perhaps this is something that could be optimized in the future. 

Thanks for the note! I'll mark this one as closed for now.
