### ISSUE TITLE
[BUG] - Auto Tunnel not workin in 3.4.6

### ISSUE THREAD

**Issue by helmar74** [zaneschepke/wgtunnel#258]
**Describe the bug**
I installed  WG Tunnel with play store. I got 3.4.6 but auto tunneling isn't working. I read that i should be fixed in version 3.4.7
When will this version be available in play store?

**Smartphone (please complete the following information):**

- Device: [e.g. Pixel 4a]
- Android Version: [e.g. Android 13]
- App Version [e.g. 3.3.3]

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by popy2k14** [comment]
noticed the same with 3.4.6 after update to 3.4.7 auto tunnel (also with the new option restart on reboot) work without an issue for me. I have manually installed 3.4.7 from github here.

Also wanted to know how long publishing will take on play store for 3.4.7?
@zaneschepke is the 3.4.7 already published and in review process?

thx

**Comment by demaniak** [comment]
Hi!

I'm on 3.4.7 (installed from f-droid), and auto-tunneling is only half way working on android 14.

Specifically, auto-tunneling for mobile networks work fine.
But untrusted wifi, not so much.

As far as I can make out, the app is not requesting the background location permission, so I have no way to grant it.

**Comment by popy2k14** [comment]
Yeah, after using it longer, sometimes it switching on the tunnel, also when in trusted Wifi.
Maybe an  interval check again would be good?

**Comment by demaniak** [comment]
Today I was on a non-home wifi , not marked as trusted.

I found that I had to pause auto-tunneling in order to keep the tunnel active (after manually turning it on).

Otherwise I would turn it on, and a while later I would see that it turned off again (by itself).

**Comment by fumantsu** [comment]
I have the same with 3.4.6 and 3.4.7 in regards WIFI. Actually I don't use the option for enable for untrusted wifi but the one inside the tunnel (aka auto-tunneling).
Also I notice that in 3.4.7, notifications and actual operation of the application is lagging. Initial I thought that it is battery-power management options but... a) was working on 3.4.6 b) it is unrestricted.

**Comment by zaneschepke** [comment]
> noticed the same with 3.4.6, after update to 3.4.7 auto tunnel (also with the new option restart on reboot) work without an > issue for me. I have manually installed 3.4.7 from github here.
>
> Also wanted to know how long publishing will take on play store for 3.4.7?
> @zaneschepke is the 3.4.7 already published and in review process?

I skipped 3.4.7 because I had some issues with deployment. 3.4.8 is currently in review for google play.

> Hi!
> 
> I'm on 3.4.7 (installed from f-droid), and auto-tunneling is only half way working on android 14.
> 
> Specifically, auto-tunneling for mobile networks work fine. But untrusted wifi, not so much.
> 
> As far as I can make out, the app is not requesting the background location permission, so I have no way to grant it.

The app request background location permission once on first install when you first navigate to the setting screen. If you click, yes, it takes you to app settings to turn it on. There is not a permissions modal for background location on later version of android. 

On this one, can someone share a specific scenario that is not working as it relates to auto tunneling along with their auto tunneling settings? I am unable to replicate any of the issues currently shared on this issue.

**Comment by demaniak** [comment]
> > noticed the same with 3.4.6, after update to 3.4.7 auto tunnel (also with the new option restart on reboot) work without an > issue for me. I have manually installed 3.4.7 from github here.
> > Also wanted to know how long publishing will take on play store for 3.4.7?
> > @zaneschepke is the 3.4.7 already published and in review process?
> 
> I skipped 3.4.7 because I had some issues with deployment. 3.4.8 is currently in review for google play.
> 
> > Hi!
> > I'm on 3.4.7 (installed from f-droid), and auto-tunneling is only half way working on android 14.
> > Specifically, auto-tunneling for mobile networks work fine. But untrusted wifi, not so much.
> > As far as I can make out, the app is not requesting the background location permission, so I have no way to grant it.
> 
> The app request background location permission once on first install when you first navigate to the setting screen. If you click, yes, it takes you to app settings to turn it on. There is not a permissions modal for background location on later version of android.
> 
> On this one, can someone share a specific scenario that is not working as it relates to auto tunneling along with their auto tunneling settings? I am unable to replicate any of the issues currently shared on this issue.

Ok, thank you - after reinstalling the app, I saw that I had to say "yes" to the initial question, and THEN (the important step), manually grant the permissions on the subsequent permission screen.
After that, it seems to be working fine.

Auto-Mobile data tunneling has been working fine for me in 3.4.7.

Thanks again.

**Comment by popy2k14** [comment]
> > noticed the same with 3.4.6, after update to 3.4.7 auto tunnel (also with the new option restart on reboot) work without an > issue for me. I have manually installed 3.4.7 from github here.
> > Also wanted to know how long publishing will take on play store for 3.4.7?
> > @zaneschepke is the 3.4.7 already published and in review process?
> 
> I skipped 3.4.7 because I had some issues with deployment. 3.4.8 is currently in review for google play.
> 
> > Hi!
> > I'm on 3.4.7 (installed from f-droid), and auto-tunneling is only half way working on android 14.
> > Specifically, auto-tunneling for mobile networks work fine. But untrusted wifi, not so much.
> > As far as I can make out, the app is not requesting the background location permission, so I have no way to grant it.
> 
> The app request background location permission once on first install when you first navigate to the setting screen. If you click, yes, it takes you to app settings to turn it on. There is not a permissions modal for background location on later version of android.
> 
> On this one, can someone share a specific scenario that is not working as it relates to auto tunneling along with their auto tunneling settings? I am unable to replicate any of the issues currently shared on this issue.

3.4.8 arrived through play store, testing right now.
Thx a lot! 

I am now on an new phone (pixel 8 pro) and maybe it's working better than on the Xiaomi (which are known for killing background services/apps).

Will report back.

**Comment by zaneschepke** [comment]
Please try this prerelease build that I'm hoping fixes this issue: https://github.com/zaneschepke/wgtunnel/releases/tag/auto-tunnel-reliability-testing

**Comment by popy2k14** [comment]
@zaneschepke 
Was running 3.4.8 from play store a few days and noticed that sometimes the tunnel was turned on, also in trusted networks. Maybe because I have two access points (Unifi UAP-AC-LR) and when I am moving in my apartment my phone roams between the two.

Is there something like a grace period before switching or a recheck-intervall or something like that? 

Will try your new build and report back.

**Comment by zaneschepke** [comment]
> @zaneschepke Was running 3.4.8 from play store a few days and noticed that sometimes the tunnel was turned on, also in trusted networks. Maybe because I have two access points (Unifi UAP-AC-LR) and when I am moving in my apartment my phone roams between the two.
> 
> Is there something like a grace period before switching or a recheck-intervall or something like that?
> 
> Will try your new build and report back.

There is a one second delay before switching with a recheck, but perhaps this is not enough.

**Comment by popy2k14** [comment]
I also think that's not enough.

There are two solutions/workarounds to this:

- increase the 1 second delay -> better: make an setting with default value (maybe 3 seconds?)
- do a recheck, say after 10 seconds (in my case it would activate the tunnel after the second (somnetimes) and deactivates it after ~10 seconds).

I prefer the first solution/workaround.
What do you think?
Should i open another ticket/issue for this?

**Comment by zaneschepke** [comment]
> I also think that's not enough.
> 
> There are two solutions/workarounds to this:
> 
> * increase the 1 second delay -> better: make an setting with default value (maybe 3 seconds?)
> * do a recheck, say after 10 seconds (in my case it would activate the tunnel after the second (somnetimes) and deactivates it after ~10 seconds).
> 
> I prefer the first solution/workaround. What do you think? Should i open another ticket/issue for this?

Yeah, can you open a separate issue for this please? :)

Also, any other feedback on this test version?

**Comment by popy2k14** [comment]
> > I also think that's not enough.
> > There are two solutions/workarounds to this:
> > 
> > * increase the 1 second delay -> better: make an setting with default value (maybe 3 seconds?)
> > * do a recheck, say after 10 seconds (in my case it would activate the tunnel after the second (somnetimes) and deactivates it after ~10 seconds).
> > 
> > I prefer the first solution/workaround. What do you think? Should i open another ticket/issue for this?
> 
> Yeah, can you open a separate issue for this please? :)
> 
> Also, any other feedback on this test version?

Will do so.

About the pre release:
I was away two times from home (one time with another untrusted wifi) and wgtunnel has activated/deactivated the tunnel correctly for me. I am now back at work and leaving home every day for work.
So maybe we just wait a few more days to check if it was stable every day.
Will report back.

**Comment by popy2k14** [comment]
@zaneschepke have created an new issue regarding the roaming issue: https://github.com/zaneschepke/wgtunnel/issues/303

**Comment by popy2k14** [comment]
@zaneschepke want to report that not a single problem with the test version.
Will the 3.5.0 also go live on play store?

**Comment by zaneschepke** [comment]
> @zaneschepke want to report that not a single problem with the test version. Will the 3.5.0 also go live on play store?

Hopefully soon! It is in review right now. Most likely, it will be live by tomorrow. I always recommend the Fdroid version (which if you add my personal repo it is live right now). 😄

**Comment by popy2k14** [comment]
> > @zaneschepke want to report that not a single problem with the test version. Will the 3.5.0 also go live on play store?
> 
> Hopefully soon! It is in review right now. Most likely, it will be live by tomorrow. I always recommend the Fdroid version (which if you add my personal repo it is live right now). 😄

Yeah i know, but i dont want to install another shop on all family devices :-)
Hope i comes soon, currently 3.4.8 is in the play store.

thx for your efforts!

**Comment by zaneschepke** [comment]
> > > @zaneschepke want to report that not a single problem with the test version. Will the 3.5.0 also go live on play store?
> > 
> > 
> > Hopefully soon! It is in review right now. Most likely, it will be live by tomorrow. I always recommend the Fdroid version (which if you add my personal repo it is live right now). 😄
> 
> Yeah i know, but i dont want to install another shop on all family devices :-) Hope i comes soon, currently 3.4.8 is in the play store.
> 
> thx for your efforts!

Gotcha! Well, there was an issue with some google play requirement. I just fixed it and resubmitted. It should hopefully be approved soon.

**Comment by popy2k14** [comment]
thx a lot

**Comment by zaneschepke** [comment]
> thx a lot

Should be live now

**Comment by popy2k14** [comment]
Already got it, thx
