### ISSUE TITLE
[FEATURE] - Set IP for Ping check

### ISSUE THREAD

**Issue by yogifrog** [zaneschepke/wgtunnel#261]
Problem with Wireguard is when DynDNS IP Changes on Server Side then the Connection is Stuck
 
with a Ping to the Server over the Tunnel Would Help Detect when the Wireguard Connection is Dead and Restarting the Tunnel will help

**Comment by zaneschepke** [comment]
Hello! This functionality has been added to the latest nightly version: https://github.com/zaneschepke/wgtunnel/releases/tag/nightly

You can now set a custom ping ip address on the setting for each tunnel or restart on ping fail will default to pinging each of the peers for the tunnel. 

I'll mark this as closed for now. Let me know if you have any feedback on this feature or have any issues with it and we can reopen.
