### ISSUE TITLE
[BUG] - QUESTION (only), as appears also with Wireguard for Android app

### ISSUE THREAD

**Issue by michaelof** [zaneschepke/wgtunnel#269]
Hi Zane,

first of all THANKS for wgtunnel, I like it!!!

**Describe the bug**
RSTP stream can't be used via Wireguard, Android
Both with Wireguard app, also with wgtunnel.
Works fine with IPsec based tunnel on Android.
Works fine with Wireguard app on iOS.

**Smartphone (please complete the following information):**

- Device: Nokia 7.2
- Android Version: Android 11
- App Version: 3.4.7, F-Droid

**To Reproduce**
1. establish tunnel (other side is AVM Fritzbox 7590)
2. open rtsp stream via VLC
3. enter req. user/pw
4. no picture/stream shown

**Expected behavior**
rtsp stream  should be accesible via VPN

QUESTION:
As this issue also happens with Wireguard app, I guess it would make more sense to open it for Wireguard. But, as they don't use github, any hint how/where?
Tried to subscribe to mailing list, but didn't get a confirmation until now.

**Comment by zod076** [comment]
Does it work if you stream over the VPN to a public RTSP server like https://rtsp.stream/

**Comment by michaelof** [comment]
Not sure what you mean... AFAI unterstand rtsp.stream, they provide two test streams, to get consumed for testing. No idea how to "stream over the VPN" to rtsp.stream...

**Comment by tomtomclub** [comment]
I test the link its Send me an email, but via mobile phone, so it should work, adjust DNS, not use Google

**Comment by zaneschepke** [comment]
One of the community members in discord said this about this issue: "Wireguard upstream issue, not related to WG Tunnel. And Wireguard project seems to be EOL."

It seems this might be a known issue with wireguard on android.

**Comment by zod076** [comment]
> Not sure what you mean... AFAI unterstand rtsp.stream, they provide two test streams, to get consumed for testing. No idea how to "stream over the VPN" to rtsp.stream...
> 

You test rtsp stream over the VPN to the two test stream links they give you and see if that works.

**Comment by zaneschepke** [comment]
I can reopen this issue if there is an update, but it seems pretty stale so I will close it for now.
