### ISSUE TITLE
Auto-Tunnel does not work on wired connections

### ISSUE THREAD

**Issue by zaneschepke** [zaneschepke/wgtunnel#27]

**Comment by NetSamurai** [comment]
Just ran into this on my Shield TV. This app sounds like it solves many problems if it works for Android boxes.

**Comment by zaneschepke** [comment]
> Just ran into this on my Shield TV. This app sounds like it solves many problems if it works for Android boxes.

Currently working on a fix for this. It should be available in the next release.
