### ISSUE TITLE
[BUG] - Turning tunnel off/auto-tunneling paused required before editing tunnels

### ISSUE THREAD

**Issue by Dondrejohnson5** [zaneschepke/wgtunnel#271]
**Describe the bug**
WG Tunnel requires the tunnel to be turned off before it can be edited. Same error extends to other disabled tunnels in the app, if there are more than one, if auto tunneling is not paused or off entirely. The official WireGuard app does not present this restriction

**Smartphone (please complete the following information):**

- Device: Motorola Edge 40 Pro
- Android Version: 14
- App Version 3.4.7

**To Reproduce**

1: Import two WireGuard tunnels and enable the first one.
2a: Long press on the second tunnel to edit it, it is successful.
2b: Long press on the first one to attempt to edit it, an error occurs to prompt you to disable the tunnel first.
3: Start auto-tunneling, ensuring the first tunnel remains enabled
4: Now attempt to edit the second tunnel again, you can no longer edit this tunnel because auto-tunneling is on

**Expected behavior**
I expect to be able to edit the tunnel, save the new settings, and the tunnel instantly restarts for the new settings to take effect, similar to what official WireGuard app allows, with no need of tampering current auto-tunneling mode or disabling and re-enabling tunnel manually

**Screenshots (Only if necessary)**

**Additional context**

**Comment by dkoppenh** [comment]
I can edit an active tunnel on version 3.5.4

**Comment by Dondrejohnson5** [comment]
True, however when you save your changes, the tunnel does not update or restart, it is continuously active with your previous settings until you manually restart it

**Comment by zaneschepke** [comment]
This auto restart on config changes has been added in https://github.com/zaneschepke/wgtunnel/pull/476 and should be live in the nightly tonight and in the next release soon. Marking this as closed for now. If there are any issues, we can reopen. Thanks!
