### ISSUE TITLE
[BUG] - WG Tunnel opens every time a Tasker intent has been executed

### ISSUE THREAD

**Issue by Dondrejohnson5** [zaneschepke/wgtunnel#275]
**Describe the bug**
Any time a WG Tunnel intent in tasker is executed, the WG app opens, intrusively interrupting my previous activities on screen. This can cause major problems when meaning to execute tunnel change via Tasker in the background and are in the middle of another activity, such as a mobile game or watching on a streaming platform

**Smartphone (please complete the following information):**

- Device: Motorola Edge 40 Pro 
- Android Version: 14
- App Version 3.4.7

**To Reproduce**

1: Import a tunnel 
2: in main Settings tab, "enable app shortcuts"
3: as shown in the screenshot below, fill out all necessary fields for the Send Intent action in Tasker
* Action: `START` (or `STOP`)
* Extra1: `className:WireGuardTunnelService`
* Extra2: `tunnelName:nameOfTunnel`
(please make sure the entry after `tunnelName:` perfectly matches the name of the imported tunnel)
* Package: `com.zaneschepke.wireguardautotunnel`
* Class: `com.zaneschepke.wireguardautotunnel.service.shortcut.ShortcutsActivity`
* Target: Activity

4: Start the Tasker activity

**Expected behavior**
I expect that WG Tunnel will handle receiving the Tasker intent and act accordingly in the background, even with a toast message, without unnecessarily opening up the app in order to act upon the intent.

**Screenshots (Only if necessary)**
![Screenshot_20240725-231340_Tasker](https://github.com/user-attachments/assets/b1185ffb-20e6-4b06-b413-1b885a957075)

**Additional context**

**Comment by zaneschepke** [comment]
Hey! I don't have tasker to test this, but I made some changes that I think might fix it. Could you try it out when you get a chance? https://github.com/zaneschepke/wgtunnel/releases/tag/issue-275

**Comment by Dondrejohnson5** [comment]
I have recently installed this update and it seems that it has fixed the problem. Thank you
