### ISSUE TITLE
[BUG] - Installation does not work

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#276]
**Describe the bug**
Installation does not work
**Smartphone (please complete the following information):**

- Device: Nvidia Shield. Pro tv 
- Android Version: [e.g. Android 11]
- App Version [e.g. 3.4.7.(1)

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zod076** [comment]
Latest v3.4.8 has similar issue with a message saying it's not a valid package. I tried uninstalling 3.4.7 and installing the latest apk by downloading the apk from Github and install it and the error message appears.

**Comment by zer0fl0w** [comment]
confirmed.

3.4.7 works.

3.4.8 is not working as update nor clean install.

package not valid.

**Comment by zaneschepke** [comment]
> confirmed.
> 
> 3.4.7 works.
> 
> 3.4.8 is not working as update nor clean install.
> 
> package not valid.

Thanks for letting me know. Looking into this!

**Comment by EVOTk** [comment]
> confirmed.
> 
> 3.4.7 works.
> 
> 3.4.8 is not working as update nor clean install.
> 
> package not valid.

Sale issue for me

**Comment by zer0fl0w** [comment]
it is fixed with the new release just some minutes ago.

**Comment by zaneschepke** [comment]
This is now fixed in the latest build of 3.4.8 [here](https://github.com/zaneschepke/wgtunnel/releases/tag/3.4.8).

Thanks all!
