### ISSUE TITLE
[BUG] - Problem with app

### ISSUE THREAD

**Issue by Gothico74** [zaneschepke/wgtunnel#282]
**Describe the bug**
Won't update / install

**Smartphone (please complete the following information):**

- Device: Xiaomi Mi9lite 
- Android Version: Android 10
- App Version: 3.4.8

**To Reproduce**

Install, @90% error: not installed

**Expected behavior**
Install complete

**Screenshots (Only if necessary)**

**Additional context**
App Version 3.4.7 installs fine
No logs

**Comment by zaneschepke** [comment]
Hello! Thanks for reporting this. I found the issue with the app signature and rebuilt the latest release. It should now be fixed [here](https://github.com/zaneschepke/wgtunnel/releases/tag/3.4.8).
