### ISSUE TITLE
[FEATURE] - Check if Always on VPN enabled

### ISSUE THREAD

**Issue by Asper1x** [zaneschepke/wgtunnel#283]
Today, I spent half the day trying to understand why your app wasn't connecting to my server, only to find out that it was because I had 'always on VPN' enabled in another app, even though I wasn't connected to the VPN. Therefore, I recommend implementing a check to see if 'always on VPN' is enabled.

**Comment by zaneschepke** [comment]
Hello! I'm sorry, that sounds really frustrating. 😞  I agree, this would be a good feature to add. I'll look into it.
