### ISSUE TITLE
[BUG] Grey out settings 

### ISSUE THREAD

**Issue by mvevitsis** [zaneschepke/wgtunnel#292]
Enabling always-on VPN should probably also grey out 'restart on boot' as well as the auto tunnel settings found on the profile details in the profiles tab since as far as I can tell these settings do nothing when always-on is enabled. 

![Screenshot_20240729-001433_Gallery.png](https://github.com/user-attachments/assets/5fa82556-e810-428b-9bb3-8a7760df4889)

![Screenshot_20240729-001435_Gallery.png](https://github.com/user-attachments/assets/0d358682-b0e5-4c7c-84f5-abae09667df9)

**Comment by zaneschepke** [comment]
Hello! This is the correct behavior, as that restart also enabled the restart of the auto tunnel service and some feature are allowed to work with AOVPN. I have made a change to make sure that restart on reboot does not restart the tunnel if it is already started by AOVPN.
