### ISSUE TITLE
[BUG] - Bypass app blocking

### ISSUE THREAD

**Issue by konst5r** [zaneschepke/wgtunnel#296]
You can bypass the app lock by long pressing the app widget in the Android top menu.

- Device: Pixel 3a
- Android Version: Android 12
- App version: 3.4.8

Steps to reproduce the behavior
1. Lock the app
2. Add the app widget to the top menu in Android
3. Long press on this widget to open the app without lock screen
![Screenshot_20240731-095038~3.png](https://github.com/user-attachments/assets/3fd00c2f-2955-43b1-9925-386b13683c7e)

Expected behavior: The app should display the lock screen without providing access to the app itself.

**Comment by zaneschepke** [comment]
Hello! This is fixed in the latest nightly version [here](https://github.com/zaneschepke/wgtunnel/releases/tag/nightly) and will be part of the next release.
