### ISSUE TITLE
Suggestion: long press toggle action and switch tunnels in app

### ISSUE THREAD

**Issue by zilexa** [zaneschepke/wgtunnel#30]
1. Long press the tile: open WG Tunnel app (now it opens its App Info)

2. In the app itself, when a tunnel is active and I toggle another tunnel, simply switch tunnels (deactivate one and enable the other). Currently, I need to toggle to disable the active tunnel before toggling the other tunnel. Small improvement. 

3. I still find Settings slightly confusing for a first time user. Because you need to set 2 things (wifi SSID and tunnel) before the first toggle is usable. But then you also need that second toggle, so perhaps enable that automatically when the first one is enabled? Honestly I also don't know how to improve this screen much further. I love the functionality though 😁
That's all!

**Comment by zaneschepke** [comment]
Hello and thank you for the much appreciated feedback!

1. This sounds like a good feature. I'll look into this. 
2. This is actually supposed to work already (or used to work in the past) so this one is a bug that needs to be fixed. 
3. I definitely agree that the settings screen is not super intuitive and could use some enhancing. I does not make sense for Auto tunneling to be the first setting if it is dependent on two other subsequent settings in order to be enabled. At the very least I think some of these settings should be rearranged to have a more intuitive flow. I think it would be useful to add a card like background to show which settings are all related/grouped together and which are separate (which is not super clear at the moment). I'm sure I'll think of some other improvements for the settings screen as I start working on it.

**Comment by zilexa** [comment]
Regarding (3):
When auto tunneling is enabled, the "tunnels" screen has no function at all. Because you cannot start, stop any tunnel. You need to go to Settings and disable auto tunneling.
Consider adding a bar at the top (or bottom) with the autotunnel switch, when that main switch is enabled, all tunnels are greyed out or something. 

Or instead if you don't prefer the above (I wouldn't, but at least it would be more consistent). An alternative if you do want people to start, stop or switch between tunnels, with autotunneling enabled in the background, consider the same functionality as the tile, allowing to pause a tunnel.
You can still have the main switch on the tunnels page for consistency, but still allow to pause/start or switch tunnels.
Then, when someone switches between tunnels, maybe auto-update autotunneling to use the "latest enabled tunnel". 

With this in mind, I would suggest to "mark" the tunnel (on the tunnels screen) that will be used for auto tunneling. 
That way, you don't even need a separate option for it in Settings!
All you need in Settings is a "when to auto-enable?", 1) when leaving this WiFi 2) when mobile connection. 

Just woke up with this in mind! Rewrote this 6 times now. I'm sure it's plenty of inspiration :)

**Comment by zaneschepke** [comment]
> Regarding (3): When auto tunneling is enabled, the "tunnels" screen has no function at all. Because you cannot start, stop any tunnel. You need to go to Settings and disable auto tunneling. Consider adding a bar at the top (or bottom) with the autotunnel switch, when that main switch is enabled, all tunnels are greyed out or something.
> 
> Or instead if you don't prefer the above (I wouldn't, but at least it would be more consistent). An alternative if you do want people to start, stop or switch between tunnels, with autotunneling enabled in the background, consider the same functionality as the tile, allowing to pause a tunnel. You can still have the main switch on the tunnels page for consistency, but still allow to pause/start or switch tunnels. Then, when someone switches between tunnels, maybe auto-update autotunneling to use the "latest enabled tunnel".
> 
> With this in mind, I would suggest to "mark" the tunnel (on the tunnels screen) that will be used for auto tunneling. That way, you don't even need a separate option for it in Settings! All you need in Settings is a "when to auto-enable?", 1) when leaving this WiFi 2) when mobile connection.
> 
> Just woke up with this in mind! Rewrote this 6 times now. I'm sure it's plenty of inspiration :)

Thank you for this! You have a lot of great ideas here. I'll have to think through what makes the most sense to help improve the experience without changing too much of the inner workings of the app.

**Comment by zaneschepke** [comment]
Update - 1 & 2 are part of the 3.0.1 release that should be live on the app store soon. 

The setting screen rework will take a bit more time and consideration but I'll probably start working on it for the next release.

**Comment by zaneschepke** [comment]
@zilexa In the latest release (3.1.0) I think I implemented most of your suggestions except the main screen tunnel toggling to override auto-tunneling and the auto-tunneling status bar. I'm planning on adding the overriding to the next release.  For the status bar, I'm still considering options but I think there does need to be a bar showing when auto-tunneling has been overridden.
