### ISSUE TITLE
[FEATURE] - iOS

### ISSUE THREAD

**Issue by srulikuk** [zaneschepke/wgtunnel#300]
Do you have any plans to make this app for iOS?
I tried the app today (on android) for the first time and was blown away by how seamless the connections switched, my use case is when I am connected to the home wifi I need it to connect using a local IP (profile 1) and when I am out it should switch to profile 2 (which uses wan ip).
This app works amazingly, many thanks Zane Schepke

**Comment by zaneschepke** [comment]
You're welcome! Unfortunately, I do not have an plans right now to make an iOS app. I have considered building a cross platform desktop app that could potentially extend to iOS, but I don't know when I will have time to start it. 😆

**Comment by X-49** [comment]
> You're welcome! Unfortunately, I do not have an plans right now to make an iOS app. I have considered building a cross platform desktop app that could potentially extend to iOS, but I don't know when I will have time to start it. 😆

Please make a cross-platform application using KMP, a Linux version would be especially valuable as the AmneziaWG client is only available for Windows & macOS.
