### ISSUE TITLE
[BUG] - Improve Wifi Roaming (AutoTunnel delay)

### ISSUE THREAD

**Issue by popy2k14** [zaneschepke/wgtunnel#303]
**Describe the bug**
Was running 3.4.8 from play store a few days and noticed that sometimes the tunnel was turned on, also in trusted networks.
That's because I have two access points (Unifi UAP-AC-LR) and when I am moving in my apartment my phone roams between the two.

As stated by @zaneschepke there is currently a 1 second delay for switching an no recheck.

**Smartphone (please complete the following information):**

- Device: Pixel 8 Pro
- Android Version: Android 14
- App Version: 3.4.8

**To Reproduce**

1. Use Wifi with more access points
2. Move between those accespoints (so phone will auto roam)
3. Sometimes see the issue that tunnel is active but phone connected to trusted wifi

**Expected behavior**
not activate (or deactivate) the tunnel when on trusted network

**Additional context**
There are two solutions/workarounds to this:

- increase the 1 second delay -> better: make an setting with default value (maybe 3 seconds?)
- do a recheck, say after ~10 seconds (in my case it would activate the tunnel after the second (sometimes) and deactivates it after ~10 seconds).

I prefer the first solution/workaround.
Please let me know your thoughts.

I think this would improve reliability of auto tunneling further!

**Comment by zaneschepke** [comment]
Hey! I'm increasing to 3 seconds as requested. 

The reason there is no recheck is so people can override auto tunneling if they want to turn the tunnel off without auto tunneling turning it back on.

**Comment by popy2k14** [comment]
Thx, I think that would help.

**Comment by zaneschepke** [comment]
I'm going to mark this one as closed as I think the increase has fixed the issue. If it comes up again let me know and we can reopen.

**Comment by popy2k14** [comment]
@zaneschepke yes, totally fixed the issue. With the newest play versions. I did not had the issue. 

Thx
