### ISSUE TITLE
[BUG] - connected notification is not coming in 3.5.0 version

### ISSUE THREAD

**Issue by Livid96** [zaneschepke/wgtunnel#312]

**Comment by zaneschepke** [comment]
Hello! So this is expected. I removed the need for a persistent notification for the tunnel as may people were complaining about it and it also could cause reliability issues. I may add back connection status notifications as regular notifications (not persistent and dismissible) later as an option, but for right now this is the correct behavior. 

If this is a feature you would like to see, please create a feature issue requesting this functionality.

**Comment by E0697** [comment]
It would be great if you can add it back as an option, maybe with an additional disconnect button.

**Comment by zaneschepke** [comment]
> It would be great if you can add it back as an option, maybe with an additional disconnect button.

Hello! This is definitely doable. Would you add a feature request issue for it?

**Comment by E0697** [comment]
Sure thing! Will do.
