### ISSUE TITLE
[BUG] - Status bar icon missing

### ISSUE THREAD

**Issue by innit86** [zaneschepke/wgtunnel#315]
Status bar notification missing.

**Smartphone (please complete the following information):**

- Device: Pixel 7 Pro
- Android Version: Android 14
- App Version: 3.5.0 (ffeb089)

**To Reproduce**

1. Install app.
2. Connect to server.

**Expected behavior**

After connecting to a server an WGTunnel icon should be visible in status bar.

**Comment by zaneschepke** [comment]
Hello! This is actually expected as I removed the need for having a persistent notification for the tunnel. The only icon added to the bar should now just be the key icon (if you're using userspace). 

If you have any further questions, feel free to drop them here, but I'll mark this as closed for now.
