### ISSUE TITLE
[BUG] - Problem with app Reboot is not on

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#318]
**Describe the bug**

**Smartphone (please complete the following information):**

- Device: Android tv Nvidia Shield pro 64 bit
- Android Version: [e.g. Android 11
- App Version [e.g. Night

**To Reproduce**

1. Go to 'reboot device 
2. Click on 'just reboot now'
3. Scroll down to '.
4. See error. Doesn't arrive anymore

This is on the last 3 update since the white skin

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! So, am I understanding this correctly that the tunnel is not starting on reboot on Android TV?

**Comment by tomtomclub** [comment]
No I am temporarily back to 3.4.8 after reboot or power failure the app stays off

**Comment by tomtomclub** [comment]
> Hello! So, am I understanding this correctly that the tunnel is not starting on reboot on Android TV?
No I am temporarily back to 3.4.8 after reboot or power failure the app stays off

**Comment by zaneschepke** [comment]
Gotcha. This should be fixed on 3.5.1. Let me know if you have any issues.

**Comment by tomtomclub** [comment]
> Hello! So, am I understanding this correctly that the tunnel is not starting on reboot on Android TV?

No its not starting

**Comment by tomtomclub** [comment]
> Gotcha. This should be fixed on 3.5.1. Let me know if you have any issues.

Oke i test it i let you know
