### ISSUE TITLE
[FEATURE] - Use of auto-tunneling without location/gps (with root)

### ISSUE THREAD

**Issue by gabriel20xx** [zaneschepke/wgtunnel#322]
**Is your feature request related to a problem? Please describe.**
The app regularly checks background location for the auto-tunneling feature. This uses additional battery in the background.

**Describe the solution you'd like**
Instead of getting the connected network name/ssid via the android location permission, it should get the current connected network name/ssid via root if available. This removes the use of the gps module and saves battery.

**Describe alternatives you've considered**
Maybe this would also work with lsposed module or via shizuku.

**Additional context**
No additional context.

**Comment by burny0202** [comment]
+1 for this

**Comment by zaneschepke** [comment]
Hello! Yeah, I think this would be a really neat feature. I'll look into it.

**Comment by zaneschepke** [comment]
Anyone has any ideas on the command for getting this info from a root shell on android?

**Comment by segln** [comment]
Would you be able to implement it using Shizuku to get the same result? Thank you very much!

**Comment by zaneschepke** [comment]
> Would you be able to implement it using Shizuku to get the same result? Thank you very much!

Hello! Can I have more context? I don't know what this is.

**Comment by gabriel20xx** [comment]
Shizuku is an app that acts as a middleman for providing root permissions to apps. It can be used with an adb command (or root too). With it you can use root apps without having to root your device.
https://github.com/RikkaApps/Shizuku

**Comment by segln** [comment]
[Shizuku](https://github.com/RikkaApps/Shizuku) is a tool that allows apps to gain access to system-level APIs without needing root.

With Shizuku you can interact with WifiManager without root, as Shizuku enables apps to bypass some restrictions without needing root access.

**Comment by segln** [comment]
You might be able to execute command `dumpsys wifi` using Shizuku as well!

**Comment by burny0202** [comment]
I'm also having trouble getting this to work with Magisk root - Though after some testing it may be my wifi names.....

Can you confirm if _ (underscore) is a wildcard, also ? I have access points with just an underscore and number - They seem to be treated the same, even if I only add one as trusted

**Comment by zaneschepke** [comment]
I looked into Shizuku. It looks very cool and promising. Thanks all for sharing!

I want WG Tunnel to work without being dependent on another app, but I think adding optional support for Shizuku could be a really cool feature in the future. Would someone open a new issue for this?

**Comment by zaneschepke** [comment]
> I'm also having trouble getting this to work with Magisk root - Though after some testing it may be my wifi names.....
> 
> Can you confirm if _ (underscore) is a wildcard, also ? I have access points with just an underscore and number - They seem to be treated the same, even if I only add one as trusted

Yeah, there are a few issues with special characters since the wildcard changes. You could try using the wildcards yourself and see if that fixes the issue. 

I'll work on a fix for this.

**Comment by burny0202** [comment]
> > I'm also having trouble getting this to work with Magisk root - Though after some testing it may be my wifi names.....
> > Can you confirm if _ (underscore) is a wildcard, also ? I have access points with just an underscore and number - They seem to be treated the same, even if I only add one as trusted
> 
> Yeah, there are a few issues with special characters since the wildcard changes. You could try using the wildcards yourself and see if that fixes the issue.
> 
> I'll work on a fix for this.

Brilliant, this would be great. For now I have changed to always on 

Let me congratulate you on a great app
