### ISSUE TITLE
[BUG] - Amnezia parameters do not remain

### ISSUE THREAD

**Issue by marek22k** [zaneschepke/wgtunnel#329]
**Describe the bug**

Hello,

when I import an Amnezia configuration via a file and then edit it, I do not see the extra Amnezia parameters that were in the file.

The same happens when I copy a vanilla WireGuard tunnel, then enter Amnezia parameters there, save it and then edit it again.

(Following https://github.com/zaneschepke/wgtunnel/issues/149#issuecomment-2308394439)

**Smartphone (please complete the following information):**

- Device: Fairphone 5
- Android Version: Android 14 / CalyxOS 5.9.0
- App Version: 3.5.1 / F-Droid

**Expected behavior**
The parameters are retained.

**Screenshots (Only if necessary)**

https://github.com/user-attachments/assets/d4f1280c-18e2-44b4-b9db-256c3e5d4077
https://github.com/user-attachments/assets/397442c5-b16c-425c-8013-b781772333de

(I have cut away the file selection, as it contained personal folders and files, among other things).

**Additional context**

The VPN connection does not seem to work either. However, it does on my computer.

**Comment by zaneschepke** [comment]
Hello! I'll take a look at this and see if I can reproduce.

**Comment by marek22k** [comment]
Edit: Works when `Use Amnezia userspace` is enabled in Settings.

**Comment by alexandervlpl** [comment]
@zaneschepke Importing Amnezia configs is completely broken without `Use Amnezia userspace`. Tried via file or QR code, none of the Amnezia-specific values are loaded and the tunnel can't connect.

**Comment by zaneschepke** [comment]
Hello! This should be fixed in the latest nightly. Let me know if there are any further problems and I can reopen.

**Comment by alexandervlpl** [comment]
Awesome, can't wait for the next F-Droid release!
