### ISSUE TITLE
[BUG] - After reboot is ON but known wi-fi

### ISSUE THREAD

**Issue by KarlKarp** [zaneschepke/wgtunnel#335]
**Describe the bug**
After reboot the Smartphone, the wireguard tunnel is ON, but it's in known wi-fi area. It should be OFF.
Must be switched off manualy.

**Smartphone**
- Device: Samsung Galaxy S23 ultra
- Android Version: 14
- App Version: 3.5.1

**To Reproduce**
See wgtunnel homepage after reboot smartphone

**Expected behavior**
code check

**Screenshots (Only if necessary)**

**Additional context**
About 4 weeks ago it works normaly

**Comment by KarlKarp** [comment]
Also after reboot today it has the same behavior.

**Comment by zaneschepke** [comment]
Hello! Did this happen with auto tunnel enabled or disabled?
