### ISSUE TITLE
[BUG] - App shortcuts won't work 

### ISSUE THREAD

**Issue by hasifantasy** [zaneschepke/wgtunnel#338]
**Describe the bug**
The 4 App Shortcuts (VPN on / VPN off / Auto tunnelling on / Auto tunnelling off) don't work at all

**Smartphone (please complete the following information):**

- Device: Poco X4 GT
- Android Version: 14
- App Version 3.5,1

**To Reproduce**

Long tap on the app icon raises the shortcut menu, but short tapping on a Menu entry doesn't seem to change the app behaviour.

**Expected behavior**
Working shortcuts 

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! I just want to confirm, do you have app shortcuts enabled on the setting screen?

**Comment by hasifantasy** [comment]
Hello Zane,

I didn't, because in my German localisation there is no configuration item "shortcuts", but "App-Verknüpfungen aktivieren" which I did not realized as "Shortcuts enabled". 
But now I have - and it works.
My Bug report can be closed.
Thanks for your work.
Regards 
Stefan

Am 7. September 2024 04:12:19 MESZ schrieb Zane Schepke ***@***.***>:
>Hello! I just want to confirm, do you have app shortcuts enabled on the setting screen?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/zaneschepke/wgtunnel/issues/338#issuecomment-2335002449
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Mit freundlichen Grüßen
Stefan Meister
***@***.*** 
***@***.***

**Comment by zaneschepke** [comment]
Gotcha! No worries! Is this not the proper translation? If so, would you help me understand the proper translation and then I can update this item.

**Comment by ExXxtr3me** [comment]
I've got the same problem with the nightly builds, shortcuts are enabled in the settings but starting them says they are not available.
