### ISSUE TITLE
[BUG] - root mode switch is missing in settings page

### ISSUE THREAD

**Issue by rdmitry0911** [zaneschepke/wgtunnel#339]
**Describe the bug**
root mode switch is missing in settings page
**Smartphone (please complete the following information):**

- Device: Samsung A52s 5G
- Android Version: Andeoid 12 rooted with Magisk
- App Version 3.5.1

**To Reproduce**

1. Go to Settings page (gear icon in the bottom raw)
2. There is no "kernel" block and no "root mode" switch anywhere in settings

**Expected behavior**
Should see root mode switch in  kernel block
**Screenshots (Only if necessary)**
![telegram-cloud-photo-size-4-5951895572501872957-y](https://github.com/user-attachments/assets/d98eafe9-bcf3-416a-984f-1391f5283aa5)

**Additional context**

**Comment by zaneschepke** [comment]
Did this switch work for you in the past or does this device work with kernel mode on the official app? There is a chance that your device is not supported for kernel mode.

**Comment by nillebor** [comment]
What kind of software do you use?
I use LineageOS (Poco F3) and the switch is there and also works without problems.
The Samsung software is known to block a lot.

**Comment by zaneschepke** [comment]
Most likely if this situation happens it is one of two problems:

1. Your phone is not properly rooted
2. Your kernel is not supported by WG

I don't think this is a bug so I'm going to mark it as closed, but we can continue the discussion and reopen if necessary.
