### ISSUE TITLE
Support for FireTV

### ISSUE THREAD

**Issue by raphi-0901** [zaneschepke/wgtunnel#34]
I found your app on my FireTV and it looked like a great workaround to connect to my home network.

Unfortanetly, trying to open a config file opens a file explorer where nothing can be selected and no files are shown. I think this is not an issue by your app, but you could add a feature to add the parameter of the wireguard connection by yourself instead of the config file.

**Comment by zaneschepke** [comment]
Hello! Yeah, I'm working on adding a screen where you can enter a config manually. I have heard of this issue before on FireTV that you are experiencing. Have you tried installing Cx File Explorer or a similar app? That usually fixes the issue.

**Comment by raphi-0901** [comment]
I tried it right now with CX explorer, but the same file explorer as before pops up.

**Comment by zaneschepke** [comment]
What version of the app do you have installed? You can see this on the support screen.

**Comment by raphi-0901** [comment]
It is version 3.0.2

**Comment by raphi-0901** [comment]
Thanks for your input. I already got my VPN connection working with the standard WireGuard app!

**Comment by yo12222** [comment]
Reopening as this is still not fixed on v3.0.3 (verified in app).
Trying to import a tunnel sends me to a screen that shows "Recent" (as recently opened files) with nothing in it.
However, if you press the select button right after reaching that default file browser screen, you can open the left menu.
The left menu contains nothing, unless you install a file browser like cxfilebrowser and then you can see other stuffs like downloads, processes, etc..
Yet, nothing is selectable.

In general, the moment you reach that default import file screen, you have 1 button press to do, after that, you cannot do anything at all.
Its like the arrows buttons do nothing and you are currently not hovering any button, youre stuck, with nothing else to do.

FireTv Stick 4K Max from friend.
He has the last edition.
