### ISSUE TITLE
[FEATURE] - Use Phone as a VPN Router

### ISSUE THREAD

**Issue by helmar74** [zaneschepke/wgtunnel#347]
**Is your feature request related to a problem? Please describe.**
It would be nice to use a Smartphone as a VPN Router for connected devices in hotspot

**Describe the solution you'd like**
Function like that:
1. Turn on VPN Tunnel in wgtunnel Android APP (in mobile network)
2. Enable Hotspot on Smartphone
3. Connect 1 or more WIFI Devices to Androids Hotspot (e.g laptops or tablets)
4. Route all traffic from the "hotspot connected devices" thru tunnel

**Describe alternatives you've considered**

**Additional context**

**Comment by Handrail9** [comment]
If I'm understanding what youre asking for correctly I dont think this can be done without root/a custom ROM. I'm on CalyxOS and this feature is built into the ROM. I'd be glad to be proven wrong though

**Comment by helmar74** [comment]
OK sorry to hear, that is only possible on rooted devices. 
I can't use a custom rom or a rooted device regarding some apps aren't working anymore (e.g. homebanking)
So it looks like the feature can't be realized somehow?

**Comment by zaneschepke** [comment]
I think @Handrail9 is probably right, but I'll look into it to confirm.

**Comment by zaneschepke** [comment]
I think it is safe to mark this one as closed.
