### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by ASerbinski** [zaneschepke/wgtunnel#349]
**Describe the bug**
Regarding the feature: "Automatic auto-tunneling service and/or tunnel restart after reboot or app update"

Does this require the device to be unlocked before it can connect? Or can it autostart on reboot without any intervention?

**Comment by zaneschepke** [comment]
Hello! This feature only works once the screen has been unlocked. As far as I know, I don't think there is a way around this. The phone itself does not really fully boot until the first unlock after a reboot
