### ISSUE TITLE
Edit to make it safe see photo

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#355]
**Describe the bug**
It is not possible to adjust and save this for Android TV box with a remote control, see photo  It disappears when you are safe it, so you must use muis , Very difficult indeed 
###### Question ######
Dns Name is not possible, 

[IMG_20240919_09131(https://github.com/user-attachments/assets/8bf10bfd-2bc5-489e-b8ee-6a9d9e045658)

![IMG_20240919_091315](https://github.com/user-attachments/assets/c699bc1b-6597-4a96-af67-656fe84d10a5)

je kan het niet opslaan heel lastig
Gaat niet met een Android tv box
- Device: [e.g. Pixel 4a]
- Android Version: [e.g. Android 13]
- App Version [e.g. 3.3.3]

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! I've change it so this will now allow save on android tv when you click "enter" on keyboard. Clicking the save button not needed.

**Comment by tomtomclub** [comment]
Thanks i will test it

**Comment by tomtomclub** [comment]
Which wg is the last night version?
