### ISSUE TITLE
AndroidTV suggestions

### ISSUE THREAD

**Issue by zilexa** [zaneschepke/wgtunnel#36]
1. Would be great if we could include/exclude apps just like with the regular version.
2. On AndroidTV 10 I can barely see what button I am on. Navigation is also slightly awkward (not sure what is highlighted when you open the app and not sure how to get to the imported tunnel).
3. With the official Wireguard app, I can hit the OK button on my remote twice to activate the tunnel: once to open the app, second time to start the tunnel. No need to navigate to the tunnel or to the start button. Would highly prefer this flow!
4. Option to ensure the tunnel is always on.
5. A TV is a static device, no need to scan for WiFi SSID name. 
6. Additionally, I can't even see Settings, because the warning that location permission is required is persistent even after I have given the app all 3 permissions that are listed in the App details. 

1-4 would really be great if this can be done. That way you distinguish yourself from the official app which is only an on/off button.

**Comment by zaneschepke** [comment]
1. This is possible. When you are hovering over a tunnel, you click once to access action buttons for that tunnel. You can navigate within the tunnel actions over to the edit button to make these changes. 
2. Yes, the navigation for TV is not ideal. It is very clunky. The reason for that is that I never intended for this app to be an AndroidTV app. Everything added to make this app work on AndroidTV has been completely retrofitted. I'll do my best to fix issues with the navigation, but there are aspects of it that cannot be fixed without a rewrite. 
3. I'll see what I can do to make a more intuitive flow for a quick toggle. 
4. Can you elaborate? I don't understand this request. 
5. You would be surprised. There are some users who use auto tunneling with their "TV" device being a travel device like a Nvidia Shield. 
6. I am unable to replicate this behavior on my Chromecast Android 12. I'll have to try to emulate it on an AndroidTV 10 device. I am currently working on a rewrite of the settings screen where it will be accessible without permission.

**Comment by tonyhardcode** [comment]
I agree with #2. WG Tunnel is a great app in function but design and navigation on the AndroidTV could use some polish.

**Comment by zaneschepke** [comment]
> I agree with #2. WG Tunnel is a great app in function but design and navigation on the AndroidTV could use some polish.

Definitely. I'm currently working on a pretty significant UI update. I'm hoping it will help fix some of the AndroidTV user experience issues.

**Comment by tonyhardcode** [comment]
The UI improvements on 3.1.0 are a welcome change! I would like to add one more suggestion. When navigating on the individual tunnel settings and general app settings the onscreen keyboard always pops up when an input box is highlighted. Could you have it come up on when the remote ok button is pressed?

**Comment by zaneschepke** [comment]
> The UI improvements on 3.1.0 are a welcome change! I would like to add one more suggestion. When navigating on the individual tunnel settings and general app settings the onscreen keyboard always pops up when an input box is highlighted. Could you have it come up on when the remote ok button is pressed?

Yes! The current behavior of the textfields is not ideal. I'll work on a fix.

**Comment by zaneschepke** [comment]
I've added number 3 and @tonyhardcode I've made it so you can navigate the textboxes without the keyboard opening in release 3.1.1. I closed this issue as I feel I have completed most of the major requests of this issue. Feel free to open a new issue if you notice something I have missed. Please try to limit the amount of requests per issue. This will better help me keep track of them so I can complete them.
