### ISSUE TITLE
[FEATURE] - Adding a delay timer/disconnect on active Bluetooth connection.

### ISSUE THREAD

**Issue by abhi08638** [zaneschepke/wgtunnel#360]
**Is your feature request related to a problem? Please describe.**
Wireless Android Auto does not work with a VPN active and it requires a Bluetooth connection before it connects to the wifi direct network. Unfortunately, the tunnel connects before the wifi network connects so android auto does not work.

**Describe the solution you'd like**
I believe a delay timer would solve this if I were able to connect to the AA wifi network in time. 

**Describe alternatives you've considered**
Alternatively, not turning on the tunnel if a specific Bluetooth device is connected would also work. 

**Additional context**
N/A

**Comment by zaneschepke** [comment]
Hello! Configuring split tunneling on your tunnel config is the best way around this issue. Please see the [faq](https://zaneschepke.com/wgtunnel-docs/faq.html#does-product-work-with-android-auto) for more information. Let me know if you have any issues, but this should solve your problem.

**Comment by abhi08638** [comment]
I just found the option and it worked great, this is not needed, thanks!
