### ISSUE TITLE
[BUG] 3.5.2  Falls after normal reboot and more 

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#361]
**Describe the bug**
Unfortunately this doesn't really work well 3.5.2. It no longer comes in if the power of the TV box is off for 10 minutes I have  Even a normal reboot stay offline 
Sent some pic to see the config
![IMG-20240923-WA0009](https://github.com/user-attachments/assets/fdcc77a2-d635-4062-aab7-47a8fc0c17a4)
![IMG-20240923-WA0007](https://github.com/user-attachments/assets/e6586f3c-2b73-4a21-9583-5a3915ba6350)
![IMG-20240923-WA0005](https://github.com/user-attachments/assets/a44049b5-d15f-407b-8bda-3031e7a1454c)
![IMG-20240923-WA0003](https://github.com/user-attachments/assets/417de3da-4add-45a6-8dc9-01dfddab7b02)
![IMG-20240923-WA0000](https://github.com/user-attachments/assets/610543b8-dadd-4fb8-aa47-ea269df9e163)

People ip is fake im not completely crazy lol

**Smartphone (please complete the following information):**

- Device: [e.g. Pixel 4a]
- Android Version: [e.g. Android 11
- App Version 3.5.2

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Thank for these details! I'll look into this.

**Comment by zaneschepke** [comment]
I think this has since been fixed. Marking as closed. Let me know if it still persists and we can reopen.
