### ISSUE TITLE
[BUG] - Search domains disappear from DNS setting of WireGuard tunnel

### ISSUE THREAD

**Issue by dsh2dsh** [zaneschepke/wgtunnel#362]
**Describe the bug**
Search domains added to the DNS setting are not restored when editing the config, thus are lost on next save unless entered again each time.

**Smartphone (please complete the following information):**

- Device: Samsung S21
- Android Version: Android 14
- App Version: 3.5.2

**To Reproduce**

1. Go to the tunnel config editor.
2. Add a search domain to the DNS input, e.g. 10.5.5.1 -> 10.5.5.1, mydomain.example, so that queries for machine are first qualified to machine.mydomain.example.
3. Save the config.
4. Open the same tunnel's config.

**Expected behavior**
 The input should contain the search domain but only has the DNS server IP(s).

**Additional context**
This is a copy-paste of #233, because I can't add my comment there, but I've got the same problem using latest release.

**Comment by zaneschepke** [comment]
Hello! Thank you for the report. I'll look into a fix for this!
