### ISSUE TITLE
[BUG] - Disabling app shortcuts does not remove the shortcuts

### ISSUE THREAD

**Issue by stephan-loescher** [zaneschepke/wgtunnel#365]
**Describe the bug**
Thanks for providing this cool app!
When I activate and later deactivate the "Enable app shortcuts", they are still visible and usable.
Can you please remove the static shortcuts, if the setting "enabled_app_shortcuts" is deactivated?

**Smartphone (please complete the following information):**
- Device: Fairphone 5
- Android Version: 14
- App Version 3.5.2

**To Reproduce**
1. Enable app shortcuts
2. Disable app shortcuts
3. shortcuts are still visible and usable

**Expected behavior**
No shortcuts visible if "Enable app shortcuts" is off.

**Comment by zaneschepke** [comment]
Hello! Yeah, that sounds like a good idea. I'll look into this.

**Comment by stephan-loescher** [comment]
Sorry, but it seems that the issue is not fixed.
The app shortcuts are still visible in version 3.6.5.

**Comment by zaneschepke** [comment]
Hmm, I am unable to replicate this. When I turn off shortcuts they disappear.

**Comment by stephan-loescher** [comment]
You think, I should deinstall WG Tunnel and install it again?

**Comment by stephan-loescher** [comment]
I tried a fresh install: Deinstalled WG Tunnel, installed WG Tunnel and the shortcuts are visible again.
