### ISSUE TITLE
[FEATURE] - Android TV or Google TV application

### ISSUE THREAD

**Issue by AbcITAndrzej** [zaneschepke/wgtunnel#367]
Is there a chance that there will be a version compatible with Android TV? It would be mega useful :-)

**Comment by devastgh** [comment]
The app works on android tv. The UI is not really great for that, but it mostly works. Once it's set up, you probably won't use the UI anyway.

**Comment by AbcITAndrzej** [comment]
Thanks for the info.
I'll check and let you know :-)
I'm mainly interested in the option to select the applications for which the tunnel should work.

**Comment by devastgh** [comment]
> Thanks for the info. I'll check and let you know :-) I'm mainly interested in the option to select the applications for which the tunnel should work.

That function absolutely works on my android tv devices, the complexity is getting there and setting it up with the UI :)

**Comment by zaneschepke** [comment]
Eventually I could build a dedicated UI for AndroidTV, but this would be a pretty major chunk of effort. For now, I'm just trying to improve the current UI's experience on AndroidTV.

**Comment by figarospares** [comment]
Yes I second that Amazon Tv better UI as it is a bit hard to navigate around the menus and also once connected to display upload and download data would be good add on.

**Comment by zaneschepke** [comment]
> Yes I second that Amazon Tv better UI as it is a bit hard to navigate around the menus and also once connected to display upload and download data would be good add on.

I stopped supporting Amazon TV's a while back because their ecosystem and processes made it almost impossible to support. Out of curiosity, does side loading the app on Amazon TV still work? Also, if you click the "Info" icon button on the tunnel on Android TV it should show this information.

**Comment by zaneschepke** [comment]
I'll mark this one as closed for now as the app is mostly usable on AndroidTV. I'll continue to keep trying to make the experience better on AndroidTV until I get the time to create a dedicated AndroidTV UI in the future.

**Comment by devastgh** [comment]
> > Yes I second that Amazon Tv better UI as it is a bit hard to navigate around the menus and also once connected to display upload and download data would be good add on.
> 
> I stopped supporting Amazon TV's a while back because their ecosystem and processes made it almost impossible to support. Out of curiosity, does side loading the app on Amazon TV still work? Also, if you click the "Info" icon button on the tunnel on Android TV it should show this information.

The apk sideloaded work properly on my 2nd gen fire stick 4k max.
