### ISSUE TITLE
Version 3.0.2 Fdroid constantly crashes 3.0.0 does not. 

### ISSUE THREAD

**Issue by PDXUser** [zaneschepke/wgtunnel#37]
Version 3.0.2 crashes when opening.   
Version 3.0.0 does not crash when opening (From F-Droid's Repo) 

I tried the Google Play version which is 3.0.3 and it works fine without issue.  I'd rather stick with F-Droid. :) 

I'm using the Neo Store as my preferred F-Droid app and it doesn't show the latest 3.0.3 for F-Droid so I'm not sure if it's been pushed through or not.  

Using Samsung Galaxy A13 5G variant on AT&T if this helps any.

**Comment by zaneschepke** [comment]
Hello! Thank you for notifying me of this issue! I will investigate right away. Unfortunately, F-Droid can take up to one week for a new version to make it into the store whereas Google Play is much faster. F-Droid auto updates the version of the app based on github release tags, but this can still take one week from the time the changes are pushed to github to the time the app is live in F-Droid. Version 3.0.3 should be live in F-Droid soon.

**Comment by zaneschepke** [comment]
> Version 3.0.2 crashes when opening. Version 3.0.0 does not crash when opening (From F-Droid's Repo)
> 
> I tried the Google Play version which is 3.0.3 and it works fine without issue. I'd rather stick with F-Droid. :)
> 
> I'm using the Neo Store as my preferred F-Droid app and it doesn't show the latest 3.0.3 for F-Droid so I'm not sure if it's been pushed through or not.
> 
> Using Samsung Galaxy A13 5G variant on AT&T if this helps any.

Did you try a clean install of 3.0.2 the app with all of the data removed? There is minor database issue with the release of 3.0.0 that was resolved in the subsequent releases. I am wondering if some of the data in the DB was perhaps corrupted and is causing the crash. There are only very minor differences between 3.0.2 and 3.0.3 which are mostly focused on AndroidTV improvements. This could also explain why switching to the Google Play version fixed the issue.

**Comment by PDXUser** [comment]
I did, yeah, after it crashed immediately after launching, Samsung got in the way and said something about defective code and recommended clearing data and cache/reinstall.  (Their default behavior when an app seems to fail after a few attempts in a row).   I fully removed the app after clearing the cache, letting the phone sit for a weekend with out the install of the app and it did the same thing.

**Comment by zaneschepke** [comment]
> I did, yeah, after it crashed immediately after launching, Samsung got in the way and said something about defective code and recommended clearing data and cache/reinstall. (Their default behavior when an app seems to fail after a few attempts in a row). I fully removed the app after clearing the cache, letting the phone sit for a weekend with out the install of the app and it did the same thing.

Thank you for the addtional detail. Can you also tell me the version of Android you are running?

**Comment by PDXUser** [comment]
Android 13 - Samsung's One UI 5.1 
I have heard that Samsung doesn't play nicely with some apps and I wonder if this may be partially it. (Their issues usually affect uninstalls of apps).

**Comment by zaneschepke** [comment]
> Android 13 - Samsung's One UI 5.1 I have heard that Samsung doesn't play nicely with some apps and I wonder if this may be partially it. (Their issues usually affect uninstalls of apps).

I think Samsung did not fully clear the storage. I was able to replicate the crash on my phone with the following steps (Pixel 4a Android 13):

1. Install 3.0.0
2. Add tunnel
3. Configure settings
4. Add trusted ssids
5. turn on auto tunneling
6. turn off auto tunneling
7. update app to 3.0.2
8. crash

I was able to fix the issues by going into app settings, clearing storage manually for WG tunnel, uninstalling and then installing 3.0.2 directly from F-Droid.

**Comment by PDXUser** [comment]
I tried this and get the same thing:

![image](https://github.com/zaneschepke/wgtunnel/assets/20736534/9ad2832f-4f14-45a8-8da7-58cdab99d37b)

Not that the issue would be with the store of my choice, but I tested with F-Droid's official app:
![image](https://github.com/zaneschepke/wgtunnel/assets/20736534/6f77fb5e-d437-4590-8571-8145ac739557)

**Comment by PDXUser** [comment]
HEY!  I got it to work by clearing data - but moving it to SDCARD storage (I have an external card installed).  It works without issue there.   So I wonder now if Samsung isn't really clearing the data even if told to do so!

**Comment by zaneschepke** [comment]
> HEY! I got it to work by clearing data - but moving it to SDCARD storage (I have an external card installed). It works without issue there. So I wonder now if Samsung isn't really clearing the data even if told to do so!

Great! Yeah, I think they are only clearing application cache and not application storage. It makes sense because they don't want the user to lose data. In this case we need the data to be lost :D

**Comment by PDXUser** [comment]
Since this is resolved by installing to SDCARD storage thus forcing new DB to be placed elsewhere and Samsung's apparent  issues, there's no real need to keep this open.
