### ISSUE TITLE
[FEATURE] - Non-dismissable persistent notification

### ISSUE THREAD

**Issue by gabriel20xx** [zaneschepke/wgtunnel#372]
**Is your feature request related to a problem? Please describe.**
On some roms it happens, that the background service that is intended to track the auto-tunneling state gets unresponsive or gets killed by the os even though the app is set to use unrestricted battery. For myself, I have the problem, that if I switch the wifi network from trusted to untrusted or to mobile data or vice versa it doesn't automatically and/or instantly toggle the vpn as it should with auto-tunneling enabled.

**Describe the solution you'd like**
I would think a possible solution would be to create a persistent, non-dismissable notification when auto-tunneling is enabled. This notification makes sure, that the background service, that is responsible for toggling the vpn on auto-tunneling does not get killed and is always listening to network changes.

**Describe alternatives you've considered**
I don't have any good alternatives.

**Additional context**

**Comment by aqsede** [comment]
Please make an option also for current implementation which don't have it.
