### ISSUE TITLE
[BUG] - Google Streamer Freezing

### ISSUE THREAD

**Issue by nitra17** [zaneschepke/wgtunnel#376]
On the new Google streamer, when trying to upload the configuration with any file explorer, the app completely freezes and need to reboot the streamer to make it work again after. Can not get passed uploading the file.
Works on fine on my previous google tv(android 12) but does not work on the new Google streamer(android 14)

- Device: Google Streamer
- Android Version: Android 14

**Comment by zaneschepke** [comment]
Thank you for the report. I am looking into this.
