### ISSUE TITLE
[FEATURE] - add bluetooth trusted list

### ISSUE THREAD

**Issue by warenbe** [zaneschepke/wgtunnel#377]
When using my car, android auto fails to start because of the vpn.
Editing the allow IP list of the vpn does not help.
The only solution is to disconnect the autovpn.

*Is it possible to track Bluetooth connection, so we can add the Bluetooth connection in the settings to trigger a tunnel disconnection?

**Comment by genomez** [comment]
I originally had the issue with Android Auto  as well. I added Android Auto (and Maps) to my exclude list and it works well. Everything else goes through my tunnel, except those two apps. I hope this helps.

**Comment by warenbe** [comment]
I might be dumb, then. where do you find these exclusions ?
i tried to add the wifi connection of the car without success.

**Comment by warenbe** [comment]
sorry, i check the manual too quickly... found the settings.
