### ISSUE TITLE
[BUG] - Auto-tunnel kills email app

### ISSUE THREAD

**Issue by R7010A** [zaneschepke/wgtunnel#384]
**Describe the bug**
Using auto-tunnel kills the email app.
I checked it with 2 open source mail clients (FairEmail and K9 / Thunderbird-mail).
Turning wifi off starts vpn as expected, email receipt works, turning wifi on stopps vpn, but also interrupts (FairEmail) or kills (K-9 mail) the mail clients. Additional info: I defined my home wifi network as trusted.
I set both email-clients for testing as exceptions, the result is the same.
Disabling auto-tunnel and using "normal" vpn (not always-on-vpn) works fine.

The developer of FairEmail checked the log file and said that (auto-tunnel) vpn kills the connection to the mail-servers.

Weird. 

**Smartphone (please complete the following information):**

- Device: OnePlus Nord 3 5G
- Android Version: A14
- App Version 3.5.2

**To Reproduce**
See bug description

**Expected behavior**
auto-tunnel shouldn't kill / interrupt email receipt

**Comment by zaneschepke** [comment]
Thanks for the report! I'll look into this.

**Comment by zaneschepke** [comment]
I also use FairMail so I tried this out myself. So auto tunnel is really not doing anything that special. It is simply toggling the tunnel the same way a user would toggle on tunnel on or off. If FairMail has a persistent connection, any VPN/tunnel connection will break that connection because of the network changes. From by brief testing, it seems like the FairMail connection is interrupted, but then it recovers. Is that what you are seeing?

**Comment by R7010A** [comment]
Hello Zane, 
FairEmail now behaves exactly as you described. After a short period of time when switching from WiFi to mobile data (vpn) and vice versa, the connection is established. However, the prerequisite is that a permanent vpn connection is deactivated in   >settings>connections. 
By the way, I noticed that since version 3.6.5 the tunnel-control-toggle no longer works. When switching from WiFi to vpn or vice versa, the tunnel control toggle always remains on. 

Regards

**Comment by zaneschepke** [comment]
This seems like the correct behavior so I'll mark this as closed. Let me know if you have further problems and we can reopen. 

As for the tile issue, I'm working on a fix for this. There is currently #491 open for this issue.
