### ISSUE TITLE
[FEATURE] - Using Tunnel split to connect two vpns at the same time

### ISSUE THREAD

**Issue by user12257** [zaneschepke/wgtunnel#393]
I am not sure if it is possible, but I would like to be able to use my VPN provider to not leak my IP when surfing or using certain apps, while at the same time, I need some apps, like home assistant to be in my home VPN. 

At home, I can use the split tunnel function, to give home assistant for example access to my local dns etc, while other apps use my vpn provider. But when on the road, I need to switch back and forth, or use different user profiles.

**Comment by zaneschepke** [comment]
Hello! Although there are technically possible ways to accomplish this, Android natively only supports one tunnel at a time without root. This would be a distant future type of feature that I'm not presently sure if I want to try and tackle in this app. 

That being said, there is a simple way to accomplish what you want. I recommend getting a home router that has both a VPN server and VPN client built in. This way you can always just connect to your personal VPN server at home when you're out, and then your router handle routing to either to your self hosted services or route your internet traffic through the configured vpn client on the router. 

I'll mark this one as closed for now, but feel free to comment back and we can chat further through possible solutions.
