### ISSUE TITLE
Feature Request: intents for zero-touch configuration

### ISSUE THREAD

**Issue by mrbluecoat** [zaneschepke/wgtunnel#4]
Nice app!

Would it be possible to add Android intents to allow for zero-touch configuration, such as with Tasker or an MDM? For example, https://github.com/tailscale/tailscale/issues/3547

Alternatively, have it check for a *.conf file on the device at a specific location to automatically configure the WG tunnel and tunnel all applications

**Comment by mrbluecoat** [comment]
Perhaps it's already supported as an undocumented option? https://github.com/zaneschepke/wgtunnel/blob/main/app/src/main/java/com/zaneschepke/wireguardautotunnel/ui/MainActivity.kt#L79

**Comment by zaneschepke** [comment]
Hello! Thank you for showing interest in the app. So that line you highlighted is actually what launches the VPN app permission when you first install the app if it has not already been accepted. Is the feature you are requesting the ability to control turning the VPN on and off via intents from other applications similar to the wireguard official android app with the check box option it has in the advanced settings?

**Comment by mrbluecoat** [comment]
Correct, I need to configure a fleet of Android devices for VPN and would like to use the WireGuard protocol. Due to the number of devices our IT department needs to automate the configuration, enabling, and enforcement of VPN use without touching each device physically. We use Cisco Meraki which can install apps from the play store and send intent commands to that app.

**Comment by zaneschepke** [comment]
Okay, I understand the scope of the features now. Thank you for the context. Although there are aspects of what you are asking for that some everyday consumers of the app could find useful, I think these features fall more into the category of enterprise level features. With that in mind, I think they are beyond the scope of this project. However, if there is an appetite for it, I could make an enterprise version of this app that would include these features and others like it geared more toward remote configuration and management. The official wireguard mobile app only allows you to toggle a tunnel on or off via intent. It does not allow for remote tunnel config management, force tunneling, etc. Would you be interested in this?

**Comment by mrbluecoat** [comment]
Currently we're using the IKEv2 protocol since it's native on all platforms we need. WireGuard would be nice for speed improvement but not critical at the moment so I'll leave this open as a nice-to-have.

**Comment by mrbluecoat** [comment]
P.S. Instead of Intents, it would probably be easier to just add Managed Configurations: https://developer.android.com/work/managed-configurations

**Comment by zaneschepke** [comment]
I am going to mark this one as closed, as it falls outside the goals of this app. This feature is directed toward enterprise management, but this app's goal is to serve community users (not commercial). That being said, this app is MIT licensed. Any corporation could fork this project and adjust the features to fit their purposes. 

Also, I am open to being approached by a corporation to complete this work if there is an interest.
