### ISSUE TITLE
[Question/FEATURE] - Option to only allow DNS traffic when connecting from some WIFI 

### ISSUE THREAD

**Issue by merlinuwe** [zaneschepke/wgtunnel#404]
I'm in a wifi network at work with a fast internet connection. If I use wg tunnel, the bandwidth is limited by my private internet provider. Would it be an advantage to optionally route only DNS traffic over the vpn? So one could use the broad bandwidth of the connected wifi network and the privacy (I have pi-hole at home) of the own network.

**Comment by zaneschepke** [comment]
Hello! This is technically possible, but it is not supported out of the box on Android and would require some low level changes to make something work. 

In the immediate, I would recommend configuring [private dns](https://mullvad.net/en/help/dns-over-https-and-dns-over-tls#android) to accomplish this and use either mullvad's (or another trusted party's) DNS servers or self host your own.

**Comment by bobpaul** [comment]
Wouldn't you simply do:

```
[Interface]
Address = 192.168.16.100/32
DNS = 192.168.16.1
PrivateKey = server key

[Peer]
PublicKey = client pub
PresharedKey = its shared
AllowedIPs =  192.168.16.1/32
Endpoint = wireguard.server.example:58224
PersistentKeepalive = 25
```
where 192.168.16.1 is the PiHole (and probably also the wireguard peer)?

**Comment by merlinuwe** [comment]
Sounds interesting, but I don't understand it completely. My router has the IP address 192.168.178.1

My pihole has 192.168.178.100

WG tunnel is installed on my android smartphone.

Where do I have to add which settings? Can you help me, please?

**Comment by bobpaul** [comment]
@merlinuwe 
On your phone, copy an existing wireguard tunnel that you're able to use to access your PiHole. (Long press to get the copy option).

Test the duplicate entry and make sure it works. Then disconnect.

Edit that entry. 
- Rename the tunnel to `PiHole DNS` (or similar)
- in the interface section, set DNS to `192.168.178.100`.
- in the peer section, set Allowed IPs to `192.168.178.100/32`
Save

**Explanation**
The "Allowed IPs" entry for a peer is the list of IP addresses and subnets that are reachable via a peer. Commonly that's set to `0.0.0.0/0, ::/0` which means "all IPv4 and all IPv6 addresses". Your phone will try to send all traffic (for included apps) through that tunnel. By setting it to `192.168.178.100/32` then your phone will ONLY use that tunnel to access your DNS server and all other traffic will take other routes.

**Comment by merlinuwe** [comment]
Thank you very much for your explanation, the new connection works. ;-)

I think I now have the advantage to profit from the faster wifi at work (~1000 Mbit/s) compared to my home DSL (50: 63 Mbit/s receive, 23 Mbis/s send). 

This should also result in lower latency (or do the latencies add?) and less battery consumption on the smartphone.  

Is there a way to use this new connection _only_ when I'm connected to the Wifi at work?

**Comment by bobpaul** [comment]
When you edited the tunnel configuration, you stepped through a screen that allows entering the names of Wi-Fi SSIDs. 

Configuring Auto-Tunneling on a specific tunnel takes precedence over other Auto-Tunneling you have configured.

See [Auto-tunneling to a specific tunnel by wifi name and/or mobile data﻿](https://zaneschepke.com/wgtunnel-docs/features.html#auto-tunneling-to-a-specific-tunnel-by-wifi-name-and-or-mobile-data)

**Comment by zaneschepke** [comment]
It seems this one was resolved. I'll mark as closed for now. Thank you @bobpaul!

**Comment by Lycidias93** [comment]
> @merlinuwe On your phone, copy an existing wireguard tunnel that you're able to use to access your PiHole. (Long press to get the copy option).
> 
> Test the duplicate entry and make sure it works. Then disconnect.
> 
> Edit that entry.
> 
> * Rename the tunnel to `PiHole DNS` (or similar)
> * in the interface section, set DNS to `192.168.178.100`.
> * in the peer section, set Allowed IPs to `192.168.178.100/32`
>   Save
> 
> **Explanation** The "Allowed IPs" entry for a peer is the list of IP addresses and subnets that are reachable via a peer. Commonly that's set to `0.0.0.0/0, ::/0` which means "all IPv4 and all IPv6 addresses". Your phone will try to send all traffic (for included apps) through that tunnel. By setting it to `192.168.178.100/32` then your phone will ONLY use that tunnel to access your DNS server and all other traffic will take other routes.

This works like a charm, thanks!

Would be nice, if we could have a on/off switch for "only tunnel DNS traffic" @zaneschepke

**Comment by merlinuwe** [comment]
I totally agree, THIS would be VERY helpful.
