### ISSUE TITLE
[BUG] - 3.5.4 asks for root on LOS21 ?

### ISSUE THREAD

**Issue by vsatmydynipnet** [zaneschepke/wgtunnel#406]
3.5.4 asks for root on LOS21 ?

**Comment by vsatmydynipnet** [comment]
Typo

**Comment by vsatmydynipnet** [comment]
User the apk from the release page here

**Comment by zaneschepke** [comment]
Hello! This should be fixed on 3.6.0. Let me know if it persists and I can reopen.

I'll mark as closed for now.
