### ISSUE TITLE
[BUG] App crashes when activating "Start auto-tunnels" under Android 12 (version 3.5.3)

### ISSUE THREAD

**Issue by Krabtus** [zaneschepke/wgtunnel#407]
**Error description**
In version 3.5.3 of the WG Tunnel app on Android 12, the app crashes when the "Start auto-tunneling" function is activated in the settings. The crash occurs immediately after activating the option. 

**Smartphone:**
- Device: Samsung Galaxy S20
- Android version: Android 12
- App version: 3.5.3

**Reproduction steps Steps to reproduce the behavior:**
1. Open the WG Tunnel app. 
2. Go to Settings. 
3. Activate the “Start auto-tunneling” function. 
4. The app crashes immediately.

**Expected behavior**
The app should continue to remain stable and function correctly after enabling the Start Auto Tunneling feature. Additional context The problem only occurs when the mentioned function is activated. Otherwise the app works normally.

**Comment by Checkit53** [comment]
I also have the same bug in the current version (3.5.4) under Android 14.
It worked fine in older versions.

**Comment by zaneschepke** [comment]
This should be fixed in 3.6.0. 

Marking as closed for now.
