### ISSUE TITLE
[BUG] - Configuration values take several seconds to appear when editing tunnel

### ISSUE THREAD

**Issue by bobpaul** [zaneschepke/wgtunnel#409]
**Describe the bug**
When editing a tunnel, the page loads with empty input fields and it sometimes takes 10 seconds before values populate in the fields. It seems to be worse on a tunnel that's freshly imported and hasn't previously been edited.

**Smartphone (please complete the following information):**

- Device: Samsung S10e
- Android Version: Android 12
- App Version 3.5.2
- Backend: Userspace

**To Reproduce**

1. Clear app data in WG Tunnel
2. Export zip of tunnels from official Wireguard app and import into WG Tunnel
2. In WG Tunnel Long Press a tunnel so the settings cog appears
3. Click the cog.
4. Click the edit pencil
5. Observe an empty form for "Interface" settings appears. Start counting.

If you skip steps 1 & 2, it still takes a long time at step 6, but it's usually more like 1-2 seconds instead of 10-12 seconds.

**Expected behavior**
I would expect the form to already be populated as soon as it shows up.

**Comment by merlinuwe** [comment]
There is always a time lag to load the data of 5 sec. when switching to edit mode.

Android 11, 3.5.4 nightly, usermode

**Comment by zaneschepke** [comment]
Hello! This should be fixed by #495 and will be in the next release 3.6.4. I'll mark this as closed for now.
