### ISSUE TITLE
[BUG] - When Copying an existing tunnel, Amnetzia properties are not copied.

### ISSUE THREAD

**Issue by bobpaul** [zaneschepke/wgtunnel#413]
**Describe the bug**
Amnezia Properties are not copied when using the copy button to duplicate a tunnel.

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S10e
- Android Version: Android 12
- App Version 3.5.2
- Backend: Userspace

**To Reproduce**

1. Configure a tunnel with custom "Amnezia Properties"
2. From the tunnel screen, long press the tunnel and click the Copy button.
3. Edit the newly created tunnel. Wait for the interface properties to populate.
4. Click "Show Amnezia Properties". 
5. Notice all of the Amnezia properites are all blank (set to default) while the standard Wireguard options were all copied to the new tunnel.

**Expected behavior**
All everything that was configured in the original tunnel should be copied to the new tunnel.

**Comment by dkoppenh** [comment]
This was fixed in 3.5.4, along with automatically showing the Amnezia properties if they exist.

**Comment by bobpaul** [comment]
Confirmed fixed.
