### ISSUE TITLE
[BUG] - Quick Settings Tiles cannot be dragged from the inactive group and added to the active group

### ISSUE THREAD

**Issue by uwuMocha** [zaneschepke/wgtunnel#415]
**Describe the bug**

When I drag the notification tray down and edit quick settings tiles, I try to drag the WG Tunnel related tiles from the bottom in the group of inactive tiles, towards the top, to drop it in with the active tiles. This happens with both the Tunnel control and Auto-tunnel quick settings tiles. While holding a WG Tunnel tile and attempting to drag it to the top and drop it in the active tile group, the screen will scroll up until the original position of the tile being dragged goes off screen. At that point, the "dragging" state of that tile is lost and the tile returns to its original position among the other inactive tiles.

Tiles for other apps do not exhibit this behavior, they behave as expected and allow me to drag them as far up as necessary to add them to the active group. I've been experiencing this bug for as long as I've been using the app, which has been at least since the previously released version, but it is still present on 3.5.3 as well. I've tried restarting my phone, removing and reinstalling the app, but those do not resolve the issue. 

I figure it might be possible to disable a bunch of apps and system apps on my phone that appear higher up the list so that the wgtunnel tiles will appear at the top of the inactive tile grouping, within one screen length of the active tiles group to circumvent this bug, but I haven't taken the time to try that.

**Smartphone (please complete the following information):**

- Device: Pixel 4
- Android Version: Android 13
- App Version 3.5.3
- Backend: Userspace I think?

**To Reproduce**

1. Drag notification tray down twice, to reveal the quick settings tile edit pencil icon
2. Click on the quick settings tile edit pencil icon
3. Scroll down to the Tunnel control and Auto-tunnel WG Tunnel tiles. _To reproduce this behavior, the wg tunnel quick settings tiles must be over one screen length down from the top row of the inactive tiles grouping. For a pixel 4 this means that they need to be at least the 9th row down of tiles in the inactive grouping. For me, both wg tunnel tiles are in the 20th row down._
4. Long press the Tunnel control or Auto-Tunnel tile and drag it to the top of the screen.
5. Continue holding the tile at the top of the screen while the screen scrolls up.
6. Once the original position of the dragged tile goes off screen, scrolling will stop, you will no longer be holding the tile, and the tile can be found in the original position that you grabbed it from.

**Expected behavior**

In step 6 above, the screen should continue to scroll up until the top of the list of quick settings tiles has been reached.

**Comment by zaneschepke** [comment]
Hello! This is a very strange issue indeed. I'll try to reproduce.

**Comment by zaneschepke** [comment]
Any luck with this one? I made some changes that could have potentially helped in 3.6.3.

**Comment by uwuMocha** [comment]
Yes, actually! I'm now running 3.6.3 from the fdroid store, and the quick settings tile issue now appears to be resolved on my device! Thank you!

**Comment by zaneschepke** [comment]
Np! Thanks for letting me know!
