### ISSUE TITLE
Error saving tunnel after edit with whitespaces

### ISSUE THREAD

**Issue by zilexa** [zaneschepke/wgtunnel#42]
When I try to switch from "tunnel all apps" to "include", then select Netflix, then hit Save, I get the following error:

`Error: unknown error occured`

Also, the save button is always coloured, as if it has the focus.
When I actually move to the save button, it becomes grey. When I select it to save changes, I get the error above. 
This makes it impossible to actually switch from All to include/exclude.

**Comment by zaneschepke** [comment]
Hello!  Can you tell me the app version and device you are on?

**Comment by zilexa** [comment]
Chromecast for GoogleTV 4K. 
App version: 3.1.1

**Comment by zaneschepke** [comment]
> Chromecast for GoogleTV 4K. App version: 3.1.1

Perfect! I have same model. I tested this behavior on my TV and was only able to reproduce by adding in a whitespace to the fields I listed above. I'll prioritize a fix for this issue.

**Comment by zilexa** [comment]
Aha!
I use https://github.com/ngoduykhanh/wireguard-ui to manage my home VPN server. It's a nice, intuitive UI to create clients. The conf files are then generated. Probably it includes the whitespace somewhere.

**Comment by zaneschepke** [comment]
> Aha! I use https://github.com/ngoduykhanh/wireguard-ui to manage my home VPN server. It's a nice, intuitive UI to create clients. The conf files are then generated. Probably it includes the whitespace somewhere.

Yeah, it seems like a lot of tools do this.
