### ISSUE TITLE
[BUG] - Dark theme with light themed navigation bar and status bar

### ISSUE THREAD

**Issue by CaKrome** [zaneschepke/wgtunnel#420]
**Describe the bug**
App show dark theme with light themed navigation bar and status bar, resulting in unreadable status bar. Android is using light theme.

**Smartphone (please complete the following information):**

- Device: OnePlus 6T
- Android Version: Android 11
- App Version 3.5.4
- Backend: Userspace

**To Reproduce**
1. use a light themed Android
2. open app

**Expected behavior**

Either show light mode to match my Android theme or show a proper dark theme

**Screenshots (Only if necessary)**

![Screenshot_20241028-204444_WG_Tunnel](https://github.com/user-attachments/assets/9bbbabaa-fdc4-4fa3-b106-380f52d893e8)

**Comment by zaneschepke** [comment]
Hello! This should be fixed in the latest version 3.6.0. 

Let me know if you continue to have issues and we can reopen.

**Comment by CaKrome** [comment]
Now theme works nicely with version 3.6.0. Thanks so much for the fix!
