### ISSUE TITLE
[BUG] - Problem with app

### ISSUE THREAD

**Issue by tomtomclub** [zaneschepke/wgtunnel#421]
**Describe the bug**
Android tv 
De laaste twee kan je wel instaleren maar je kan niet meer de config fil toevoegen

**Smartphone (please complete the following information):**

- Device: [e.g. Pixel 4a]
- Android Version: [e.g. Android 13]
- App Version [e.g. 3.3.3]
- Backend: [e.g. Kernel, Userspace]

**To Reproduce**

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! I'm not sure I fully understand the problem and I also don't know what version of the app this issue appeared on. I'll mark as closed for now. Please feel free to recreate the issue with more details.

**Comment by tomtomclub** [comment]
You can close it no problem its fix now
