### ISSUE TITLE
[BUG] - Auto Tunnelling does not start at boot

### ISSUE THREAD

**Issue by Manuel06p** [zaneschepke/wgtunnel#426]
**Describe the bug**
I noticed that Auto-Tunnelling and the app in general won't automatically start at android's boot with only the restart on boot option enabled. After boot I needed to open the app and it would automatically start the auto tunnelling featuer. However, if before enabling auto tunnel, I also enable Allow Always ON VPN, and than I reenable the Auto Tunnelling, it does start at boot, even though I expected the feature to not do anything, since it is greyed out.

**Smartphone (please complete the following information):**

- Device: Xiaomi MiA3
- Android Version: Android 15 (Custom ROM)
- App Version: 3.5.4

**To Reproduce**

With AutoTunnelling on, restart on boot on and allow always on vpn off, it does not start at android's boot. But if allow always on vpn is on, it does start at boot.

**Expected behavior**
I expected the Allow Always ON Vpn toggle to not be relevant when AutoTunneling is in use, since it is greyed out, but appearently id does something during boot.

**Screenshots**
That way it doesn't start at boot
![Screenshot_20241031-132533_edited.jpg](https://github.com/user-attachments/assets/f6f02a89-7610-425e-a8c4-74ba309e78a8)

That way it does
![Screenshot_20241031-132523_edited.jpg](https://github.com/user-attachments/assets/a53d3dc0-a65a-4939-824a-763b3df84148)

**Additional context**
I run android 15 aosp, and the app have unrestricted access to background activity. In auto tunnelling I have enabled Tunnel on Trusted Wifi (Without GPS, but using root), Tunnel on Mobile Data and Restart on ping fail. I don't have the Use Kernel Module option enabled.

**Comment by Scorpoon** [comment]
I'm running version 3.6.0 on GrapheneOS (Android 15) and the tunnel starts as expected and I haven't noticed this behavior in earlier versions. Would it be possible for you to check if the problem still exists on 3.6.0?

**Comment by zaneschepke** [comment]
This feature is set to work only if the tunnel was active when the reboot occurred. If you had no active tunnels active when you rebooted, it won't start any tunnels. If you you have auto tunneling enabled, it will start auto tunneling service on boot. If this is not the expected behavior or if you want to to behave differently, we can definitely discuss it.

**Comment by zaneschepke** [comment]
Let me know if this is still an issue, but I'll mark this as resolved for now. We can always reopen.

**Comment by Manuel06p** [comment]
Hi, sorry if I haven't replied to you earlier, but appearantly I had some problems with notifications form github and I didn't see your answers. Today I went back to it to inform you that with the lastest updates I solved my issue. Sorry again for not having answered you before.
