### ISSUE TITLE
Add support for kernel module backend

### ISSUE THREAD

**Issue by pacjo** [zaneschepke/wgtunnel#43]
Official app has this functionality and it allows for better performance with lower battery drain. I believe the documentation is available in the android wire guard docs.

**Comment by zaneschepke** [comment]
I'll look into this!

**Comment by zaneschepke** [comment]
> Official app has this functionality and it allows for better performance with lower battery drain. I believe the documentation is available in the android wire guard docs.

Hello again! I am trying to work on this feature. I have a rooted Pixel 4a running Android 13 and the official app does not see kernel support for wireguard. Any pointers on how to get this working so I can have a test device to work on this feature?

**Comment by pacjo** [comment]
Do you have "Enable Kernel module backend" in wireguard settings? (3 dot menu, then expand "Advanced")

![Screenshot_20231209-163208_WireGuard](https://github.com/zaneschepke/wgtunnel/assets/56438628/2ede6a94-07f4-4d31-a845-04e211426112)

**Comment by zaneschepke** [comment]
I don't have that option. But I can confirm with the Root Checker app that my device is rooted.

**Comment by pacjo** [comment]
Hmm, what are you using for root? In magisk and kernelSU you need to allow superuser access on per app basis. Just checked and option won't show unless wireguard is given root access.

**Comment by zaneschepke** [comment]
> Hmm, what are you using for root? In magisk and kernelSU you need to allow superuser access on per app basis. Just checked and option won't show unless wireguard is given root access.

I'm using Magisk and I can't see a way to add Wireguard to the Superuser list of apps because WireGuard did not request it on install/open.

**Comment by pacjo** [comment]
Maybe it's a bug in wireguard itself, but it works for me. 

https://github.com/zaneschepke/wgtunnel/assets/56438628/31cfa1e1-aec8-446f-ad33-99df2ea6c70f

**Comment by zaneschepke** [comment]
Thank you for the video! Unfortunately, I don't get that option. I think I'll try a rooted emulator next. What version of Android are you using to do this?

**Comment by 2b** [comment]
It is worth mentioning that your kernel has to be compiled with the wireguard kernel module, you can verify that by the presence of `/sys/module/wireguard` directory.

**Comment by pacjo** [comment]
That's wierd.

> What version of Android are you using to do this?

crDroid 9.11 (A13)
November security patch.

I tested crDroid 10 (A14) last week and don't remember having issues.

One thing is that I'm using Neo Backup to restore whole APK along with it's data. On A13 I tried uninstalling and reinstalling, so here it works fine, but I can't confirm anything on A14.

**Comment by zaneschepke** [comment]
@pacjo @2b I was able to get the kernel module working with the official app on a rooted emulator. I can now begin the dev work. I'll keep you posted on the progress.  I will probably not support multi-tunnel feature to start. I hope that is not the main feature you are looking for.. :rofl:

**Comment by pacjo** [comment]
Tested and seems to be working. Thanks.

**Comment by zaneschepke** [comment]
> Tested and seems to be working. Thanks.

You're welcome :smile:  In the future, I will add the other kernel features that are available to the wireguard official app.
