### ISSUE TITLE
[question] - why does wg-tunnel need location permission to use auto-tunnel function

### ISSUE THREAD

**Issue by warioishere** [zaneschepke/wgtunnel#430]
Not a bug, just a question, as stated in the title: why does the app require location permission for auto-tunnel to work?
Wouldnt it be possible if the app can detect if connected to the listed network and then turn off wireguard connection?

I dont really understand why it needs the location permission to detect that we are connected with white listed networks.

Thanks for this project!! Love this app, much better then standard wireguard app,

writing an article on my blog about it, thatswhy also the questions

**Comment by ntova** [comment]
Because Android does consider the wifi name as sensitive location information. You can clearly derive location information from some wifi names. 

Here is the result of a quick search, hope this clarifies it even more: https://developer.android.com/develop/connectivity/wifi/wifi-permissions

**Comment by warioishere** [comment]
So this means, the location permission just allows the app to read the wifi name, not using gps at all, right?

> Because Android does consider the wifi name as sensitive location information. You can clearly derive location information from some wifi names.
> 
> Here is the result of a quick search, hope this clarifies it even more: https://developer.android.com/develop/connectivity/wifi/wifi-permissions

**Comment by ntova** [comment]
Yes. This is also why you do not need the location permission with rooted devices, where you can read the current wifi directly.
