### ISSUE TITLE
[FEATURE] Ability to add configuration from clipboard

### ISSUE THREAD

**Issue by Korb** [zaneschepke/wgtunnel#431]
**Is your feature request related to a problem? Please describe.**
I suggest adding the item `Paste from clipboard` in addition to the items `Add from file or zip`, `Add from QR code` and `Create from scratch`.

**Describe the solution you'd like**
This is useful in situations where configurations are distributed as keys like `ss://Y2hhY2hh` or `vgc://SCoQY`.

**Describe alternatives you've considered**
Save the received link to a file and specify it when importing using the `Add from file or zip` function?

**Comment by Korb** [comment]
> zaneschepke closed this as completed in 9bb3006 on Nov 23, 2024

Hmm, pasting the `vgc`-configuration key gives me the `Invalid tunnel config format` error message.

---
WG Tunnel 3.9.5 (39500) f-droid (Aug 21, 2025)
Model: Vivo T1 (4G) / V2153
OS version: Funtouch OS 14

**Comment by zaneschepke** [comment]
This should be fixed or at least give a more detailed message of what is going wrong with version 4.0.0. Please give that a try.

**Comment by Korb** [comment]
`wgtunnel-fdroid-release-4.0.3.apk`:

> Bad config. Unknown section at location: TOP_LEVEL.

I enabled `Local logging (Enable local logging)` and tried adding the key I sent you on 2025-09-24 in Telegram again, but `Read the logs` is empty. Apparently, the log isn't recording events for new configuration additions (or addition errors).
