### ISSUE TITLE
[Question] - Changes in the recent nightly build

### ISSUE THREAD

**Issue by merlinuwe** [zaneschepke/wgtunnel#432]
Can you please add some infos about your recent nightly build(s)? So we can test them?

**Comment by zaneschepke** [comment]
Thanks for this! Yeah, I'll look into changelog options to make it easier to tell what has changed.

**Comment by zaneschepke** [comment]
This is now added to the workflow. It might have some bugs, but seems to be working so far. I'll keep and eye on it, but marking as closed for now.

https://github.com/zaneschepke/wgtunnel/releases/tag/nightly
