### ISSUE TITLE
[BUG] - 3.6.0 cannot delete a node from ui

### ISSUE THREAD

**Issue by Septrum101** [zaneschepke/wgtunnel#435]
**Describe the bug**
Cannot deleted  node from ui.

**Smartphone (please complete the following information):**

- Device: vivo pad3
- Android Version: Android 13
- App Version 3.6.0
- Backend: Userspace

**To Reproduce**
When I want to delete a node from ui. It  cannot work.

**Expected behavior**

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! Thank you for reporting this.

 I am able to replicate it and I'm working on a fix.
