### ISSUE TITLE
[BUG] - Problem with app

### ISSUE THREAD

**Issue by zyunling** [zaneschepke/wgtunnel#436]
**Describe the bug**
1，在android tv 上，界面选择中文无效。
2，auto tunneling 开关一点就闪退。
3，restart on ping fail这项，旧版本有地方输入ping的目标地址，3.6版本找不到地方设置ping的地址。

**Smartphone (please complete the following information):**

- Device: TIVO Streamer 4K
- Android Version: [Android 10]
- App Version :3.6

总体使用没问题，也可以开机自动连接。
建议：继续优化TV版的界面，目前字体仍然太小，可以放大字体，按钮，排版等，方便遥控器使用。

**Comment by zaneschepke** [comment]
Hello! Thank you for reporting these issue and for the feedback! 

I have made these fixes and have added the Chinese language and synced Weblate with the repository. 

I will mark this as closed now as these changes will be live soon in 3.6.1. 

If you notice things are still not fixed, please comment back and I will reopen this issue.
