### ISSUE TITLE
[FEATURE] - Turn off Auto-Tunnel on trusted Android Auto connection

### ISSUE THREAD

**Issue by IrrerPolterer** [zaneschepke/wgtunnel#439]
### Problem Statement:

I am using the Auto-Tunnel feature to stay connect to my VPN (my home network) on both untrusted WiFi and on mobile data. However, this creates issues with wireless Android Auto in my car. Android Auto (wireless) requires to not be connected to a VPN. It uses a WiFi-Direct link between my phone and car while keeping mobile data active for internet access.

Setting the car’s WiFi SSID as a trusted Wifi network in the auto tunnel settings does not disable VPN automatically, when I'm connected to Android Auto. This makes sense, because the phone retains the active data connection over mobile network, for internet access in parallel to the Wifi-Direct link with the car.

**Consequently, I have to manually disable the VPN each time I enter the car to use Android Auto.**

### Proposed Solution:

Extend the "trusted WiFi Networks" feature to include networks that will disable VPN even if the phone's internet remains on mobile data. This could be labeled "Trusted Android Auto Networks" or more broadly as "Trusted WiFi Direct Networks."

### Alternatives Considered:

I attempted using Tasker to disable VPN upon connecting to the Android Auto WiFi, but couldn’t find a way to control WG Tunnel via Tasker.

**Comment by IrrerPolterer** [comment]
@zaneschepke as a workaround, could you tell me what Activity/Intent I might use to trigger disabling/enabling the tunnel from Tasker? I've seen that there is a `epke.wireguardautotunnel.service.shortcut.ShortcutsActivity` class. But I haven't been able to make use of that through Tasker yet.

**Comment by zaneschepke** [comment]
Hello! This is a common issue that can be resolved by following this documentation in the app doc's [FAQ](https://zaneschepke.com/wgtunnel-docs/faq.html#does-product-work-with-android-auto) section. You basically just need to configure split tunneling for your tunnel and exclude the android auto app from the tunnel. 

I'll close this for now. Feel free to comment more if you run into problems.

**Comment by IrrerPolterer** [comment]
Thanks a ton! Dang, I should've taken a closer look into the FAQs, only looked at other parts of the docs. 🤦🏻

Just adding some notes for others coming across this issue:

- Docs: [WG-Tunnel & Android Auto](https://zaneschepke.com/wgtunnel-docs/faq.html#does-product-work-with-android-auto) // [Split Tunneling](https://zaneschepke.com/wgtunnel-docs/features.html#split)
- In the tunnel-specific settings (not app settings), go to *Tunneling Apps*
- Disable *Tunnel All Applications*
- Select mode *Exclude*
- Select *Android Auto* from the app list

**Comment by virtuacool** [comment]
> Muito obrigado! Poxa, eu deveria ter dado uma olhada mais de perto nas FAQs, só olhei outras partes dos documentos. 🤦🏻
> 
> Apenas adicionando algumas notas para outras pessoas que estão enfrentando esse problema:
> 
> * Docs: [WG-Tunnel e Android Auto](https://zaneschepke.com/wgtunnel-docs/faq.html#does-product-work-with-android-auto) // [Tunelamento Dividido](https://zaneschepke.com/wgtunnel-docs/features.html#split)
> * Nas configurações específicas do túnel (não nas configurações do aplicativo), vá para _Aplicativos de tunelamento_
> * Desabilitar _Túnel de Todos os Aplicativos_
> * Selecionar modo _Excluir_
> * Selecione _Android Auto_ na lista de aplicativos
> * Salve suas configurações. Agora você pode usar o Tunelamento Automático na rede móvel enquanto ainda estiver conectado ao Android Auto.


Thank you for your recommendations!

I've been having this problem for a few days and I can't solve it in any way.

Only with the VPN turned off can I connect my smartphone to AA.

I even tried deleting all applications in delete mode and it still doesn't work!

I have 5 Proton VPN tunnels configured, one of them as "Primary Tunnel" and this one configured as "Mobile data tunnel".

I don't have "Auto-Tunnel" activated.

What am I doing wrong?
