### ISSUE TITLE
[FEATURE] - Custom DNS entries

### ISSUE THREAD

**Issue by Eskuero** [zaneschepke/wgtunnel#447]
I'm not talking about specifying DNS servers for the tunnel but providing custom DNS entries like:

jellyfin.example.com 192.168.1.4
legend.example.com 10.15.16.19

This would make it easier to configure access for local services on the other side of tunnel without having to setup a custom DNS server.

**Comment by zaneschepke** [comment]
Hello! As far as I am aware, there is no way to do this on android and this is something that would have to be done on your DNS server. You could make this a bit more automated by using search domains on your dns settings for your wireguard config. 

I'll mark this as closed for now, but feel free to continue the discussion if you have more to add.

**Comment by ntova** [comment]
This is (somewhat) possible using Adaway https://f-droid.org/packages/org.adaway/

It lets you define custom /etc/hosts entries. However, it requires root and the entries are always active, not only on VPN.
