### ISSUE TITLE
[BUG] - can't delete tunnel

### ISSUE THREAD

**Issue by gamebird92** [zaneschepke/wgtunnel#449]
**Describe the bug**
Trying to delete a tunnel in the app. It asks me "sure you want to delete" and after pressing "yes" nothing happens. 

**Smartphone (please complete the following information):**

- Device: Pixel 7a
- Android Version: Android 15
- App Version 3.6.0 (F-Droid)

**To Reproduce**

1. Go to Tunnel
2. Long press on a tunnel
3. Select the bin
4. Confirm delete
5. tunnel is still there

**Expected behavior**
tunnel gets deleted

**Comment by merlinuwe** [comment]
Same here with Xiaomi Poco  X3 Pro, Android 11.

**Comment by z5146542** [comment]
Facing same issue on Motorola Razr 40, Android 14

**Comment by zaneschepke** [comment]
Hello! This should be fixed in the latest nightly. I will be creating a new prod release soon with this fix.

**Comment by zaneschepke** [comment]
This is now fixed in 3.6.1 release. Marking as closed.
