### ISSUE TITLE
[BUG] - Excluding apps doesn't works on the fly

### ISSUE THREAD

**Issue by don-dolarson** [zaneschepke/wgtunnel#450]
**Describe the bug**
Excluding apps from tunneling function doesn't work on the fly.

**Smartphone (please complete the following information):**

- Device: OnePlus 5T
- Android Version: LineageOS 20
- App Version: 3.6.0-c2725bf-nightly
- Backend: Kernel

**To Reproduce**

1. Tunnel settings > Add a recently installed app to excluded list
3. Go to ip.me if the excluded app is a browser and see what IP address is showing up or test the application by external service logs and search for connections.

**Expected behavior**
No tunneling excluded app

**Screenshots (Only if necessary)**

**Additional context**
It works as expected by a device restart or by stopping the WG Tunnel application several times and reconnecting the tunnel.

**Comment by zaneschepke** [comment]
Hello! Yeah, as it stands the tunnel would need to be restarted in order for changes to take effect. 

Are you requesting for the tunnel to automatically restart after changes to the config?

**Comment by zaneschepke** [comment]
This functionality been added in https://github.com/zaneschepke/wgtunnel/pull/476 and should be live in the nightly tonight and in the next release soon. Marking this as closed for now. If there are any issues, we can reopen.
