### ISSUE TITLE
[FEATURE] - Option to send keeptalive when screen is unlocked and keeptalive is off globaly

### ISSUE THREAD

**Issue by io43** [zaneschepke/wgtunnel#452]
Do it make sense to request a feature to add an option to send a keep alive request (or anything to wake the connection) when the screen is getting unlocked while keept alive are not enabled in the wireguard tunnel config? 

Because to save battery and follow the recommended best practice for wireguard i dont have kept alive on, the issue is that when you try to use your browser when the  phone have been not in use for a while then the first time you get a dns error because the request is sent too early while wireguard is establishing the connection or something like that, it may not apply on phones with google services because play services keep a connection open for push notifications so the connection never need to wake up i guess.  

This option would help a lot because it is really painfull to always have to refresh the page multiple times, thanks

edit, i just realized that it is maybe because i use DoH dns in chrome? will try with it off but i wanted to use doh for chrome while using wireguard server dns for everything else

**Comment by zaneschepke** [comment]
Hey! I haven't experienced this same issue so I think it is related to something with your network/configuration. 

We can keep discussing this issue and I can reopen if necessary, but I'll mark it as closed for now.
