### ISSUE TITLE
[BUG] - Problem with app. Remote control air mouse application selection does not work (tunneling apps) Cant select app by mouse

### ISSUE THREAD

**Issue by mgsm163** [zaneschepke/wgtunnel#461]
**Smart Box TOX1:**

- Android Version: 9.0
-Remote control air mouse application selection does not work (tunneling apps)
wgtunnel [3.6.1](https://github.com/zaneschepke/wgtunnel/releases/tag/3.6.1)

**Comment by zaneschepke** [comment]
Hello! So this specifically doesn't work when doing the split tunneling app selection?

**Comment by mgsm163** [comment]
only the first application is checked, the next ones are not checked.

**Comment by mgsm163** [comment]
the cursor does not make a selection

**Comment by mgsm163** [comment]
![Screenshot_18](https://github.com/user-attachments/assets/4066187b-13bd-4c75-9b4c-429d595b234c)
Cant select app by mouse

**Comment by zaneschepke** [comment]
I'll work on a fix. Thanks for the details!
