### ISSUE TITLE
[BUG] - IP leak when Auto Tunneling

### ISSUE THREAD

**Issue by Samm160** [zaneschepke/wgtunnel#466]
Hi,
I have been using the app and was happy.
I set my SSID Wifi as trusted and everything else untrusted.
I am using Auto tunneling.
Everything is working Great until I found out: when I am leaving my wifi and connecting to my mobile network, it take a few second and during this time, the real ip is leaking (to be exact, the mobile network is leaking).
Each time I get away from wifi and while switching to mobile network, the real IP leak for few seconds.
Please help to resolve this issue, otherwise the app is unusable.

**Comment by zaneschepke** [comment]
Hello! To prevent IP leaks, I recommend enabling Android's native kill switch in the Always-on VPN settings. This should prevent this leak.

**Comment by Samm160** [comment]
Alternative solution is to add the option of blocking data packet during this transaction (from Wifi to mobile data)
Which is like new feature.
