### ISSUE TITLE
[BUG] - Breaking change after v3.5.4?

### ISSUE THREAD

**Issue by hippi-viking** [zaneschepke/wgtunnel#471]
**Describe the bug**
It seems like there might be a breaking change after v3.5.4. I have (had) the app installed and working on multiple phones for some time now. After updating from v3.5.4 to v3.6.0 or v3.6.1 the app crashes constantly and is not able to start up. When being uninstalled, reinstalled and set up again it seems to work again.
I have multiple tunnels set up, one of them has multiple endpoints with different networks routed over. DNS lookups are also routed through the tunnels. I am using Wireguard as a kernel module.

**Smartphone (please complete the following information):**

- Device: Xiaomi Mi A3
- Android Version: Android 14 ([v2024.02.27](https://github.com/ponces/treble_aosp/releases/tag/v2024.02.27) AOSP build - the latest one that works on my devices)
- App Version 3.6.0, 3.6.1
- Backend: Kernel

**To Reproduce**

1. Install v3.5.4 or earlier on device
2. Set up tunnels with AllowedIP ranges and DNS servers
3. Switch to kernel module and always-on VPN options
4. Update app to v3.6.0 or v3.6.1

**Expected behavior**
App continues to work after update.

[edit] The app doesn't need to be uninstalled and reinstalled, it's enough to reset its data. So the older stored data is no longer compatible with the v3.6.x series.

**Comment by hippi-viking** [comment]
Is there a way to access and save the tunnel configuration without the app being able to start up so I don't need to regenerate and adjust keys on all the endpoints?
Thanks!

**Comment by zaneschepke** [comment]
Hey! I'm sorry about the breaking changes here. I usually avoid breaking changes at all costs and I'll try to prevent any breaking changes in the future that are not absolutely necessary.

**Comment by hippi-viking** [comment]
Hello, no worries, just to let you know. There is another one in v3.6.3. Luckily the tunnels keep working this time (haven't restarted the phones yet), but  the app itself crashes.
I suppose this might also be related to the multiple-endpoint tunnel(s).
