### ISSUE TITLE
[FEATURE] - Organise tunnel details differently

### ISSUE THREAD

**Issue by hippi-viking** [zaneschepke/wgtunnel#473]
**Is your feature request related to a problem? Please describe.**
Tunnel details are not visible when multiple endpoints are used.
![1000000073](https://github.com/user-attachments/assets/8f71985e-3135-406c-a7ef-a266bb57dc31)

**Describe the solution you'd like**
The display used before the v3.6.x series was better in this regard: details of a single tunnel in a row, one tunnel per row.

**Describe alternatives you've considered**
Details of a single tunnel per row.

**Comment by zaneschepke** [comment]
Hello! Thank you for the report. Can you share your phone locale and device? I'm unable to reproduce this.

**Comment by hippi-viking** [comment]
Hello! :) No problem, thank you for looking into this. Sure, i'm using a Xiaomi Mi A3 with Hungarian locale. The problem - i think - might be is that i have multiple tunnel endpoints for a single wireguard interface.
(These are multiple segments of my network, which all can be accessed separately for failover reasons. Traffic is policy-routed between these endpoints based on IP addresses. And there are multiple wireguard interfaces for these endpoints separately - if the link would fail somewhere -, with the whole traffic routed through that link. (So those would act as a classic VPN.))

**Comment by zaneschepke** [comment]
Thanks for the details. I'll try to reproduce!
