### ISSUE TITLE
[BUG] - Repository rebase failed [Weblate]

### ISSUE THREAD

**Issue by Nmrawe** [zaneschepke/wgtunnel#484]
WG Tunnel translations files are not getting updated probably due to merge conflicts: https://hosted.weblate.org/changes/browse/wg-tunnel/

**Comment by zer0fl0w** [comment]
yes, i wondered why the zane schepke repository for fdroid/droidify is still stuck at 3.6.0...

...now i know (:

**Comment by zaneschepke** [comment]
I'll work on fixing this. As for my Fdroid, that is actually a separate, upstream bug which you can see the details on the issues of that repo.

**Comment by zaneschepke** [comment]
Hello! This should be fixed now. I'm sorry about that wait!

**Comment by zaneschepke** [comment]
> The "strings" component has been blocked for some time.

I'm sorry about that. I just unlocked it.

**Comment by zaneschepke** [comment]
> Thanks!
> 
> BTW, this [string](https://hosted.weblate.org/translate/wg-tunnel/strings/en/?q=Auto-tunnel+Channel) is read-only for some reason.

Yeah, this is correct. This is a channel Id string so it shouldn't be localized. It is not visible to user.
