### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by Elbullazul** [zaneschepke/wgtunnel#49]
Would it be possible to speed up the animation speed when changing screens and add a black theme for OLED screens?

**Comment by zaneschepke** [comment]
Hello! Thank you for using the app and for the feedback.

Yes, I will look into this.

**Comment by zaneschepke** [comment]
The animations are much improved now in the new versions. At some point in the near future I will add support for changing the theme colors.

**Comment by zaneschepke** [comment]
The lastest [3.5.0](https://github.com/zaneschepke/wgtunnel/releases/tag/3.5.0) now includes android monet dynamic theming as well as light/dark mode support. I'll keep this open for now as I think the nav animations could still use some work.
