### ISSUE TITLE
[BUG] - Application crashes when Auto-tunnel is on since 3.6.2

### ISSUE THREAD

**Issue by bmonjoie** [zaneschepke/wgtunnel#496]
**Describe the bug**
Since 3.6.2, when turning on auto-tunnel, the application crashes immediately. It also crashes on start when updating from 3.6.1 if auto-tunnel is on. 

**Smartphone (please complete the following information):**

- Device: Pixel 8 Pro
- Android Version: Android 15
- App Version: 3.6.2 and 3.6.3

**To Reproduce**

1. Install 3.6.2 or 3.6.3
2. Add a VPN
3. Toggle on Auto-Tunnel

**Expected behavior**
The application doesn't crash

**Comment by zaneschepke** [comment]
Hello, this crash was fixed in 3.6.3. Are you sure it is still happening on this version? 

Basically, I accidentally made a typo where auto-tunnel service was creating the wrong notification channel. If you try to launch a notification when a channel has not been created then it can cause a crash.

**Comment by bmonjoie** [comment]
It happened to me after F-droid updated to 3.6.3.
I'll have access to my computer tomorrow and I'll check with ADB what the root cause of this crash is.

**Comment by JohannCR** [comment]
FYI the crash happened to me and disappeared after uninstall, reinstall and reconfiguring from scratch.

**Comment by Step-MS** [comment]
I have got version 3.6.3, Pixel 8 Pro as well. It seems that it crashes after some time (no connection with tunnelled app, restarted WG Tunnel and it worked again, all app energy options OFF). AutoTunnel for mobile data and App tunneling are on. I think old Version worked better. Turned on logging and waiting for next Crash ;-)...by the way GREAT JOB, THANKS! :-)

**Comment by bmonjoie** [comment]
I have just installed version 3.6.3 from the GitHub releases page (updating from 3.6.1) and it didn't crash.
Could it be possible that F-Droid installed 3.6.2 thinking it was 3.6.3?
I'll close this ticket as I cannot reproduce it with the release from this GitHub.
