### ISSUE TITLE
[FEATURE] - Reduce the amount of location requests for untrusted WiFi auto-tunnel feature

### ISSUE THREAD

**Issue by Mynacol** [zaneschepke/wgtunnel#498]
**Is your feature request related to a problem? Please describe.**
The amount and frequency of location requests when using the untrusted WiFi auto-tunnel feature gets annoying. Modern Android shows an indicator each time it is requested. It clutters the privacy dashboard with so many location requests you cannot comfortably use it to track the location permission usages of other apps.

**Describe the solution you'd like**
Maybe use network change broadcasts to get notified by Android whenever the network configuration changes. This would limit the required location permission requests to exactly the times the network changes. (See #419 for some more details).

**Describe alternatives you've considered**
Preserve the status quo, it is functional and at worst only annoying.

**Additional context**
Past discussion was in issue #419, this one tracks the frequent location requests.

**Comment by zaneschepke** [comment]
Hey! I did some work to improve this and there should be less location queries in the next release. Using a broadcast receiver for this information is deprecated on the later APIs so hopefully these changes I've made help make this a little less annoying.
