### ISSUE TITLE
[BUG] - Tunnel automatically disconnects after 4 seconds

### ISSUE THREAD

**Issue by z5146542** [zaneschepke/wgtunnel#499]
**Describe the bug**
After toggling a tunnel, the connection automatically disconnects after 4 seconds. Further attempts lead to the same result, but after a while (1-2 minutes) toggling works as intended.

**Smartphone (please complete the following information):**

- Device: Motorola Razr 40
- Android Version: Android 13
- App Version 3.6.3
- Backend: Userspace

**To Reproduce**

Toggle on a tunnel and wait 4 seconds.

**Expected behavior**
The tunnel should not disconnect automatically after 4 seconds.

**Additional context**

'Allow Always-On VPN' and 'auto-tunnelling' is set to 'true'.

Problem seems to exist whether I am connnected to WiFi or mobile data.

This has not been a problem at all in the previous version, so I am most certain my WG VPN server is fine.

**Comment by zaneschepke** [comment]
Hello! I'm unable to replicate this. Can I ask what you are using auto tunneling for in combination with AOVPN?

**Comment by zaneschepke** [comment]
I think this should be resolved with 3.6.5. Let me know if you're still experiencing issues and we can reopen.
