### ISSUE TITLE
Feature Request: kill switch

### ISSUE THREAD

**Issue by mrbluecoat** [zaneschepke/wgtunnel#5]
It would be great to implement a kill switch that prevents any network activity if the VPN is disabled if both `Turn on mobile data` and `Tunnel all applications` are enabled and the VPN is set to always-on

**Comment by zaneschepke** [comment]
Hello! I'm not sure if I am understanding this correctly but are you requesting that the app stops your phone's network traffic if VPN is not running and you want it to always be running? I did a small amount of searching on this and I don't think this is something a typical android app can do. I could be wrong.

**Comment by mrbluecoat** [comment]
Correct, if the VPN connection drops, the kill switch activates and blocks your device's internet access. This prevents you accidentally sending data outside of the secure VPN tunnel, because if the tunnel fails then you won't be able to send any data at all.

Android has a built-in 'Always-on VPN' setting but it's not foolproof: https://github.com/tailscale/tailscale/issues/1698

If you can provide an intent or other means (such as a password or PIN) to disable the ability to turn off the VPN in the app UI we could use that in combination with the native Always-On Android setting

**Comment by zaneschepke** [comment]
Currently, the app does not integrate with Android's built in "Always-on" capability. I can see this as a useful feature to add in the future. We would not need to disable turning on and off the VPN in the app GUI because with "Always-on" enabled it will still stay connected to the VPN no matter how you manipulate the connection in the app. If you combine this with Android' "Block connections without VPN" setting I think you will get your desired result.

**Comment by mrbluecoat** [comment]
Yes, perfect. Happy to test when ready.

**Comment by mrbluecoat** [comment]
Works great, thanks!

Any chance you can auto-start the tunnel at boot? Always On prevented network access after reboot and force stop of app which is perfect but would be awesome to identify a preferred tunnel that auto-connects.

**Comment by zaneschepke** [comment]
I rebooted my phone with always on enabled and it did start my tunnel again at boot. Did yours not do that?

**Comment by mrbluecoat** [comment]
I retried this morning and it worked. All good - thanks again!
