### ISSUE TITLE
Feature Request: More flexibility for auto-tunneling settings

### ISSUE THREAD

**Issue by mjmccans** [zaneschepke/wgtunnel#50]
First off, fantastic app. I have been using it for a while on multiple devices and it works great. With the new "battery saver" option enabled it barely uses any battery while being more reliable than other solutions I have tried (such as my Tasker based solution, which was great but did not work reliably when the screen was off on the device). 

For my use case it would be great if there was more flexibility regarding setting which tunnels are enabled for different SSIDs / mobile data connections. I have three "levels" of networks: (1) local network; (2) trusted networks; and (3) everything else. For the "local network", this would be a "trusted SSID" in your app where no VPN tunnel is enabled because the resources I need to access are local. For the "trusted networks", I enable a split tunnel so I can access the resources I need (including a DNS server) but the remainder of the traffic flows outside of the tunnel because the network is trusted (and I happen to use this tunnel for mobile data as well). For "everything else", I enable a full tunnel so all traffic is protected (for example, when connected to public wifi or any other SSID that I have not tagged as being "trusted"). 

In my experience the type of setup that I have is fairly common, and it would be fantastic if your app could handle such a setup. There are a number of ways that I believe you could enable this feature from an interface perspective, and I wonder if some inspiration could be taken from the iOS version of the WireGuard app where it looks like to can specify certain tunnels that are enabled for "only these SSIDs" or "except these SSIDs". In Tasker I have achieved this setup by creating Variables for "No VPN SSIDs", "Trusted SSIDs" (which includes mobile data) and set up Profiles that turn on the tunnels as appropriate, including defaulting to the full tunnel if the SSID does not match any of the Variables). However, I believe you could achieve something more flexible for all users with an approach similar to the iOS WireGuard app if there was also the concept of a "default" tunnel (the full tunnel in my case).

I hope I have described the feature request in a way that makes sense, but please let me know if you have any questions. I realize that it would add complexity to your app, but I also believe it would open up many new use cases that could be beneficial for a lot of users.

**Comment by zaneschepke** [comment]
Hello! Thank you so much for the feedback and for using the app! I'm glad you are enjoying the (long overdue) battery saver feature. I am always looking for feedback on that feature.

This is all a great idea. I really should have built the app with this flexibility from the start, but I was too busy hacking away. 😁 I'll take a look at the iOS implementation of wireguard official as suggested. This would be a super valuable feature that I don't think would be too hard to add. The app already has the "default tunnel" concept with the "primary tunnel" feature.

**Comment by mjmccans** [comment]
Thank you for being so receptive to ideas; I know what it is like to deal with the sometimes unrealistic expectations of an open source userbase. I think the iOS implementation may have some good ideas to draw from, but I have not used it myself so I am not clear how much flexibility it has (I only looked at screenshots of the app). Your app is already fantastic and much more reliable for me than other solutions. I just think implementing more flexibility could really take it to the next level and allow for some new and unique use cases. Thanks again, and I am happy to help out with testing if you do end up trying to implement this feature suggestion.

**Comment by datkush420** [comment]
It's nice to see this as I was getting ready to request this feature myself.

Currently, I have two tunnels. The first, is a full tunnel that forwards all traffic and is used on untrusted / public wifi networks when away from home. The second, is a "split" tunnel that only forwards dns and LAN traffic. This is used when on mobile data and is great for battery life.

The auto tunneling feature currently works great and enables/disables my split tunnel that I have set as primary when switching from trusted wifi to mobile and vice versa. It's quick and reliable and I prefer using this app compared to Tasker. However, when I connect to untrusted wifi the app wants to use my split tunnel instead of the full tunnel.

I've been using this app for a couple weeks now and I thank you for your work and I appreciate your openness to ideas / features suggested by the community.

**Comment by Kopernikus1979** [comment]
Same here, fantastic app. Before I also used Tasker but this is much better. Hoping this feature gets added soon. Thx

**Comment by zaneschepke** [comment]
I'm sorry it took me so long to get to this one. I hope the new changes are beneficial and I am open to any additional feedback/requests for additional auto-tunneling flexibility.

**Comment by Kopernikus1979** [comment]
@zaneschepke 

No problem at all, glad someone is making this excellent app.
Should I download latest version from F-Droid or Play Store?

**Comment by zaneschepke** [comment]
> @zaneschepke
> 
> No problem at all, glad someone is making this excellent app. Should I download latest version from F-Droid or Play Store?

Thank you for using it! I will always recommend F-Droid. Anything you download from the Play Store adds tracking to the app.
