### ISSUE TITLE
[BUG] - App crashes on launch on 3.6.3

### ISSUE THREAD

**Issue by JohannCR** [zaneschepke/wgtunnel#500]
**Describe the bug**
Cannot open app, it keeps crashing.

**Smartphone (please complete the following information):**

- Device: Fairphone 4
- Android Version: Android 13
- App Version 3.6.3

**To Reproduce**
Open app

**Expected behavior**
Shouldn't crash
**Screenshots (Only if necessary)**

**Comment by JohannCR** [comment]
Also none of Fdroid old versions apk seems to install... How can we revert to a previous version ?

**Comment by JohannCR** [comment]
3.6.3 Works again after reconfiguring from scratch.

**Comment by chriszf** [comment]
I have the same problem on a pixel 6 on Android 14, but it was not resolved by reconfiguring, I had to downgrade to 3.6.1. That said, the configuration was created remotely and installed through a QR code.

**Comment by Zaptyp** [comment]
I can reproduce that bug is in app after upgrading from 3.6.2 to 3.6.3

**Comment by Erlotinib** [comment]
I can also reproduce with 3.6.3 (fdroid) on android 11 (lineageos)

clearing data fix the crash and I was able to reconfigure with a qr code

**Comment by zaneschepke** [comment]
I'm really sorry about this one. Yes, there is breaking change/crash when updating from 3.6.2 to 3.6.3. Unfortunately, there is not much I can do about it at this point, but I will make sure to be more diligent in my testing going forward before creating a new release.
