### ISSUE TITLE
[BUG] - DNS servers field randomly reset to empty

### ISSUE THREAD

**Issue by ad-on-is** [zaneschepke/wgtunnel#501]
**Describe the bug**
I don't know how and when, but sometimes the DNS servers field gets reset to an empty value

**Smartphone (please complete the following information):**

- Device: ObePlus 8T
- Android Version: Android 14
- App Version 3.6.3
- Backend: Userspace

**To Reproduce**

- Randomly without user interaction 

**Expected behavior**
DNS servers should not reset at all without user intentions 

**Screenshots (Only if necessary)**

**Additional context**

**Comment by zaneschepke** [comment]
Hello! I think this should be fixed on the latest changes to the config screen as I fixed a few bugs with how tunnel configs were being saved. I'll mark it as closed for now. If you notice this issue happening again in 3.6.4 just send another message and I'll reopen the ticket.
