### ISSUE TITLE
[BUG] - stability issues with autotunnel since last few updates

### ISSUE THREAD

**Issue by zilexa** [zaneschepke/wgtunnel#505]
**Describe the bug**
Its been hit or miss with the last couple of updates and auto tunneling. Even with the app open, auto tunneling did not happen when turning off wifi. But now hours later when I turn off wifi, without having the app open, it works again. 

**Smartphone (please complete the following information):

- Device: Asus Zenfone 10
- Android Version: Android 14
- App Version 3.6.3
- Backend: [e.g. Kernel, Userspace]

**To Reproduce**

1. Leave trusted Wifi. Wait for mobile network data connection icon. 
2. Wait for vpn connection. Notice it's not happening.
3. Long press on tunnel control quick tile to go to app.
4. Notice still no vpn connection.
5. Now just toggle auto tunneling off and on again.
6. Notice the connection is being made.

**Expected behavior**
Like it used to, robustly auto connect to my wireguard profile when leaving trusted Wifi. 

**Screenshots (Only if necessary)**

**Additional context**
It just seems to be less reliable lately with the last couple of updates.

**Comment by zaneschepke** [comment]
Hello! Thanks for the report!  Is this something that happens consistently or occasionally? Also, are you using kernel mode or just default userspace?

**Comment by slu-010101** [comment]
We also have problems with the auto tunnel function on four different smartphones.
It works over weeks without an issue, but since 3.6.3 the WG tunnel is disabled multiple times a day.

Auto tunnel is only used with the ping function to detect a WAN ip change of my WG server.

Maybe the same cause?

As soon 3.6.4 is over F-Droid available I will try it.

**Comment by zilexa** [comment]
Honestly the app hasn't worked for me all week. Zero auto tunneling. Just got home, am on WiFi and still on VPN. Even when I open the app, it doesn't disconnect VPN. 

I installed the Nightly but its a separate app. Empty. Zero configuration, no tunnels nothing. So I removed it again. 

The older version, I think 3.1 or sth worked totally fine..

**Comment by zaneschepke** [comment]
I'm really sorry about the stability issues. I've been trying to keep adding features/updates to the app, but due to life I've had very little time to test these changes. Over this Christmas break I'm having more time to dig in and get the app back to stable so I think you see improvements soon!

**Comment by slu-010101** [comment]
Still have issues with 3.6.4, but I see something who can help you maybe to debug.

I disable wifi on a Pixel 7a and my WG tunnel disconnect, enable WG again and enable wifi, WG tunnel disconnect again.
Now I enable "Settings -> Local logging" to see what's in the logs and now it works without issue and my WG don't disconnect again.

I see similar on a other Android device, as soon the logging is enabled it's stable.

Make this any sense?

**Comment by deftmartian** [comment]
Seeing the same issue with last few updates.  Currently on 3.6.4. Pixel 7 w/ grapheneOS fully updated - android 15. 

Tried erasing data and uninstalling and reinstalling. Did not fix.  

Manually toggling auto tunneling will make it work, but disconnecting trusted wifi with app open doesn't engage tunnel.

**Comment by slu-010101** [comment]
@deftmartian do you have logging enabled or disabled?

**Comment by deftmartian** [comment]
> @deftmartian do you have logging enabled or disabled?

I tried with both after seeing your comment - no change.  I was seeing auto tunnelling working directly after changing settings, but not after a few hours.  This behaviour was with all versions i was having issues with.     I switched to 3.6.5 from @zaneschepke's repo last night.  Seeing if that fixes it.

**Comment by deftmartian** [comment]
Been on 3.6.5 since 12 hrs ago.  Same issue as last versions.   Auto tunneling worked after I installed 3.6.5 and tested it.  But no longer working now when I turn wifi off.

**Comment by zaneschepke** [comment]
Thanks for the additional details. For those experiencing issues, if there are any logs you could email me that would be most helpful.

**Comment by zaneschepke** [comment]
> > @deftmartian do you have logging enabled or disabled?
> 
> I tried with both after seeing your comment - no change. I was seeing auto tunnelling working directly after changing settings, but not after a few hours. This behaviour was with all versions i was having issues with. I switched to 3.6.5 from @zaneschepke's repo last night. Seeing if that fixes it.

I have the exact same phone and OS. I'll try to reproduce this, but so far I am unable to do so. Is the auto tunnel service being killed by the OS? When it stops working is the auto tunnel service still running? (You should be able to either see the notification or the apps that are active when you pull down the quick tile menu to fully expanded and look at the bottom for "x apps are active")

**Comment by deftmartian** [comment]
> > > @deftmartian do you have logging enabled or disabled?
> > 
> > 
> > I tried with both after seeing your comment - no change. I was seeing auto tunnelling working directly after changing settings, but not after a few hours. This behaviour was with all versions i was having issues with. I switched to 3.6.5 from @zaneschepke's repo last night. Seeing if that fixes it.
> 
> I have the exact same phone and OS. I'll try to reproduce this, but so far I am unable to do so. Is the auto tunnel service being killed by the OS? When it stops working is the auto tunnel service still running? (You should be able to either see the notification or the apps that are active when you pull down the quick tile menu to fully expanded and look at the bottom for "x apps are active")

Sent an email with logs and settings etc.

**Comment by deftmartian** [comment]
Appears that 3.6.5 fixes it for me on pixel 7 w/ grapheneos.  Required a reboot to work though.  Checked with logging and no logging.   thanks @zaneschepke !

**Comment by zaneschepke** [comment]
@zilexa Has this improved for you as well?

**Comment by deftmartian** [comment]
I may need to walk my comment back.  I noticed issues the other day after over a day of device uptime.  I enabled logging, but haven't had much time to test it since.

**Comment by zilexa** [comment]
Yes auto tunneling seems to work well again. Thanks!
Unfortunately the tile (tunnel control) state is not updated properly. It seems to be always "on".

**Comment by zaneschepke** [comment]
Thanks for the update! I'm working on a fix for the tile which is currently being tracked in #491. 

I'll mark this one as resolved for now. 

Thanks again!
