### ISSUE TITLE
[BUG] Cell network disconnected on vpn start

### ISSUE THREAD

**Issue by Shulyaka** [zaneschepke/wgtunnel#509]
**Describe the bug**
If I am on mobile data (no wifi), I often lose cell network connectivity when I activate the tunnel. When it reconnects and the tunnel is reactivated, it can happen again. This seems like an Android bug, but it doesn't happen on other VPN clients. Could that be a known issue or some parameters I need to change?

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S23+
- Android Version: Android 14
- App Version 3.6.3
- Backend: Userspace

**To Reproduce**

1. Disconnect Wi-Fi
2. Start the tunnel
3. See error (no cellular service message and no 4G+ connection)

**Expected behavior**
VPN started without disconnecting from the cell network

**Screenshots (Only if necessary)**

**Additional context**
I have collected adb logcat, but couldn't find a relevant part in it myself.

**Comment by zaneschepke** [comment]
Hey! Can you describe in a little more detail exactly what you are seeing? I am not following.

**Comment by Shulyaka** [comment]
I will better show you. Pay attention on the top right corner in the below video:
https://github.com/user-attachments/assets/e5127a73-f594-4c2e-965c-39da772f1ca2

**Comment by zaneschepke** [comment]
Thanks! That is definitely helpful. Does this same behavior happen when you use the official wireguard client?

**Comment by Shulyaka** [comment]
No, I haven't seen this behavior on other VPN clients, including the official Wireguard app, AmneziaWG, and various OpenVPN-based clients.
Note that I am unable to test the official wireguard client end-to-end right now, because my mobile ISP blocks vanilla wireguard handshakes, but I think this issue should have manifested itself before the handshake. I will travel to another country next month, will try with a local mobile provider.
AmneziaWG works fine, but lacks the functionality to autoconnect based on Wi-Fi networks, which is an awesome feature of this app!

**Comment by Shulyaka** [comment]
I have upgraded to version 3.6.5 and I can no longer reproduce this behavior. Not sure what you did, but it looks like you have solved it. Thanks!
