### ISSUE TITLE
[FEATURE] - Disable Auto Tunnel on Android Auto / Specific BT

### ISSUE THREAD

**Issue by indiana11011100** [zaneschepke/wgtunnel#511]
**Is your feature request related to a problem? Please describe.**
First Android Auto is not able to run with VPN connections.
Second, somehow VPN and Android Auto crashes the mobile. Touchscreen is extremely slow and touch reaction is partially executed or delayed as interaction can't be seen.
Finally device must be rebooted.

**Describe the solution you'd like**
Two options would be possible.
1. Detect Android Auto activity. Maybe this is not possible as it won't start correctly until VPN is turned off. And maybe the mobile would crash anyway, as disabling the VPN could be to late.
2. Blacklist Bluetooth IDs. Like the WIFI List. This could prevent a restart and everything else I guess.

**Describe alternatives you've considered**
Maybe Automate or MacroDroid integration. At least no real alternative.

**Additional context**
This Android Auto behaviour I have since the Pixel 6 (first try with it) and actually on my work and private mobile Pixel 8.
Sorry, no screenshot as I have this problem only with rented cars (Business Travel). I'm really happy my own car does not have Android Auto ;)

Anyway I really would appreciate the preferred solution BT Blacklist.

Thanks in advance and your great work with this App. I really love it.

**Comment by zer0fl0w** [comment]
wired android auto does not care if phone has active vpn. i use it all the time.

wireless android auto does indeed need vpn disabled at phone.

but it does not crash/reboot the phone. this might be a individually problem with your specific device. but it is in nonway generic.

**Comment by zaneschepke** [comment]
Hello! The best option for Android Auto is to configure split tunneling to exclude the android auto package from the vpn connection. You can see more details here: https://zaneschepke.com/wgtunnel-docs/faq.html#does-product-work-with-android-auto. There is a bug that can occur when configuring split tunneling where if you navigate back to edit config screen after configured your packages they might get reset, but this has been fixed and will be part of the next release. I'll mark this as closed for now.

**Comment by indiana11011100** [comment]
> wired android auto does not care if phone has active vpn. i use it all the time.
> 
> wireless android auto does indeed need vpn disabled at phone.
> 
> but it does not crash/reboot the phone. this might be a individual problem with your specific device. but it is in no way a generic problem.

In this case you are probably right and it could be caused by work profile or some installed App... Anyway it is (was) really anoying and made me crazy in other cars than mine ;)

> Hello! The best option for Android Auto is to configure split tunneling to exclude the android auto package from the vpn connection. You can see more details here: https://zaneschepke.com/wgtunnel-docs/faq.html#does-product-work-with-android-auto. There is a bug that can occur when configuring split tunneling where if you navigate back to edit config screen after configured your packages they might get reset, but this has been fixed and will be part of the next release. I'll mark this as closed for now.

Thanks a lot! 

Whish you all happy and relaxing Christmas time :)
