### ISSUE TITLE
fdroid ahead of github/repository

### ISSUE THREAD

**Issue by zer0fl0w** [zaneschepke/wgtunnel#512]
fdroid is already at v3.6.4, while github and your own repo are still at v3.6.3?

how?

just curious.

**Comment by zaneschepke** [comment]
Hmm, for some reason Fdroid updated despite the fact I have it configured to only update by release tag. At some point pull the latest for the repo and saw I bumped the version code (for prerelease versions) and pulled it and deployed it.. 🫤
