### ISSUE TITLE
[BUG] - Compiling error 

### ISSUE THREAD

**Issue by R7010A** [zaneschepke/wgtunnel#526]
**Describe the bug**
Trying to build the apk from source, but compiling fails

**Smartphone (please complete the following information):**

- Device: OnePlus Nord 3
- Android Version: A14
- App Version 3.6.6

**To Reproduce**

git clone https://github.com/zaneschepke/wgtunnel
cd wgtunnel
./gradlew assembleDebug

**Hint: java-17-openjdk-amd64 is installed on my system**

**Additional context**
Error:
`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':buildSrc'.
> Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
> Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@747815a9 of type BuildFlowService.Parameters
> A problem occurred configuring project ':buildSrc'.
> Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
> Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]`

**Comment by zaneschepke** [comment]
Hey! 

I think there is some issue with your environment/java install. 

try this

```sh
apt install openjdk-17-jdk openjdk-17-jre
java --version
echo $JAVA_HOME
```

**Comment by zaneschepke** [comment]
We can keep chatting about this here, but I'll mark this as closed for now as I don't think this is a bug with the app.
