### ISSUE TITLE
[QUESTION] - Latest release only in Google Play store

### ISSUE THREAD

**Issue by merlinuwe** [zaneschepke/wgtunnel#527]
Why is the latest release only available in Google Play Store? I miss it in Droid-ify and F-Droid.

**Comment by zaneschepke** [comment]
Hello! I'll have to look at why Fdroid is not updated, but these updates can take up to 1 week to go live in Fdroid official so Google Play will usually be live faster. 

I recommend adding my personal repo to the Fdroid app if you want updates faster: https://github.com/zaneschepke/fdroid

**Comment by merlinuwe** [comment]
Thank you very much for the tip, it works, I've got 3.6.6 with Droid-ify,soon.
