### ISSUE TITLE
[BUG] - Stop on no internet [Not Working]

### ISSUE THREAD

**Issue by tomlyo** [zaneschepke/wgtunnel#529]
**Describe the bug**
Tunnel active, no internet, the tunnel remains connected, unable to access websites. As soon as I disable the tunnel my internet connectivity is restored. This can happen for a variety of reasons such as internet loss on the wireguard vpn side (I run a home VPN server). It's not a good experience to remain connected to a non-functioning tunnel blocking internet entirely when disabling/stopping it would resolve the issue. 

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S20 FE 5G
- Android Version: Android Version
- App Version 3.6.5
- Backend: User-space

**To Reproduce**

0. Ensure "Stop on no internet" is checked on auto-tunnelling, and auto-tunnelling is enabled.
1. Auto tunnelling connects to the tunnel successfully, verified internet connectivity.
2. Stop the tunnel/wireguard service that I'm connected to
3. Client remains connected to the tunnel despite the connection dropping. Attempting to browse the internet fails and I cannot access any web pages all of a sudden.

**Expected behavior**
I'm expecting the tunnel to stop so that my device can revert back to 4G LTE, instead I remain on the tunnel unable to access anything.

**Additional context**
My wife uses this app as well, she does not have the experience to understand what's going on when suddenly her internet stops working randomly.

**Comment by zaneschepke** [comment]
Hello! Stop on no internet means stop the tunnel when your phone has no internet connectivity (mobile data and wifi is off or has no internet access, airplane mode is on, etc). It does not mean when there is no tunnel connectivity (thus the airplane mode symbol). 

If there is an issue with this feature or if it should have a different wording let me know and I can change that to make it more clear what this feature is for, but I'll mark this as closed for now.
