### ISSUE TITLE
Support for Android TV!? 

### ISSUE THREAD

**Issue by mpenachayan** [zaneschepke/wgtunnel#53]
Hi, i was searching for another Wireguard client with auto connect for mi Xiaomi TV stick 4k and avoid using the VPN provider app.
I found that your app can be installed from Play Store in Android TV.
I managed to connect to my VPN provider from this app but I cannot change The settings as it's not optimized for TV and keyboard does not launch and there are no way to navigate through settings.
Do you have any plans to add full Android TV support to the app??

**Comment by zaneschepke** [comment]
Hello! Thank you for using the app. 

The AndroidTV experience is a bit clunky as it was not originally designed for TV, but everything should be fully functional. What text box are you trying to launch the keyboard on? You should be able to navigate through the settings as well. 

Can you confirm you are on the latest version 3.2.0?

**Comment by mpenachayan** [comment]
I can confirm i am using version 3.2.0.
And the problem is not only in a textbox. It's in all text boxes. If i try to edit a tunnel to change DNS, there is no way to modify that. And in the settings tab it's always in Add Trusted Ssid. There ir no way to write anything nor to move down to change other settings.
I tried using also google home app keyboard but nothing happens

**Comment by zaneschepke** [comment]
You have to click the center D-pad button while hovering a text box to show the keyboard. It does not auto pop up the keyboard. We made it that way so when you are scrolling through a page, like the edit config screen, it does not pop up the keyboard every time to hover a new text field. 

I was able to verify this works on my Chromecast stick with version 3.2.0.

**Comment by mpenachayan** [comment]
I think 99% Of the Android TV apps behave that way so I already did that multiple times but my biggest issue is that I cannot leave the textbox, there is no way to scroll to other options

**Comment by zaneschepke** [comment]
I'll try to reproduce this issue on my end. 

> I think 99% Of the Android TV apps behave that way so I already did that multiple times but my biggest issue is that I cannot leave the textbox, there is no way to scroll to other options

I'll try to reproduce this issue on my end.

**Comment by zaneschepke** [comment]
@mpenachayan Which textbox are you unable to leave? I am seeing an issue on the settings screen where some of the UI is getting cutoff. I'll work on fixing that. On my Chromecast, I was able to edit DNS and add trusted SSIDs.

**Comment by mpenachayan** [comment]
I am not able to leave Trusted SSId texfield.
But i am not able to scroll through tunnel edit options neither general options.
I only can move through tunnel list and bottom menu bar

**Comment by zaneschepke** [comment]
> I am not able to leave Trusted SSId texfield. But i am not able to scroll through tunnel edit options neither general options. I only can move through tunnel list and bottom menu bar

What version of Android is your TV running?

**Comment by mpenachayan** [comment]
It's a Xiaomi Mi Stick 4K running Android 11.
As far as I know, it's running last software version

**Comment by keldian** [comment]
I too am unable to scroll past "Enable auto-tunneling" on CGTV. Version is 3.2.0 on Android 12 (STTK.230808.004.10714782)

**Comment by zaneschepke** [comment]
> I too am unable to scroll past `Enable auto-tunneling` on CGTV. Version is 3.2.0 on Android 12 (STTK.230808.004.10714782)

For AndroidTV version, there are no settings to scroll to past the Enable auto-tunneling setting. Those settings/features are only available for the mobile version because they are not supported on AndroidTV.

**Comment by keldian** [comment]
I see. I thought it was straight up the mobile app—didn't occur to me the UI would be different.

**Comment by zaneschepke** [comment]
> I see. I thought it was straight up the mobile app—didn't occur to me the UI would be different.

Yeah, those features won't work on AndroidTV so I thought it best to disable them.
