### ISSUE TITLE
Tunnel won't auto reconnect if internet goes down and comes back

### ISSUE THREAD

**Issue by rob77uk** [zaneschepke/wgtunnel#54]
Firstly thank you for making this great app. I'm running it on a shield and have been looking for a solution for my VPN to auto start on reboot and this works wonderfully.

The only issue I have is if the internet goes down and comes back up or I reboot my modem then the tunnel will stay connected but not reconnect. The little star at the side of my tunnel goes from green to red but stays like this forcing me to disconnect and reconnect to get internet access back.

Is there a way for it to auto reconnect if the tunnel goes down?

Thanks

**Comment by zaneschepke** [comment]
Hello! Thank you for using the app and reporting the issue. I'll try to reproduce this issue on my end and get back with you. It should be reconnecting automatically.

**Comment by zaneschepke** [comment]
@rob77uk I was unable to replicate this behavior. 

Is your WireGuard server self-hosted or cloud hosted? 

The only thing I can think of is somehow there is a DNS resolution issue or some other issue triggered by your network going down that is causing the app to fail re-establishing connection with the WireGuard server.

**Comment by rob77uk** [comment]
Hi Zane

Thank you for checking for me. The VPN service I'm using is Airvpn and I just use the default settings so it is using there own DNS servers. I also have your app split tunneling so only a couple of my apps are using wireguard. The rest go through the regular internet as it causes problems with netflix etc.

It's not a massive issue as I can just toggle off then on. If I can try any different setting please let me know.

Cheers

Rob

**Comment by zaneschepke** [comment]
I think this issue is related to #6. I think it is an issue with the IP having changed on the WG server and when the tunnel tries to re-establish connection it does not re-resolve the DNS, so you are unable to connect to the server. This would explain why restarting the tunnel fixes the issue, as WG will resolve DNS on the new connection.

**Comment by zaneschepke** [comment]
I have reopened #6, so I am going to make this one as closed.
