### ISSUE TITLE
[FEATURE] - Auto connect on data - auto disconnect on WIFI if no trusted SSID set

### ISSUE THREAD

**Issue by alexskynet** [zaneschepke/wgtunnel#56]
**Is your feature request related to a problem? Please describe.**
Hi and thank you for this nice app

I have some wifi networks that are connected to the office WG VPN so I only need tunnels UP on data

Tunnels have to stay down on WIFI and if I need I to activate them by hand if I need them on foreign untrusted WIFI's

The "Tunnel on mobile data" alone, with no trusted SSID, doesn't seem to do the job

**Describe the solution you'd like**
If ""Tunnel on mobile data" the tunnel comes up on data and if no SSID are specified, or we are connected to an already VPN connected WIFI, it goes down on WIFI connection
 
**Describe alternatives you've considered**
I tried to automate this with Automation but sometimes it fails: much better to use one single up to take up/down tunnels with no foreign integration

**Additional context**
WiFi I use are protected and already connected to the company's server, I only need tunnel to come up on mobile data and go down on any WIFI or on selected WIFI's

Thank you again for this great app

Best regards

Alessandro

**Comment by zaneschepke** [comment]
Hello! Thank you for using the app. I think this one is similar to #55 to auto tunneling only when on mobile data. 

This is a good idea. I will add it.

**Comment by alexskynet** [comment]
Thank you!

**Comment by zaneschepke** [comment]
Hello @alexskynet. I was looking through this one a bit more and I have some questions. If you add the Wi-Fi network SSIDs that are already connected to your office VPN to Trusted SSIDs, enable tunnel on mobile data, and turn on auto-tunneling, does that not solve your problem?

**Comment by peterzen** [comment]
This is my use case also - the auto tunnelling does indeed solve this problem.   

The settings UI doesn't make it quite clear that this is the case, though - when you enable the Auto tunnel then the disabling of the controls above it somehow suggest that those aren't in effect when in fact the opposite is true.  Maybe if auto tunneling would be above and _Tunnel on mobile/eth_ etc would be in a collapsible panel underneath that would make it really obvious.

Thanks for developing this app!

**Comment by zaneschepke** [comment]
Thank you for these ideas. I think it could be improved to be more clear. The reason the settings are disabled is so they cannot be changed while auto tunneling is active. 

I'm glad you are enjoying it and I will keep working to improve it!

**Comment by peterzen** [comment]
> Thank you for these ideas. I think it could be improved to be more clear. The reason the settings are disabled is so they cannot be changed while auto tunneling is active.

Would it be feasible to make the trusted SSID and the other settings changeable while *Auto tunnelling* is active?  Just for the sake of making the UI intuitively usable (it's no big deal having to turn the Auto tunnel switch off - making changes - then back on - but if the tunnel could be restarted behind the scenes then it would be trivial for a new user also.

**Comment by zaneschepke** [comment]
> > Thank you for these ideas. I think it could be improved to be more clear. The reason the settings are disabled is so they cannot be changed while auto tunneling is active.
> 
> Would it be feasible to make the trusted SSID and the other settings changeable while _Auto tunnelling_ is active? Just for the sake of making the UI intuitively usable (it's no big deal having to turn the Auto tunnel switch off - making changes - then back on - but if the tunnel could be restarted behind the scenes then it would be trivial for a new user also.

Allowing changes on the fly could cause unexpected behavior from auto tunneling, depending on when and what changes happen. I agree that the UI should be more intuitive for new users. I'll have to think on this one.
