### ISSUE TITLE
[FEATURE] - ACTION_BOOT_COMPLETED vs ACTION_LOCKED_BOOT_COMPLETED

### ISSUE THREAD

**Issue by olivluca** [zaneschepke/wgtunnel#59]
In my limited testing, I see that monitoring of network changes doesn't start until I manually unlock the device.
The app uses the [ACTION_BOOT_COMPLETED](https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED) intent, so that's expected.
Maybe it could use the [ACTION_LOCKED_BOOT_COMPLETED](https://developer.android.com/reference/android/content/Intent#ACTION_LOCKED_BOOT_COMPLETED) to start even before the user unlocks the device, but then maybe it doesn't have access to the settings.

**Comment by zaneschepke** [comment]
Thank you for the feedback! I think this would be great if it works. I will test it.

**Comment by zaneschepke** [comment]
I was unable to get this to work. I think because the phone has yet to be unlocked, there is limited functionality available. Thank you for sharing this info. I was not previously aware of that intent.

**Comment by olivluca** [comment]
Aren't you going to pursue this further?
The android documentation says that when the ACTION_LOCKED_BOOT_COMPLETED is broadcast only the device-protected storage is available (whatever that is), I guess you're storing the settings in credential-protected storage, hence you cannot start a tunnel because you cannot access the settings (there may be more hoops involved, this is android after all :wink:).
Maybe it's just a matter of moving the settings from one storage to the other, I don't know.
I wrote a simple app that uses ACTION_LOCKED_BOOT_COMPLETED but it doesn't need to access any storage (and I'm not really into android development so it was mostly a cut'n'paste exercise :wink: ).
In any case I think this is a real problem if you want to keep a tunnel always active when you're not using a trusted network and forget to unlock the phone once after it rebooted (especially if it rebooted by itself and you didn't notice).

**Comment by zaneschepke** [comment]
From my research, this is not possible on Android. Even Android's native Always on VPN does not start until you unlock the device. I have not seen any VPN apps that are able to do this on Android.

**Comment by olivluca** [comment]
You're most probably right: I'm using [automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) (unfortunately not open source) to start my wireguard tunnel and it is able to do so without unlocking the phone, but that phone has no lock screen (though I didn't manage to automatically start the tunnel at boot with wgtunnel on that phone, but I'll try again).
I cannot do that on another phone where I set up a pin: automate, just like wgtunnel and most other apps, doesn't start until I unlock the phone :disappointed: 
The only app that starts without unlocking the phone is [my own](https://github.com/olivluca/AAstarter) but that's quite useless :wink:.
