### ISSUE TITLE
[BUG] Unable to connect to tunnel, no connectivity

### ISSUE THREAD

**Issue by eMerzh** [zaneschepke/wgtunnel#61]
Hello, here :) 

thanks for work you put on this app 👏 

< mylife>
i have a tunnel from my phone to my home, today, there was an eletricity outage at my house, 
</ mylife>

so the tunnel was active, and all of a sudden, there wasn't any connectivity anymore... 
nothing to warn me about the issue, couldn't messaging, couldn't browse ... it took me a while to think about that 🤔 

To be honnest this drop my wife-acceptance-factor 😅 
could you help me regain that? :p 

**Smartphone (please complete the following information):**
 - Device:  Pixel 6a/4a
 - Android Version: 14
 - App Version 3.2.2 via fdroid

**To Reproduce**
1. have a working tunnel
2. somehow shut it down
3. what the world go silent

**Expected behavior**
Maybe disconnect the tunnel ? or at list give a warning ?

**Comment by zaneschepke** [comment]
Hello! With the default WireGuard configuration of no persistent keepalive, WireGuard sends a handshake request to the server on a 2.5 minute interval. If we have not received a successful handshake response within 3 minutes, the app will display a push notification notifying that there is an issue with the server connection and the status LED in the app should turn red. 

Did you not see this behavior?

**Comment by eMerzh** [comment]
hum... i did not see that 🤔  i have "battery saver" enabled as well as app shortcut.. the rest is disabled..

i'll maybe try to replicate the behavior to see

**Comment by zaneschepke** [comment]
No worries! I will try to replicate as well.
