### ISSUE TITLE
[FEATURE/Bug] - Airplane mode, battery draining + overheat

### ISSUE THREAD

**Issue by zamansoum** [zaneschepke/wgtunnel#67]
Hello, 
I noticed that when I put my phone into airplane mode, the app is constantly attempting to reach the vpn server even though the network card is turned off. This drained my battery by 40% in the span of 3h and my phone became hot as well. If I want to enable airplane mode, I have to disable auto-tunneling, turn the tunnel off and THEN turn airplane mode on. Would it be possible to keep the tunnel off or in a suspended state when the airplane mode is enabled or when no network access is detected at all.

Thank you

**Comment by zaneschepke** [comment]
Thank you for reporting this issue! This is a scenario I had not considered before and looks to be causing some pretty serious problems. I will look into a fix for this issue asap.

**Comment by zamansoum** [comment]
Thank you for looking into it. 

Clarification, my phone lost 40% battery in 3h **while not in use**
