### ISSUE TITLE
[FEATURE] - Better tunnel name when scanning QR code

### ISSUE THREAD

**Issue by stefansundin** [zaneschepke/wgtunnel#68]
**Is your feature request related to a problem? Please describe.**

I think the default tunnel name can be improved when importing tunnels by scanning QR codes. This would be especially useful when you need to import multiple configs and want to keep them easily identifiable.

**Describe the solution you'd like**

I think it would be great if the tunnel name could be defined in the config data. I'm having trouble finding an official spec for the config file, but [this website](https://docs.sweeting.me/s/wireguard#-Name1) documents a `# Name = ...` comment to define interface and peer names. If this is present then I think it would be a great default tunnel name.

If there isn't any `# Name =` comment then the endpoint hostname can be used.

So to summarize:

```ini
[Interface]
Address = 10.5.0.32/16
DNS = 8.8.8.8
PrivateKey = ...

[Peer]
# Name = Work VPN
PublicKey = ...
PresharedKey = ...
Endpoint = vpn.example.com:51820
PersistentKeepalive = 25
AllowedIPs = 0.0.0.0/0, ::/0
```

Resulting tunnel name when scanning QR code: `Work VPN`

If an existing tunnel already exists with this name, then name it `Work VPN (2)` or perhaps `Work VPN (2023-12-14)` (i.e. the current date).

```ini
[Interface]
Address = 10.5.0.32/16
DNS = 8.8.8.8
PrivateKey = ...

[Peer]
PublicKey = ...
PresharedKey = ...
Endpoint = vpn.example.com:51820
PersistentKeepalive = 25
AllowedIPs = 0.0.0.0/0, ::/0
```

Resulting tunnel name when scanning QR code: `vpn.example.com`

If an existing tunnel already exists with this name, then name it `vpn.example.com (2)` or perhaps `vpn.example.com (2023-12-14)` (i.e. the current date).

I hope this makes sense. Thanks for a great app.

**Describe alternatives you've considered**

N/A

**Additional context**

I love that this app allows more character in the tunnel names. The official WireGuard app limits it to 16 characters and I don't know why. So thanks for fixing this. 👍

**Comment by zaneschepke** [comment]
Hello! Thanks for using the app. I think this would be a beneficial improvement. I'll look into it.
