### ISSUE TITLE
[FEATURE] - AndroidAuto recognition

### ISSUE THREAD

**Issue by Uinsart** [zaneschepke/wgtunnel#69]
Hey, thanks again for this great app!
I would love to see the app recognize that I use Android Auto, and disables the VPN for the time conntected. Because AndroidAuto doesnt work with VPN enabled and doesnt disable it by itself.

Its because of this I cannot use the Auto-tunneling on mobile data.

Thanks again for your great work!

**Comment by zaneschepke** [comment]
Hello! This issue can actually be solved by setting up application split tunneling and excluding the android auto app from VPN. Please reference #29 for how to configure this in the app. This reminds me that this would be a great addition to our newly created documentation. I'll work on adding it to the docs.
