### ISSUE TITLE
[FEATURE] Notification Toggle behaviour suggestion

### ISSUE THREAD

**Issue by zilexa** [zaneschepke/wgtunnel#70]
**Is your feature request related to a problem? Please describe.**
When auto-tunneling is on and you are not connected to a trusted WiFi, but need to quickly "pause" the tunnel because you need access to something like public wifi or some page that doesn't work through the tunnel, the toggle is the way. 
Because you don't want to exit your app, find the rarely used WG-Tunnel app (since it is "configure-once-and-forget") go to settings (!) and disable auto-tunneling (because simply disconnecting would result in auto-reconnect). Also, once you are done you probably forget going back into the app to re-enable auto-tunneling. 

So the toggle is very important. However, currently, it seems to behave like this. 
0. start situation: auto-tunneling is on with a trusted wifi SSID.
1. Leave trusted WiFi --> notice the little key in notification bar, WG-Tunnel has autoconnected to VPN.
2. Notice also that the toggle in the notification bar is still "off". Not a big deal. But incorrect representation, since you are connected.
3. end up in a situation in which you want to disable VPN
4. Hit the toggle. Notice it was already off, but will now disable the tunnel (the key icon disappears)
5. Now, I perfom the actions I wanted to perform for which I needed to disable the tunnel... 
6. ... and I forget to hit the toggle again, because I just continue with my day
7. Now I get back home, trusted wifi connects.
8. When I leave my trusted wifi again, the tunnel does not auto connect.
9. Days pass, I forget I ever did action "5", and don't know why the tunnel doesn't auto connect.

**Describe the solution you'd like**
My suggestion is to always re-enable autotunneling -at least when it was "paused" via the toggle- when connected to the trusted wifi, to ensure it will work again next time. 

(Additionally, it would be nice if the colour of the toggle (enabled/disabled) would be linked to the key-icon you see in the top bar. Because now its mostly off, even when connected to tunnel. But this is really a minor issue. )

**Comment by zaneschepke** [comment]
Thank you for the detailed report and feedback!

I agree that this behavior is in need of improvement. I think your suggestion of resuming the auto-tunneling once you connect back to trusted network is a good one. I think this could even be taken a step further and resume auto-tunneling once you connect to a different SSID than the one that you originally paused on, but perhaps that is too aggressive. 

Overall, I really like the idea and think this would be a valuable improvement. Also, I am aware of the quick tile becoming out of sync with the real state of the VPN. I will look into a way to remedy that issue.

**Comment by zaneschepke** [comment]
With the new behavior of auto-tunneling only toggle once (instead of continually) per network change in version 3.4.3,  I think this issue is solved. Auto tunneling will automatically make the appropriate changes next time it detects a network state change regardless of the users toggling of the tunnel previously.
