### ISSUE TITLE
[BUG] - 3.2.4 crashes on tunnel attempt

### ISSUE THREAD

**Issue by phoropter** [zaneschepke/wgtunnel#71]
**Describe the bug**
The latest update will not connect to my tunnel via auto tunneling and just crashes when I attempt to enable it manually.

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - Android Version: 14, GrapheneOS
 - App Version 3.2.4

**To Reproduce**
1. Install 3.2.4
2. Import tunnel from zip
3. Attempt to connect to tunnel

**Comment by phoropter** [comment]
I have 
* Tunnel on untrusted wifi
* Tunnel on mobile data

Working on getting you a logcat output.

**Comment by zaneschepke** [comment]
> Ran `adb logcat | grep com.zaneschepke.wireguardautotunnel` and tried to connect to my tunnel, hope it has helpful info for you. [logcat.txt](https://github.com/zaneschepke/wgtunnel/files/13744005/logcat.txt)

Thank you so much. This is extremely helpful. It seems there is an issue with Android 14's change to foreground service permissions. I'll get a fix in for this asap.

**Comment by phoropter** [comment]
Glad that helped you nail it down quickly! And thanks for the super quick response!

**Comment by zaneschepke** [comment]
> Glad that helped you nail it down quickly! And thanks for the super quick response!

Thank you for reporting the issue! 😄

**Comment by phoropter** [comment]
I can confirm that it's working as expected in 3.2.5
