### ISSUE TITLE
[BUG] - Location services required on fire tv

### ISSUE THREAD

**Issue by G-Ray** [zaneschepke/wgtunnel#73]
On a Fire TV, one can allow location access for the app, but toggling "Enable auto-tunneling" does not work and a toast is displayed with "Location services required"

 - Device: Fire TV 4k max
 - App Version: 3.1.7

**Comment by IrgendwasmitBlech** [comment]
The same for me.
LineageOS 20 (Fairphone 4, no Gapps)

**Comment by zaneschepke** [comment]
> The same for me. LineageOS 20 (Fairphone 4, no Gapps)

Hello! I think the LineageOS is a separate issue. Please see here for a resolution: https://github.com/zaneschepke/wgtunnel/issues/60#issuecomment-1863773248

**Comment by zaneschepke** [comment]
> On a Fire TV, one can allow location access for the app, but toggling "Enable auto-tunneling" does not work and a toast is displayed with "Location services required"
> 
> * Device: Fire TV 4k max
> * App Version: 3.1.7

Hello! I will get a new version pushed to the Amazon store soon with a fix for this. I am sorry I have not updated the app listing in the Amazon store in a while. Unfortunately, there is no good way to integrate it with my deployment pipeline.

**Comment by IrgendwasmitBlech** [comment]
Hello,

thank you for the quick response.

I switch the location service in and off and in, but with untrusted wifi it is mit working.


Best regards
Bertram

Am 27. Dezember 2023 22:55:41 MEZ schrieb Zane Schepke ***@***.***>:
>> The same for me. LineageOS 20 (Fairphone 4, no Gapps)
>
>Hello! I think the LineageOS is a separate issue. Please see here for a resolution: https://github.com/zaneschepke/wgtunnel/issues/60#issuecomment-1863773248
>

**Comment by G-Ray** [comment]
> > On a Fire TV, one can allow location access for the app, but toggling "Enable auto-tunneling" does not work and a toast is displayed with "Location services required"
> > 
> > * Device: Fire TV 4k max
> > * App Version: 3.1.7
> 
> Hello! I will get a new version pushed to the Amazon store soon with a fix for this. I am sorry I have not updated the app listing in the Amazon store in a while. Unfortunately, there is no good way to integrate it with my deployment pipeline.
> 
> Is this an Android 10 device?

According to https://developer.amazon.com/docs/fire-tablets/fire-os-8.html the OS of this device (Fire TV 4k max **gen2**) is based on android 11.

The "official" wireguard app does not offer a solution to automatically enable the vpn connection after a reboot, so I hope `wgtunnel` will :hugs:

**Comment by zaneschepke** [comment]
Thank you for that info. Yes, WG Tunnel has this feature, but I am not sure whether or not it will work on AndroidTV. This is especially true for older versions of AndroidTV. I tried to test it on my emulator and it does not seem to be working. It may behave differently on your FireTV. 

This feature, in general, is not super reliable on certain android devices. It works very well on my Pixel 7 running GrapheneOS, but it does not work at all on my old Pixel XL running stock Google android.

**Comment by araujorm** [comment]
Hello.

Trying it now on a Mi Stick 4k (android 11), imported a tunnel and it works, but it isn't started after a reboot. If I open the app manually, it starts the tunnel.

So, it's confirmed that something is missing on this app for Android TV.

One app that works fine is Termux (after installing Termux:Boot plugin). Maybe some ideas could be taken from there?

Or at least as a workaround, could there be a possibility to launch WG Tunnel from termux boot?

**Comment by zaneschepke** [comment]
> Hello.
> 
> Trying it now on a Mi Stick 4k (android TV 11), imported a tunnel and it works, but it isn't started after a reboot. If I open the app manually, it starts the tunnel.
> 
> So, it's confirmed that something is missing on this app for Android TV.
> 
> One app that works fine to do stuff at boot is Termux (after installing Termux:Boot plugin). Maybe some ideas could be taken from there?
> 
> Or at least as a workaround, could there be a possibility to launch WG Tunnel from termux boot?

Thank you for this info. I took a look at termux boot and we are using the exact same strategy for boot. I'll have to dig into their further to figure out why it doesn't work consistently across devices. 

Can you confirm that termux boot works on your AndroidTV?

**Comment by araujorm** [comment]
> Can you confirm that termux boot works on your AndroidTV?

Yes, consistency across reboots.

> I was able to reproduce this issue. It seems to impact older devices. The problem is the older devices cannot read from the database on boot. I'm working on a fix now.

Could it be a timing issue? I've noticed that the things I start with Termux:Boot (for example the sshd daemon) take a while to be accessible after rebooting. So maybe a strategy would be to sleep if something fails and try again after a while (just guessing here).

**Comment by zaneschepke** [comment]
> > Can you confirm that termux boot works on your AndroidTV?
> 
> Yes, consistency across reboots.
> 
> > I was able to reproduce this issue. It seems to impact older devices. The problem is the older devices cannot read from the database on boot. I'm working on a fix now.
> 
> Could it be a timing issue? I've noticed that the things I start with Termux:Boot (for example the sshd daemon) take a while to be accessible after rebooting. So maybe a strategy would be to sleep if something fails and try again after a while (just guessing here).

There were a couple of different issues. The main one was how I was calling to start the service needed to specify startForeground. I'm not entire sure why these issues only appear on older devices, but in my testing this new fix is working on mobile and AndroidTV. I have a few more bugs to fix, but a fix for this one will be in this upcoming release. 

The goal is to have a new release build out (first available for download on GitHub) later today, tomorrow at the latest. 

Thank you for all of your help in testing this and the quick feedback!
