### ISSUE TITLE
[BUG] - 3.2.5 No Shortcut for Primary Connection

### ISSUE THREAD

**Issue by mtalexan** [zaneschepke/wgtunnel#74]
**Describe the bug**
With the latest FDroid version of the app (3.2.5), enabling the "Enable app shortcuts" does not make any shortcuts available, either from the stock launcher home screen, or from automation apps that list all available shortcuts.

**Smartphone (please complete the following information):**
 - Device: Pixel Food
 - Android Version: Android 14
 - App Version 3.2.5

**To Reproduce**
1. Add a connection
2. Activate it successfully
3. Deactivate it
4. Enable "Enable app shortcuts" in the settings
5. Go to home screen
6. Long press in open area
7. Pick "Widgets" (includes shortcuts as well)
8. Notice WGTunnel is not listed

**Expected behavior**
The shortcut to toggle the primary connection is available

**Comment by zaneschepke** [comment]
Hello! Thank you for using the app. The app shortcuts available are static shortcuts to toggle the primary tunnel. Please see the docs [here](https://zaneschepke.com/wgtunnel-docs/integrations.html#app-shortcuts) for how to use them. Additionally, if you wish to toggle individual tunnels there are intents available. Information on how to integrate with apps like Macrodroid is also mentioned in the docs. 

I'm sorry the docs are pretty sparse at the moment. I am working on improving them.

**Comment by mtalexan** [comment]
Ah, you're right, my mistake. I wasn't aware of the different types of shortcuts and that some of them aren't available to place on the home screen as icons.
