### ISSUE TITLE
[BUG] - Location permissions not detected

### ISSUE THREAD

**Issue by mtalexan** [zaneschepke/wgtunnel#75]
**Describe the bug**
GrNting all location permissions all the time, including precise location, auto-tunnelling reports it still doesn't have location permissions.

**Smartphone (please complete the following information):**
 - Device: Pixel Fold
 - Android Version: Android 14
 - App Version 3.2.5

**To Reproduce**
1. Go to WGTunnel in the App Setting
2. Open the Permissions
3. Select Location
4. Choose "Allow all the time"
5. Enable "Use precise location"
6. In the app, add a connection
7. Successfully activate it at least once
8. Enable Auto-tunnelling for untrusted wifi
9. Add a trusted wifi SSID
10. Enable Auto-tunnelling on mobile data
11. Click the "start auto-tunnelling" 
12. See the toast message "Location services required"

**Expected behavior**
It detecta the wifi network

**Screenshots (Only if necessary)**

**Additional context**
In the FDroid veraion of the app, there's no indication that Google Framework Services are required. I don't have any installed. Possibly this is just a documentation bug?

**Comment by zaneschepke** [comment]
Hello again :) Google services are not required for the app to function. You do still need to have Location services enabled on your phone in order to use auto-tunneling for untrusted WiFi networks (for that specific setting). In your phone settings, scroll down to "Location" and make sure it is enabled.

**Comment by mtalexan** [comment]
I did enable Location Services and granted the greatest level of permissions (always available, include precise location). I'm still getting the error.  
I played with the settings some more, and the auto-enable works as long as "untrusted wifi" isn't enabled. Though that tracks with what the permissions are needed for.  
The settings:  
![IMG_20231228_102041](https://github.com/zaneschepke/wgtunnel/assets/7081950/33011a6d-a383-4335-91af-6c6e80657360)
The error is in a toast message at the bottom of the image. It appears whenever I click "start auto-tunnel" with the "untrusted wifi" option enabled:  
![IMG_20231228_102204](https://github.com/zaneschepke/wgtunnel/assets/7081950/f88aaff1-c724-4b01-a120-bd2c496b1b3a)

**Comment by zaneschepke** [comment]
![Screenshot_20231228-104339.png](https://github.com/zaneschepke/wgtunnel/assets/25063592/c1c2bc2e-9d94-4ec1-8d99-10a8be879655)

![Screenshot_20231228-104407.png](https://github.com/zaneschepke/wgtunnel/assets/25063592/a7e656b9-3f13-405a-9b46-e2221be47370)

Is this enabled?

**Comment by mtalexan** [comment]
Yes, and location services are working in other apps.  
![IMG_20231228_112027](https://github.com/zaneschepke/wgtunnel/assets/7081950/2a40336a-bf94-4281-a8d5-c66453247a49)

**Comment by zaneschepke** [comment]
> Yes, and location services are working in other apps.  
> ![IMG_20231228_112027](https://github.com/zaneschepke/wgtunnel/assets/7081950/2a40336a-bf94-4281-a8d5-c66453247a49)
> 

Strange.. May I ask are you using Google's version of Android or something different like GrapheneOS?

**Comment by mtalexan** [comment]
I'm actually running CalyxOS without microG installed. But it sounds like it's working for you on GrapheneOS without Sandboxed play services installed.  Running down a bit of a rabbit hole, it seems like maybe GrapheneOS might provide it's own Unified NLP that can optionally use Sandboxed Google Play Services if present and configured. This Unified NLP is a part of the GSF normally, so on CalyxOS without microG it doesn't exist.

The Unified NLP existence shouldn't matter though, it's only useful for speeding up location lookups and getting more precise locations by checking other radio signal strengths and comparing to a lookup database. It's not necessary for determining what WiFi networks are currently connected. Tasker, in the same profile, has no issues getting the currently connected WiFi for example.
