### ISSUE TITLE
[FEATURE] - Add more languages

### ISSUE THREAD

**Issue by reconvene** [zaneschepke/wgtunnel#78]
**Is your feature request related to a problem? Please describe.**
It may make software easier to use by adding more supported languages

**Describe the solution you'd like**
Make the application support per-app language setting in Android 13+, and provide switching language option for the application of Android 12 and below
The language translation work can be distributed to other members in the community through **Weblate** or **Crowdin**

**Additional context**
Weblate  https://weblate.org/en/
Crowdin  https://crowdin.com/

**Comment by nillebor** [comment]
another possibility would be to offer the language in individual language files here. Because other users could take over the translation and upload the update here.

**Comment by zaneschepke** [comment]
Marking this one as closed as I think I have everything configured in Weblate properly now. We will work out the kinks as new translations are added.

**Comment by reconvene** [comment]
I'm sorry that I only saw your replies now. It's a great thing for me that my opinion is adopted by you, and this change is worth celebrating because it can lower the threshold for people in more areas.

**Comment by reconvene** [comment]
Hi bro, I am the person who requested your project called "WGtunnel" on github to add multi-language functionality. I just joined GitHub not long ago, so I don't know if I will expose my real email when I reply to you directly through email. Address. If you can see this email, please reply to me if you have seen my real email address. If so, please attach the email address you saw. Thank you very much!!!

**Comment by zaneschepke** [comment]
> Hi bro, I am the person who requested your project called "WGtunnel" on github to add multi-language functionality. I just joined GitHub not long ago, so I don't know if I will expose my real email when I reply to you directly through email. Address. If you can see this email, please reply to me if you have seen my real email address. If so, please attach the email address you saw. Thank you very much!!!

I don't see any email.

**Comment by reconvene** [comment]
That sounds good, it means that GitHub's email protection settings are effective. Thank you very much for your help.

---------------------------

> I don't see any email.
