### ISSUE TITLE
Notification icon is small than other icons

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#79]
Notification icon is small than other icons.
I think the you're using incorrect res sizes and suggest to increase.
Tried in a Redmi Note 9S and also in a Google Pixel 7Pro and same issue.
Thanks in advance

![image](https://github.com/zaneschepke/wgtunnel/assets/31618496/fe4acfe5-cef8-4667-8715-39a2805bd800)

**Comment by zaneschepke** [comment]
Thank for letting me know. I'll look into this!
