### ISSUE TITLE
[FEATURE] - Make settings lockable / password protected

### ISSUE THREAD

**Issue by ravor-org** [zaneschepke/wgtunnel#88]
Hello,

**Is your feature request related to a problem? Please describe.**
I'm looking for a simple solution for my kids' smartphones to force them to a wireguard VPN. I have setup a own WiFi, VLAN and VPN for my kids, so all the traffic is routed through my proxy server / ad-blocker at home. Unfortunately no app allows to effectively block changes in their configuration or simply turn it off at any time.

**Describe the solution you'd like**
Allow to set a password for switching the VPN on or off AND for changing the configuration. Important note here, we cannot rely on the Android password/biometrics feature as this is bound to the kids for unlocking their phones. So it needs to be independent.

**Describe alternatives you've considered**
I've already looked into other alternatives, e.g. AppLocker and similar tools, but these can either be circumvented somehow or include a lot of trackers / ads.

Best regards.

**Comment by zaneschepke** [comment]
Hello! I think this is a really good idea and it would be pretty easy to implement. I look into it.!

**Comment by SecureCPU** [comment]
Yes, we would really love this feature as well.
Thanks!
