### ISSUE TITLE
[BUG] - "Create from scratch" fails to add tunnel

### ISSUE THREAD

**Issue by edwardando** [zaneschepke/wgtunnel#89]
I'm using 3.3.2 from FDroid on LineageOS 20

On the create from scratch I fill in my details, when I press save, I get "Configuration setting saved." but no tunnels are added... what could be happening??

![Screenshot_20240110-201158_WG Tunnel](https://github.com/zaneschepke/wgtunnel/assets/2989690/dc1d0255-8b8c-4b52-8332-dfb91f928adf)

**Comment by zaneschepke** [comment]
Hello! Thank you for reporting this issue! There is a new release 3.3.3 available for download  on Github that might be worth trying as it has some bug fixes for the configuration screen. That release should be on Fdroid soon. 

Additionally, can you share details on which fields you populated? Ideally, can you share your entire config you tried to enter minus the public and private keys? Thank you!

**Comment by edwardando** [comment]
OK I'll wait for 3.3.3 to appear on FDroid and I'll report back here.

**Comment by edwardando** [comment]
Yes, I confirm it still disappears, looks like you're on the case, but I can give you some sample inputs if you want

**Comment by zaneschepke** [comment]
> Yes, I confirm it still disappears, looks like you're on the case, but I can give you some sample inputs if you want

That would be very help. Could you provide the sample input minus the keys. Thank you!

**Comment by edwardando** [comment]
Here are two screenshots of junk inputs, when I press save they vanish!

![Screenshot_20240117-220140_WG Tunnel](https://github.com/zaneschepke/wgtunnel/assets/2989690/684d6f72-ec40-4c58-
![Screenshot_20240117-220159_WG Tunnel](https://github.com/zaneschepke/wgtunnel/assets/2989690/6149f2cc-7061-4396-962b-214651c70843)
80ad-ee864a25942d)

**Comment by grapemix** [comment]
In my case:
version: 3.3.3 from fdriod
interface address: 10.10.10.2/32
endpoint: MY_PUBLIC_IP:51820

Just cannot create from scratch.

BTW, why does this app needs google play services? Some of us don't install it on purpose. It would be nice if this app doesn't depends on this lib. 

Thanks for this app.

**Comment by zaneschepke** [comment]
> In my case: version: 3.3.3 from fdriod interface address: 10.10.10.2/32 endpoint: MY_PUBLIC_IP:51820
> 
> Just cannot create from scratch.
> 
> BTW, why does this app needs google play services? Some of us don't install it on purpose. It would be nice if this app doesn't depends on this lib.
> 
> Thanks for this app.

Hello! The app needs location services depending on your flavor of Android in order to read Wi-Fi SSID which is considered precise location data (this is specifically for the auto-tunneling feature). This used to be required to start auto-tunneling, but is now optional to accommodate the various Android flavors.

**Comment by grapemix** [comment]
Thanks for your quick response. 

But wait, I think Google Play service scans and provides approximate location in the background periodically. The precise location is provided by GPS which requires additional permission and is not suitable for indoors use. I am not an expert on this topic, I am just getting curious and asking. Thanks.

ref: https://sc.vern.cc/@kostovtd/location-without-google-services-a591352ed0ba

**Comment by edwardando** [comment]
Great for the fix! @zaneschepke will the fixed version appear on FDroid soon?

**Comment by zaneschepke** [comment]
> Great for the fix! @zaneschepke will the fixed version appear on FDroid soon?

Unfortunately, F-Droid pipelines can take up to one week to update the app. I am looking into what it would take to self host a F-Droid repository for faster updates.

**Comment by edwardando** [comment]
I confirm that Version 3.3.4-test1 on FDroid solves this bug!

**Comment by zaneschepke** [comment]
Thank you for confirming this issue was fixed in 3.3.4. F-Droid should not be picking up *-test/beta/alpha versions so I'll have to look into that.
