### ISSUE TITLE
[BUG] - App crashes when VPN "always on" toggle is ON

### ISSUE THREAD

**Issue by msalini** [zaneschepke/wgtunnel#90]
**Describe the bug**
As I see ,the bug is not strictly originated by the app, but impacts it. 

Steps to reproduce it:
- Install the original Wireguard App
- Turn on "VPN always on" in VPN settings
- uninstall the app
- install WG tunnel app
- Open the app: the app crashes and flashes this message (see image below) for a split second.

In short, It seems that the original WG app retains the "always on" VPN setting even after being uninstalled, thus causing WG tunnel to crash after the first install. It is not possible to even create the VPN instance in the settings. And it is not possible to disable the "always ON" toggle as the previous VPN instance is not there anymore

**Smartphone (please complete the following information):**

- Device: Samsung SM-A520F
- Android Version: LineageOS 18.1 [Android 11]
- Rooting: The device is rooted
- App Version 3.3.3

**Expected behavior**
WG Tunnel should detect the "always On" "ghost setting" left from the previous install and avoid the crash. (I am not sure what else can be done to fix the VPN settings potentially compromised by the previous install)

**Screenshots (Only if necessary)**

![Message before crashing](https://github.com/zaneschepke/wgtunnel/assets/32898857/20c795dc-e266-42c5-874a-6bb1e7b80366)

**Additional context**
I believe this bug is primarily caused by the original WG app, however I do not know how to report it to them.

**Comment by zaneschepke** [comment]
Have you tried reinstalling the original app, going into app settings from android settings menu, remove all cache and storage of the original app, and then try to launch WG tunnel?

**Comment by msalini** [comment]
Yes I have. Doesn't work.
I have also reset all network settings.
Doesn't work either.
I am at loss.

**Comment by zaneschepke** [comment]
Try the same treatment for WG tunnel and reboot your phone. Samsung is notorious for not actually removing app data until after a reboot.

**Comment by msalini** [comment]
I went one step further
- Uninstall all WG apps
- reboot to recovery
- wipe dalvik/cache
- restart
- install WG tunnel: the app crashes again
- repeat the same steps with the original WG app
- the app throws out the msg "error bringing up the tunnel: service not authorised by the user"
- no VPN instance is created in the settings

Again, back to square one.

**Comment by zaneschepke** [comment]
Short of flashing the phone, I'm at a loss. I have a feeling that something was corrupted at the root system level and that is why we are not seeing any benefits from these steps. I assume you were using the kernel mode with the official WireGuard app when you uninstalled it?

**Comment by msalini** [comment]
god knows in which mode I was, but I think userspace.
Funny detail: I can use the WG app is kernel mode now (because it does bypass the creation of a VPN instance in settings) but I really do not want to as it occasionally crashes my entire device. Instead, the app in userspace mode was perfectly fine until I uninstalled it.

**Comment by zaneschepke** [comment]
To the best of my knowledge, It has to be done via API. Any luck/progress on this issue?

**Comment by zaneschepke** [comment]
This issue is being closed due to inactivity. If you are still having problems, feel free to open a new issue.
