### ISSUE TITLE
[BUG] - Unable to start a connection after changing allowed IPs

### ISSUE THREAD

**Issue by Veksi154** [zaneschepke/wgtunnel#95]
**Describe the bug**
Tunnel works great with the default allowed IPs (0.0.0.0/0, ::/0), but when I edit the config to only allow traffic to my home network (10.76.74.1/24) the tunnel refuses to start.

**Smartphone (please complete the following information):**

- Device: OnePlus 9 Pro
- Android Version: Android 13
- App Version: 3.3.2

**Comment by zaneschepke** [comment]
Hello! It is a little complicated to configure this type of routing for WireGuard. I recommend [this](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/) tool to help generate the proper allowedIps list to disable WireGuard for your home network subnet. I used this tool to enable this functionality for my home network and it works great.

Additionally, there is a pretty good discussion about using this feature [here](https://www.reddit.com/r/WireGuard/comments/awudup/how_to_exclude_local_network_packets_from/). 

If you continue to have issues we can reopen this issue, but I will close this issue for now.
