### ISSUE TITLE
[FEATURE] - Option to automatically start kernel mode VPN on boot

### ISSUE THREAD

**Issue by Golbinex** [zaneschepke/wgtunnel#96]
**Is your feature request related to a problem? Please describe.**
Always-on VPN is not working in kernel mode and VPN is disabled on boot.

**Describe the solution you'd like**
Additional option to automatically start VPN profile on boot.

**Describe alternatives you've considered**
There are currently two alternative options to automatically start kernel mode VPN on boot:
1. Auto-tunneling - this is a little overkill, because it constantly requests location even though I don't need untrusted Wi-Fi feature. It doesn't work without location.
2. Via activities - Requires automation and is little too overcomplicated

**Comment by zaneschepke** [comment]
Thank you for reporting this! This should be an easy fix. I'll get to work on it.

**Comment by zaneschepke** [comment]
I didn't have a phone to test this, but it should be working. Let me know if you run into any problems and we can reopen the issue.

**Comment by timur-g** [comment]
I use kernel mode VPN and tunnel does not start on boot. Did I miss how to set it or it just does not work for me?

**Comment by zaneschepke** [comment]
> I use kernel mode VPN and tunnel does not start on boot. Did I miss how to set it or it just does not work for me?

It should be working in the following situations:
1. Auto tunneling enabled
2. AOVPN enabled
3. Tunnel is running when reboot happens

If this isn't working for you let me know and we can reopen and investigate.

**Comment by timur-g** [comment]
Thanks. I do not use auto-tunneling, it says "background location required". But I have tunnel running when reboot happens.
In that (primary) tunnel I also have "set as mobile data tunnel" (but it may not be relevant as it is under auto-tunneling).
Upon reboot, I briefly see "VPN starting" in notifications, but it does not start.
